// packages/editor/apps/vue/seldon/parts/BarBreadcrumbsBar.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/**
 * Bar: BarBreadcrumbsBar
 * Level: Part
 * Intent: Groups related controls in a horizontal bar with buttons, navigation, or tabs layouts.
 * Tags: bar, controls, buttons, navigation, tabs, UI, layout, group
 * Type: Custom
 *
 * Structure:
 *   ButtonIconic  buttonIconic
 *     Icon        icon
 *   Icon          icon2
 *   Link          link
 *   Icon          icon3
 *   Link          link2
 *   Icon          icon4
 *   Link          link3
 *
 * @example
 * ```vue
 * <BarBreadcrumbsBar
 *   role="navigation"
 *   aria-hidden="false"
 * />
 * ```
 */
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"
import { combineClassNames, mergeSlot } from "../utils/class-names"
import ButtonIconic from "../elements/ButtonIconic.vue"
import Icon from "../primitives/Icon.vue"
import Link from "../primitives/Link.vue"

const props = defineProps<{
  className?: string
  buttonIconic?: Record<string, unknown> | null
  icon?: Record<string, unknown> | null
  icon2?: Record<string, unknown> | null
  link?: Record<string, unknown> | null
  icon3?: Record<string, unknown> | null
  link2?: Record<string, unknown> | null
  icon4?: Record<string, unknown> | null
  link3?: Record<string, unknown> | null
  seldonRefs?: Record<string, Record<string, unknown>>
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "role": "navigation",
  "aria-hidden": "false",
  "buttonIconic": {
    "className": "sdn-button-iconic sdn-button-iconic--pgsr"
  },
  "icon": {
    "icon": "seldon-component",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--rezm"
  },
  "icon2": {
    "icon": "material-chevronRight",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--ucf5"
  },
  "link": {
    "children": "Home",
    "aria-hidden": "false",
    "className": "sdn-link sdn-link--yqey"
  },
  "icon3": {
    "icon": "material-chevronRight",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--ucf5"
  },
  "link2": {
    "children": "Profile",
    "aria-hidden": "false",
    "className": "sdn-link sdn-link--yqey"
  },
  "icon4": {
    "icon": "material-chevronRight",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--ucf5"
  },
  "link3": {
    "children": "Settings",
    "aria-hidden": "false",
    "aria-current": "page",
    "className": "sdn-link sdn-link--yqey"
  }
}

const rootClassName = computed(() => combineClassNames("sdn-bar", props.className))
const rootAttrs = { "role": sdn["role"], "aria-hidden": sdn["aria-hidden"] }
const buttonIconicProps = computed(() => mergeSlot(sdn.buttonIconic, props.buttonIconic, props.seldonRefs))
const iconProps = computed(() => mergeSlot(sdn.icon, props.icon, props.seldonRefs))
const icon2Props = computed(() => mergeSlot(sdn.icon2, props.icon2, props.seldonRefs))
const linkProps = computed(() => mergeSlot(sdn.link, props.link, props.seldonRefs))
const icon3Props = computed(() => mergeSlot(sdn.icon3, props.icon3, props.seldonRefs))
const link2Props = computed(() => mergeSlot(sdn.link2, props.link2, props.seldonRefs))
const icon4Props = computed(() => mergeSlot(sdn.icon4, props.icon4, props.seldonRefs))
const link3Props = computed(() => mergeSlot(sdn.link3, props.link3, props.seldonRefs))
</script>

<template>
    <div :class="rootClassName" v-bind="rootAttrs">
      <slot>
        <ButtonIconic v-if="buttonIconicProps !== null" v-bind="buttonIconicProps" :icon="iconProps" />
        <Icon v-if="icon2Props !== null" v-bind="icon2Props" />
        <Link v-if="linkProps !== null" v-bind="linkProps" />
        <Icon v-if="icon3Props !== null" v-bind="icon3Props" />
        <Link v-if="link2Props !== null" v-bind="link2Props" />
        <Icon v-if="icon4Props !== null" v-bind="icon4Props" />
        <Link v-if="link3Props !== null" v-bind="link3Props" />
      </slot>
    </div>
</template>

// packages/editor/seldon/parts/BarBreadcrumbsBar.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/
import { HTMLAttributes } from "react"
import { ButtonIconic, ButtonIconicProps } from "../elements/ButtonIconic"
import { Frame } from "../frames/Frame"
import { Icon, IconProps } from "../primitives/Icon"
import { Link, LinkProps } from "../primitives/Link"
import { applyRef } from "../utils/apply-ref"
import { combineClassNames } from "../utils/class-name"

export interface BarBreadcrumbsBarProps extends HTMLAttributes<HTMLElement> {
  className?: string
  "data-seldon-ref"?: string
  seldonRefs?: Record<string, Record<string, unknown>>
  buttonIconic?: ButtonIconicProps | null
  icon?: IconProps | null
  icon2?: IconProps | null
  link?: LinkProps | null
  icon3?: IconProps | null
  link2?: LinkProps | null
  icon4?: IconProps | null
  link3?: LinkProps | null
}

/*****
 * Bar: BarBreadcrumbsBar
 * Level: Part
 * Intent: Groups related controls in a horizontal bar with buttons, navigation, or tabs layouts.
 * Tags: bar, controls, buttons, navigation, tabs, UI, layout, group
 * Type: Custom
 *
 * @example
 * ```tsx
 * <BarBreadcrumbsBar
 *   role="navigation"
 *   aria-hidden="false"
 * />
 * ```
 *****/
export function BarBreadcrumbsBar({
  className = "",
  buttonIconic = sdn.buttonIconic,
  icon = sdn.icon,
  icon2 = sdn.icon2,
  link = sdn.link,
  icon3 = sdn.icon3,
  link2 = sdn.link2,
  icon4 = sdn.icon4,
  link3 = sdn.link3,
  children,
  seldonRefs,
  ...props
}: BarBreadcrumbsBarProps) {
  const barBreadcrumbsBarClassName = combineClassNames("sdn-bar", className)
  const buttonIconicProps = applyRef(
    seldonRefs,
    buttonIconic === null
      ? null
      : {
          ...sdn.buttonIconic,
          ...buttonIconic,
          className: combineClassNames(
            sdn.buttonIconic?.className,
            buttonIconic?.className,
          ),
        },
  )
  const iconProps = applyRef(
    seldonRefs,
    icon === null
      ? null
      : {
          ...sdn.icon,
          ...icon,
          className: combineClassNames(sdn.icon?.className, icon?.className),
        },
  )
  const icon2Props = applyRef(
    seldonRefs,
    icon2 === null
      ? null
      : {
          ...sdn.icon2,
          ...icon2,
          className: combineClassNames(sdn.icon2?.className, icon2?.className),
        },
  )
  const linkProps = applyRef(
    seldonRefs,
    link === null
      ? null
      : {
          ...sdn.link,
          ...link,
          className: combineClassNames(sdn.link?.className, link?.className),
        },
  )
  const icon3Props = applyRef(
    seldonRefs,
    icon3 === null
      ? null
      : {
          ...sdn.icon3,
          ...icon3,
          className: combineClassNames(sdn.icon3?.className, icon3?.className),
        },
  )
  const link2Props = applyRef(
    seldonRefs,
    link2 === null
      ? null
      : {
          ...sdn.link2,
          ...link2,
          className: combineClassNames(sdn.link2?.className, link2?.className),
        },
  )
  const icon4Props = applyRef(
    seldonRefs,
    icon4 === null
      ? null
      : {
          ...sdn.icon4,
          ...icon4,
          className: combineClassNames(sdn.icon4?.className, icon4?.className),
        },
  )
  const link3Props = applyRef(
    seldonRefs,
    link3 === null
      ? null
      : {
          ...sdn.link3,
          ...link3,
          className: combineClassNames(sdn.link3?.className, link3?.className),
        },
  )

  return (
    <Frame
      className={barBreadcrumbsBarClassName}
      role={sdn["role"]}
      aria-hidden={sdn["aria-hidden"]}
      {...props}
    >
      {children !== undefined ? (
        children
      ) : (
        <>
          {buttonIconicProps !== null && (
            <ButtonIconic {...buttonIconicProps} icon={iconProps} />
          )}
          {icon2Props !== null && <Icon {...icon2Props} />}
          {linkProps !== null && <Link {...linkProps} />}
          {icon3Props !== null && <Icon {...icon3Props} />}
          {link2Props !== null && <Link {...link2Props} />}
          {icon4Props !== null && <Icon {...icon4Props} />}
          {link3Props !== null && <Link {...link3Props} />}
        </>
      )}
    </Frame>
  )
}

//
// Default property values
//
const sdn: BarBreadcrumbsBarProps = {
  role: "navigation",
  "aria-hidden": "false",
  className: "sdn-bar sdn-bar",
  buttonIconic: {
    className: "sdn-button-iconic sdn-button-iconic--pgsr",
  },
  icon: {
    icon: "seldon-component",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--rezm",
  },
  icon2: {
    icon: "material-chevronRight",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--ucf5",
  },
  link: {
    children: "Home",
    "aria-hidden": "false",
    className: "sdn-link sdn-link--yqey",
  },
  icon3: {
    icon: "material-chevronRight",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--ucf5",
  },
  link2: {
    children: "Profile",
    "aria-hidden": "false",
    className: "sdn-link sdn-link--yqey",
  },
  icon4: {
    icon: "material-chevronRight",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--ucf5",
  },
  link3: {
    children: "Settings",
    "aria-hidden": "false",
    "aria-current": "page",
    className: "sdn-link sdn-link--yqey",
  },
}
