// packages/editor/apps/react/seldon/parts/TopbarInlineLinks.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

import { HTMLAttributes } from "react"

import { Button, ButtonProps } from "../elements/Button"
import { Frame, FrameProps } from "../frames/Frame"
import { Image, ImageProps } from "../primitives/Image"
import { LinkPlain, LinkPlainProps } from "../primitives/LinkPlain"
import { TextLabel, TextLabelProps } from "../primitives/TextLabel"
import { combineClassNames } from "../utils/class-name"
import { SeldonRefs, mergeOptionalSlot, mergeSlot } from "../utils/merge-slot"

export interface TopbarInlineLinksProps extends HTMLAttributes<HTMLElement> {
  "data-seldon-ref"?: string
  seldonRefs?: SeldonRefs

  frame?: FrameProps | null
  linkPlain?: LinkPlainProps | null
  linkPlain2?: LinkPlainProps | null

  frame2?: FrameProps | null
  linkPlain3?: LinkPlainProps | null
  button?: ButtonProps | null
  textLabel?: TextLabelProps | null
  image?: ImageProps | null
}

//
// Default property values
//
const sdn: TopbarInlineLinksProps = {
  role: "banner",
  "aria-hidden": "false",
  frame: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--rclo",
  },
  linkPlain: {
    children: "Services",
    className: "sdn-link-plain sdn-link-plain--hnhh",
  },
  linkPlain2: {
    children: "Our Work",
    className: "sdn-link-plain sdn-link-plain--hnhh",
  },

  frame2: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--az2m",
  },
  linkPlain3: {
    children: "Contact",
    className: "sdn-link-plain sdn-link-plain--yc40",
  },
  button: {
    className: "sdn-button sdn-button--aket",
  },
  textLabel: {
    children: "Let&#039;s Connect",
    className: "sdn-text-label sdn-text-label--fcuq",
  },
  image: {
    className: "sdn-image sdn-image--guh3",
  },
}

/**
 * Topbar: TopbarInlineLinks
 * Level: Part
 * Intent: Site header that pairs a brand logo and wordmark with primary navigation and a call-to-action.
 * Tags: topbar, navbar, header, navigation, brand, menu, part, UI
 * Type: Inline
 *
 * Structure:
 *   Frame          frame
 *     LinkPlain    linkPlain
 *     LinkPlain    linkPlain2
 *   Frame          frame2
 *     LinkPlain    linkPlain3
 *     Button       button
 *       TextLabel  textLabel
 *     Image        image
 *
 * @example
 * ```tsx
 * <TopbarInlineLinks
 *   role="banner"
 *   aria-hidden="false"
 * />
 * ```
 */
export function TopbarInlineLinks({
  className = "",
  frame,
  linkPlain,
  linkPlain2,

  frame2,
  linkPlain3,
  button,
  textLabel,
  image,

  children,
  seldonRefs,
  ...props
}: TopbarInlineLinksProps) {
  const topbarInlineLinksClassName = combineClassNames("sdn-topbar", className)

  const frameProps = mergeSlot(sdn.frame, frame, seldonRefs)
  const linkPlainProps = mergeOptionalSlot(sdn.linkPlain, linkPlain, seldonRefs)
  const linkPlain2Props = mergeOptionalSlot(sdn.linkPlain2, linkPlain2, seldonRefs)

  const frame2Props = mergeSlot(sdn.frame2, frame2, seldonRefs)
  const linkPlain3Props = mergeOptionalSlot(sdn.linkPlain3, linkPlain3, seldonRefs)
  const buttonProps = mergeOptionalSlot(sdn.button, button, seldonRefs)
  const textLabelProps = mergeOptionalSlot(sdn.textLabel, textLabel, seldonRefs)
  const imageProps = mergeOptionalSlot(sdn.image, image, seldonRefs)

  return (
    <Frame
      className={topbarInlineLinksClassName}
      role={sdn["role"]}
      aria-hidden={sdn["aria-hidden"]}
      {...props}
    >
      {children !== undefined ? (
        children
      ) : (
        <>
          <Frame {...frameProps}>
            {linkPlainProps !== null && <LinkPlain {...linkPlainProps} />}
            {linkPlain2Props !== null && <LinkPlain {...linkPlain2Props} />}
          </Frame>
          <Frame {...frame2Props}>
            {linkPlain3Props !== null && <LinkPlain {...linkPlain3Props} />}
            {buttonProps !== null && (
              <Button {...buttonProps}>
                {textLabelProps !== null && <TextLabel {...textLabelProps} />}
              </Button>
            )}
            {imageProps !== null && <Image {...imageProps} />}
          </Frame>
        </>
      )}
    </Frame>
  )
}

// packages/editor/apps/vue/seldon/parts/TopbarInlineLinks.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/**
 * Topbar: TopbarInlineLinks
 * Level: Part
 * Intent: Site header that pairs a brand logo and wordmark with primary navigation and a call-to-action.
 * Tags: topbar, navbar, header, navigation, brand, menu, part, UI
 * Type: Inline
 *
 * Structure:
 *   Frame          frame
 *     LinkPlain    linkPlain
 *     LinkPlain    linkPlain2
 *   Frame          frame2
 *     LinkPlain    linkPlain3
 *     Button       button
 *       TextLabel  textLabel
 *     Image        image
 *
 * @example
 * ```vue
 * <TopbarInlineLinks
 *   role="banner"
 *   aria-hidden="false"
 * />
 * ```
 */
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"
import { combineClassNames, mergeSlot, mergeOptionalSlot } from "../utils/class-names"
import Frame from "../frames/Frame.vue"
import Button from "../elements/Button.vue"
import Image from "../primitives/Image.vue"
import LinkPlain from "../primitives/LinkPlain.vue"
import TextLabel from "../primitives/TextLabel.vue"

const props = defineProps<{
  className?: string
  frame?: Record<string, unknown> | null
  linkPlain?: Record<string, unknown> | null
  linkPlain2?: Record<string, unknown> | null
  frame2?: Record<string, unknown> | null
  linkPlain3?: Record<string, unknown> | null
  button?: Record<string, unknown> | null
  textLabel?: Record<string, unknown> | null
  image?: Record<string, unknown> | null
  seldonRefs?: Record<string, Record<string, unknown>>
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "role": "banner",
  "aria-hidden": "false",
  "frame": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--rclo"
  },
  "linkPlain": {
    "children": "Services",
    "className": "sdn-link-plain sdn-link-plain--hnhh"
  },
  "linkPlain2": {
    "children": "Our Work",
    "className": "sdn-link-plain sdn-link-plain--hnhh"
  },
  "frame2": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--az2m"
  },
  "linkPlain3": {
    "children": "Contact",
    "className": "sdn-link-plain sdn-link-plain--yc40"
  },
  "button": {
    "className": "sdn-button sdn-button--aket"
  },
  "textLabel": {
    "children": "Let&#039;s Connect",
    "className": "sdn-text-label sdn-text-label--fcuq"
  },
  "image": {
    "className": "sdn-image sdn-image--guh3"
  }
}

const rootClassName = computed(() => combineClassNames("sdn-topbar", props.className))
const rootAttrs = { "role": sdn["role"], "aria-hidden": sdn["aria-hidden"] }
const frameProps = computed(() => mergeSlot(sdn.frame, props.frame, props.seldonRefs))
const linkPlainProps = computed(() => mergeOptionalSlot(sdn.linkPlain, props.linkPlain, props.seldonRefs))
const linkPlain2Props = computed(() => mergeOptionalSlot(sdn.linkPlain2, props.linkPlain2, props.seldonRefs))
const frame2Props = computed(() => mergeSlot(sdn.frame2, props.frame2, props.seldonRefs))
const linkPlain3Props = computed(() => mergeOptionalSlot(sdn.linkPlain3, props.linkPlain3, props.seldonRefs))
const buttonProps = computed(() => mergeOptionalSlot(sdn.button, props.button, props.seldonRefs))
const textLabelProps = computed(() => mergeOptionalSlot(sdn.textLabel, props.textLabel, props.seldonRefs))
const imageProps = computed(() => mergeOptionalSlot(sdn.image, props.image, props.seldonRefs))
</script>

<template>
    <div :class="rootClassName" v-bind="rootAttrs">
      <slot>
        <Frame v-bind="frameProps">
          <LinkPlain v-if="linkPlainProps !== null" v-bind="linkPlainProps" />
          <LinkPlain v-if="linkPlain2Props !== null" v-bind="linkPlain2Props" />
        </Frame>
        <Frame v-bind="frame2Props">
          <LinkPlain v-if="linkPlain3Props !== null" v-bind="linkPlain3Props" />
          <Button v-if="buttonProps !== null" v-bind="buttonProps">
            <TextLabel v-if="textLabelProps !== null" v-bind="textLabelProps" />
          </Button>
          <Image v-if="imageProps !== null" v-bind="imageProps" />
        </Frame>
      </slot>
    </div>
</template>
