// packages/editor/apps/vue/app/home/HomePage.vue
<script setup lang="ts">
import { useToastStore } from "@app/toaster/toast-store"
import { stripPlatformSuffix } from "@seldon/editor/lib/helpers/strip-platform-suffix"
import { HOME_CONTENT } from "@seldon/editor/lib/home/home-content"
import { activateBinding } from "@seldon/editor/lib/storage/workspace-binding-store"
import {
  createStoredWorkspace,
  deleteStoredWorkspace,
  findImportMatch,
  listStoredWorkspaces,
  withFreshWorkspaceId,
} from "@seldon/editor/lib/storage/workspace-store"
import { onMounted, ref } from "vue"
import { useRouter } from "vue-router"

import { createEmptyWorkspace } from "@seldon/core"
import { setWorkspaceLabel } from "@seldon/core/workspace/reducers/handlers/set/set-workspace-label"

import type { Workspace } from "@seldon/core/workspace/types"
import type { StoredWorkspace } from "@seldon/editor/lib/storage/workspace-store"

const router = useRouter()
const toast = useToastStore()
const workspaces = ref<StoredWorkspace[]>([])
const loading = ref(true)
const fileInput = ref<HTMLInputElement | null>(null)

async function refresh(): Promise<void> {
  loading.value = true
  workspaces.value = await listStoredWorkspaces()
  loading.value = false
}

/** The name is the workspace label, so it is written before the record exists. */
async function create(): Promise<void> {
  const named = setWorkspaceLabel(
    { value: HOME_CONTENT.defaultWorkspaceName },
    createEmptyWorkspace(),
  )
  const record = await createStoredWorkspace(named)
  router.push(`/${record.id}`)
}

/** The name to show for a stored workspace, falling back for an unnamed one. */
function workspaceName(record: StoredWorkspace): string {
  return record.workspace.metadata.label || HOME_CONTENT.defaultWorkspaceName
}

/** Where a workspace is stored: its bound project, or the editor's live store. */
function storeLabel(record: StoredWorkspace): string {
  return record.boundProject ? `Project: ${record.boundProject}` : "Local"
}

// A bound workspace needs its folder grant re-taken before the open reads it,
// and a browser only grants during a gesture, so this runs in the click and
// navigates once the handle is live for the session.
async function open(record: StoredWorkspace): Promise<void> {
  if (record.boundProject) await activateBinding(record.id)
  router.push(`/${record.id}`)
}

async function remove(id: string): Promise<void> {
  if (!confirm(HOME_CONTENT.deleteConfirm)) return
  await deleteStoredWorkspace(id)
  await refresh()
}

async function duplicate(record: StoredWorkspace): Promise<void> {
  // A fresh id keeps the copy from overwriting the record it came from, so the
  // original and the duplicate both survive.
  const renamed = setWorkspaceLabel({ value: `${workspaceName(record)} copy` }, record.workspace)
  const copy = withFreshWorkspaceId(renamed)

  await createStoredWorkspace(copy)
  await refresh()
}

function triggerImport(): void {
  fileInput.value?.click()
}

async function onImportFile(event: Event): Promise<void> {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  input.value = ""
  if (!file) return
  try {
    const parsed = JSON.parse(await file.text()) as Partial<StoredWorkspace> | Workspace
    const workspace = ((parsed as Partial<StoredWorkspace>).workspace ?? parsed) as Workspace
    if (!workspace || typeof workspace !== "object" || !("nodes" in workspace)) {
      toast.addToast("Invalid workspace file")
      return
    }
    // An imported workspace carries its own name. A record file written before
    // the name moved into the label still has one, and the file name fills in.
    const legacyName = (parsed as { name?: string }).name
    const name = legacyName ?? stripPlatformSuffix(file.name.replace(/\.json$/i, ""))
    const named = workspace.metadata.label
      ? workspace
      : setWorkspaceLabel({ value: name }, workspace)

    // When this id is already bound to a project store, route the import there
    // rather than copying into the live store. A no-op when nothing is bound.
    if (named.metadata.id) await activateBinding(named.metadata.id)

    // A file exported from the editor keeps its `metadata.id`, so it resolves
    // back to the record it came from instead of duplicating. A rename is
    // confirmed, an import older than the stored copy is confirmed again, and
    // declining a rename keeps the import as its own workspace under a fresh id.
    const match = await findImportMatch(named)

    if (!match) {
      const record = await createStoredWorkspace(named)

      router.push(`/${record.id}`)

      return
    }

    const existingLabel =
      match.existing.workspace.metadata.label || HOME_CONTENT.defaultWorkspaceName
    const importedLabel = named.metadata.label || HOME_CONTENT.defaultWorkspaceName

    if (match.labelChanged) {
      const overwrite = confirm(
        `"${existingLabel}" is already stored as this workspace. Overwrite it with the imported "${importedLabel}"? Cancel keeps the import as a separate workspace.`,
      )

      if (!overwrite) {
        const record = await createStoredWorkspace(withFreshWorkspaceId(named))

        router.push(`/${record.id}`)

        return
      }
    }

    if (match.importIsOlder) {
      const proceed = confirm(
        `The imported copy of "${importedLabel}" is older than the stored workspace. Overwrite the newer version anyway?`,
      )

      if (!proceed) return
    }

    const record = await createStoredWorkspace(named)

    router.push(`/${record.id}`)
  } catch {
    toast.addToast("Could not read workspace file")
  }
}

onMounted(refresh)
</script>

<template>
  <main class="home">
    <h1 class="home-title">{{ HOME_CONTENT.title }}</h1>
    <p class="home-subtitle">{{ HOME_CONTENT.subtitle("Vue") }}</p>

    <div class="home-actions">
      <button class="home-create" @click="create">
        {{ HOME_CONTENT.newWorkspaceButton }}
      </button>
      <button class="home-import" @click="triggerImport">
        {{ HOME_CONTENT.openWorkspaceButton }}
      </button>
      <input
        ref="fileInput"
        type="file"
        accept="application/json,.json"
        class="home-file"
        @change="onImportFile"
      />
    </div>

    <h2 class="home-section-title">
      {{ HOME_CONTENT.recentWorkspacesHeading }}
    </h2>
    <p v-if="loading" class="home-empty">{{ HOME_CONTENT.loading }}</p>
    <p v-else-if="workspaces.length === 0" class="home-empty">
      {{ HOME_CONTENT.noWorkspaces }}
    </p>

    <ul v-else class="home-list">
      <li v-for="ws in workspaces" :key="ws.id" class="home-item">
        <button class="home-item__open" @click="open(ws)">
          <span class="home-item__name">{{ workspaceName(ws) }}</span>
          <span class="home-item__meta">
            <span class="home-item__store">{{ storeLabel(ws) }}</span> ·
            {{ ws.lastEditor ?? "?" }} ·
            {{ ws.updatedAt }}
          </span>
        </button>
        <button class="home-item__action" @click="duplicate(ws)">Duplicate</button>
        <button class="home-item__delete" @click="remove(ws.id)">
          {{ HOME_CONTENT.deleteButton }}
        </button>
      </li>
    </ul>
  </main>
</template>

<style scoped>
.home {
  margin: 0 auto;
  display: flex;
  min-height: 100vh;
  max-width: 42rem;
  flex-direction: column;
  gap: 2rem;
  padding: 2.5rem;
  color: #fff;
}
.home-title {
  font-size: 1.25rem;
  font-weight: 600;
}
.home-subtitle {
  margin-top: 0.5rem;
  font-size: 0.8125rem;
  color: rgba(255, 255, 255, 0.7);
}
.home-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
}
.home-section-title {
  margin-bottom: 0.75rem;
  font-size: 0.8125rem;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: rgba(255, 255, 255, 0.5);
}
.home-create {
  border-radius: 0.25rem;
  padding: 0.5rem 1rem;
  font-size: 0.8125rem;
  font-weight: 500;
  background: #fff;
  color: #000;
  border: none;
  cursor: pointer;
}
.home-import {
  border-radius: 0.25rem;
  padding: 0.5rem 1rem;
  font-size: 0.8125rem;
  border: 1px solid rgba(255, 255, 255, 0.3);
  background: transparent;
  color: inherit;
  cursor: pointer;
}
.home-file {
  display: none;
}
.home-item__action {
  padding: 0 0.75rem;
  border-radius: 0.25rem;
  border: 1px solid rgba(255, 255, 255, 0.3);
  background: transparent;
  color: inherit;
  font-size: 0.75rem;
  cursor: pointer;
}
.home-empty {
  font-size: 0.8125rem;
  color: rgba(255, 255, 255, 0.6);
}
.home-list {
  list-style: none;
  padding: 0;
  border-radius: 0.25rem;
  border: 1px solid rgba(255, 255, 255, 0.1);
}
.home-item {
  display: flex;
  align-items: stretch;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
}
.home-item + .home-item {
  border-top: 1px solid rgba(255, 255, 255, 0.1);
}
.home-item__open {
  flex: 1;
  display: flex;
  justify-content: space-between;
  align-items: center;
  min-width: 0;
  border: none;
  background: transparent;
  color: inherit;
  cursor: pointer;
  text-align: left;
}
.home-item__name {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-weight: 500;
}
.home-item__store {
  font-size: 0.75rem;
  color: rgba(255, 255, 255, 0.7);
  white-space: nowrap;
}
.home-item__meta {
  font-size: 0.75rem;
  color: rgba(255, 255, 255, 0.5);
  white-space: nowrap;
}
.home-item__delete {
  padding: 0 0.75rem;
  border-radius: 0.25rem;
  border: 1px solid rgba(255, 255, 255, 0.3);
  background: transparent;
  color: rgba(255, 255, 255, 0.5);
  font-size: 0.75rem;
  cursor: pointer;
}
.home-item__delete:hover {
  color: #fff;
}
</style>

// packages/editor/apps/react/app/home/HomePage.tsx
import { selectFile } from "@seldon/editor/lib/helpers/select-file"
import { stripPlatformSuffix } from "@seldon/editor/lib/helpers/strip-platform-suffix"
import { HOME_CONTENT } from "@seldon/editor/lib/home/home-content"
import { activateBinding } from "@seldon/editor/lib/storage/workspace-binding-store"
import {
  createStoredWorkspace,
  deleteStoredWorkspace,
  findImportMatch,
  listStoredWorkspaces,
  withFreshWorkspaceId,
} from "@seldon/editor/lib/storage/workspace-store"
import { useCallback, useEffect, useState } from "react"
import { useNavigate } from "react-router"

import { createEmptyWorkspace } from "@seldon/core"
import { setWorkspaceLabel } from "@seldon/core/workspace/reducers/handlers/set/set-workspace-label"

import { HomeView } from "./HomePage.bespoke"
import { useParseWorkspace } from "./hooks/use-parse-workspace"

import type { StoredWorkspace } from "@seldon/editor/lib/storage/workspace-store"

export default function HomePage() {
  const navigate = useNavigate()
  const parseWorkspace = useParseWorkspace()
  const [workspaces, setWorkspaces] = useState<StoredWorkspace[]>([])
  const [loading, setLoading] = useState(true)

  const refresh = useCallback(async () => {
    setWorkspaces(await listStoredWorkspaces())
    setLoading(false)
  }, [])

  useEffect(() => {
    void refresh()
  }, [refresh])

  // The name is the workspace label, so it is written into the new workspace
  // before the record is created.
  const handleNew = useCallback(async () => {
    const name =
      prompt(HOME_CONTENT.newWorkspaceNamePrompt, HOME_CONTENT.defaultWorkspaceName) ??
      HOME_CONTENT.defaultWorkspaceName
    const workspace = setWorkspaceLabel({ value: name }, createEmptyWorkspace())
    const record = await createStoredWorkspace(workspace)

    navigate(`/${record.id}`)
  }, [navigate])

  // An imported workspace carries its own name, so the file name only fills in
  // for one that was never named. A file exported from the editor keeps its
  // `metadata.id`, so it resolves back to the record it came from instead of
  // landing as a duplicate. Overwriting a match is guarded: a rename is
  // confirmed, and an import older than the stored copy is confirmed again so it
  // cannot clobber newer work. Declining a rename keeps the import as its own
  // workspace under a fresh id.
  const handleImport = useCallback(async () => {
    const result = await selectFile({ accept: ".json,application/json" })

    if (!result.success) return
    const { file } = result
    const text = await file.text()
    const parsed = parseWorkspace(text)
    const fileName = stripPlatformSuffix(file.name.replace(/\.json$/i, "")) || "Imported workspace"
    const workspace = parsed.metadata.label
      ? parsed
      : setWorkspaceLabel({ value: fileName }, parsed)

    // When this id is already bound to a project store, route the import there
    // rather than copying into the live store. A no-op when nothing is bound.
    if (workspace.metadata.id) await activateBinding(workspace.metadata.id)

    const match = await findImportMatch(workspace)

    if (!match) {
      const record = await createStoredWorkspace(workspace)

      navigate(`/${record.id}`)

      return
    }

    const existingLabel =
      match.existing.workspace.metadata.label || HOME_CONTENT.defaultWorkspaceName
    const importedLabel = workspace.metadata.label || HOME_CONTENT.defaultWorkspaceName

    if (match.labelChanged) {
      const overwrite = confirm(
        `"${existingLabel}" is already stored as this workspace. Overwrite it with the imported "${importedLabel}"? Cancel keeps the import as a separate workspace.`,
      )

      if (!overwrite) {
        const record = await createStoredWorkspace(withFreshWorkspaceId(workspace))

        navigate(`/${record.id}`)

        return
      }
    }

    if (match.importIsOlder) {
      const proceed = confirm(
        `The imported copy of "${importedLabel}" is older than the stored workspace. Overwrite the newer version anyway?`,
      )

      if (!proceed) return
    }

    const record = await createStoredWorkspace(workspace)

    navigate(`/${record.id}`)
  }, [navigate, parseWorkspace])

  // A bound workspace needs its folder grant re-taken before the open reads it,
  // and a browser only grants during a gesture, so this runs in the click and
  // navigates once the handle is live for the session.
  const handleOpen = useCallback(
    async (ws: StoredWorkspace) => {
      if (ws.boundProject) await activateBinding(ws.id)
      navigate(`/${ws.id}`)
    },
    [navigate],
  )

  const handleDelete = useCallback(
    async (id: string) => {
      if (!confirm(HOME_CONTENT.deleteConfirm)) return
      await deleteStoredWorkspace(id)
      await refresh()
    },
    [refresh],
  )

  return (
    <HomeView
      workspaces={workspaces}
      loading={loading}
      onNew={handleNew}
      onImport={handleImport}
      onOpen={handleOpen}
      onDelete={handleDelete}
    />
  )
}
