// packages/editor/apps/vue/seldon/parts/BarState.vue
/***** * * This code was generated using Seldon (https://github.com/SeldonDigital/seldon) * *
License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md * Do not redistribute or
sublicense without permission. * * You may not use this software, or any derivative works of it, in
whole or in part, * for the purposes of training, fine-tuning, or otherwise improving (directly or
indirectly) * any machine learning or artificial intelligence system without written permission. *
*****/

<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/**
 * Bar: BarState
 * Level: Part
 * Intent: Groups related controls in a horizontal bar with buttons, navigation, or tabs layouts.
 * Tags: bar, controls, buttons, navigation, tabs, UI, layout, group
 * Type: Custom
 *
 * Structure:
 *   ButtonMenu   buttonMenu  -> propertyState
 *     TextLabel  textLabel   -> propertyStateLabel
 *     Icon       icon        -> propertyStateIcon
 *
 * @example
 * ```vue
 * <BarState
 *   aria-hidden="false"
 *   buttonMenu={() => {}}
 *   textLabel="{}"
 *   icon="material-star"
 * />
 * ```
 */
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"

import ButtonMenu from "../elements/ButtonMenu.vue"
import Icon from "../primitives/Icon.vue"
import TextLabel from "../primitives/TextLabel.vue"
import { combineClassNames, mergeOptionalSlot, mergeSlot } from "../utils/class-names"

const props = defineProps<{
  className?: string
  buttonMenu?: Record<string, unknown> | null
  textLabel?: Record<string, unknown> | null
  icon?: Record<string, unknown> | null
  seldonRefs?: Record<string, Record<string, unknown>>
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "aria-hidden": "false",
  buttonMenu: {
    className: "sdn-button-menu sdn-button-iconic--pgsr",
    "data-seldon-ref": "propertyState",
  },
  textLabel: {
    children: "Button Menu",
    className: "sdn-text-label sdn-text-label--sa6t",
    "data-seldon-ref": "propertyStateLabel",
  },
  icon: {
    icon: "material-chevronDown",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--y2ct",
    "data-seldon-ref": "propertyStateIcon",
  },
}

const rootClassName = computed(() => combineClassNames("sdn-bar-state", props.className))
const rootAttrs = { "aria-hidden": sdn["aria-hidden"] }
const buttonMenuProps = computed(() =>
  mergeOptionalSlot(sdn.buttonMenu, props.buttonMenu, props.seldonRefs),
)
const textLabelProps = computed(() =>
  mergeOptionalSlot(sdn.textLabel, props.textLabel, props.seldonRefs),
)
const iconProps = computed(() => mergeSlot(sdn.icon, props.icon, props.seldonRefs))
</script>

<template>
  <div :class="rootClassName" v-bind="rootAttrs">
    <slot>
      <ButtonMenu v-if="buttonMenuProps !== null" v-bind="buttonMenuProps">
        <TextLabel v-if="textLabelProps !== null" v-bind="textLabelProps" />
        <Icon v-if="iconProps !== null" v-bind="iconProps" />
      </ButtonMenu>
    </slot>
  </div>
</template>

// packages/editor/apps/react/seldon/parts/BarState.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

import { HTMLAttributes } from "react"

import { ButtonMenu, ButtonMenuProps } from "../elements/ButtonMenu"
import { Frame } from "../frames/Frame"
import { Icon, IconProps } from "../primitives/Icon"
import { TextLabel, TextLabelProps } from "../primitives/TextLabel"
import { combineClassNames } from "../utils/class-name"
import { SeldonRefs, mergeOptionalSlot, mergeSlot } from "../utils/merge-slot"

export interface BarStateProps extends HTMLAttributes<HTMLElement> {
  "data-seldon-ref"?: string
  seldonRefs?: SeldonRefs

  buttonMenu?: ButtonMenuProps | null
  textLabel?: TextLabelProps | null
  icon?: IconProps | null
}

//
// Default property values
//
const sdn: BarStateProps = {
  "aria-hidden": "false",
  buttonMenu: {
    className: "sdn-button-menu sdn-button-iconic--pgsr",
    "data-seldon-ref": "propertyState",
  },
  textLabel: {
    children: "Button Menu",
    className: "sdn-text-label sdn-text-label--sa6t",
    "data-seldon-ref": "propertyStateLabel",
  },
  icon: {
    icon: "material-chevronDown",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--y2ct",
    "data-seldon-ref": "propertyStateIcon",
  },
}

/**
 * Bar: BarState
 * Level: Part
 * Intent: Groups related controls in a horizontal bar with buttons, navigation, or tabs layouts.
 * Tags: bar, controls, buttons, navigation, tabs, UI, layout, group
 * Type: Custom
 *
 * Structure:
 *   ButtonMenu   buttonMenu  -> propertyState
 *     TextLabel  textLabel   -> propertyStateLabel
 *     Icon       icon        -> propertyStateIcon
 *
 * @example
 * ```tsx
 * <BarState
 *   aria-hidden="false"
 *   buttonMenu={() => {}}
 *   textLabel="{}"
 *   icon="material-star"
 * />
 * ```
 */
export function BarState({
  className = "",
  buttonMenu,
  textLabel,
  icon,

  children,
  seldonRefs,
  ...props
}: BarStateProps) {
  const barStateClassName = combineClassNames("sdn-bar-state", className)

  const buttonMenuProps = mergeOptionalSlot(sdn.buttonMenu, buttonMenu, seldonRefs)
  const textLabelProps = mergeOptionalSlot(sdn.textLabel, textLabel, seldonRefs)
  const iconProps = mergeSlot(sdn.icon, icon, seldonRefs)

  return (
    <Frame className={barStateClassName} aria-hidden={sdn["aria-hidden"]} {...props}>
      {children !== undefined ? (
        children
      ) : (
        <>
          {buttonMenuProps !== null && (
            <ButtonMenu {...buttonMenuProps}>
              {textLabelProps !== null && <TextLabel {...textLabelProps} />}
              {iconProps !== null && <Icon {...iconProps} />}
            </ButtonMenu>
          )}
        </>
      )}
    </Frame>
  )
}
