// packages/editor-vue/seldon/parts/Menu.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/*****
 * Menu: Menu
 * Level: Part
 * Intent: Floating list of actions anchored to a trigger.
 * Tags: menu, dropdown, actions, part, overlay, UI
 * Type: Default
 *
 * @example
 * ```vue
 * <Menu
 *   role="menu"
 *   aria-hidden="false"
 * />
 * ```
 *****/
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"
import { combineClassNames, mergeSlot } from "../utils/class-names"
import Hr from "../primitives/Hr.vue"
import Icon from "../primitives/Icon.vue"
import MenuItem from "../elements/MenuItem.vue"
import MenuItemCheckbox from "../elements/MenuItemCheckbox.vue"
import MenuItemRadio from "../elements/MenuItemRadio.vue"
import TextLabel from "../primitives/TextLabel.vue"

const props = defineProps<{
  className?: string
  menuItem?: Record<string, unknown> | null
  icon?: Record<string, unknown> | null
  textLabel?: Record<string, unknown> | null
  textLabel2?: Record<string, unknown> | null
  menuItem2?: Record<string, unknown> | null
  icon2?: Record<string, unknown> | null
  textLabel3?: Record<string, unknown> | null
  textLabel4?: Record<string, unknown> | null
  hr?: Record<string, unknown> | null
  menuItemCheckbox?: Record<string, unknown> | null
  icon3?: Record<string, unknown> | null
  textLabel5?: Record<string, unknown> | null
  menuItemRadio?: Record<string, unknown> | null
  icon4?: Record<string, unknown> | null
  textLabel6?: Record<string, unknown> | null
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "role": "menu",
  "aria-hidden": "false",
  "className": "sdn-menu",
  "menuItem": {
    "role": "menuitem",
    "aria-hidden": "false",
    "className": "sdn-menu-item sdn-menu-item--rrtt"
  },
  "icon": {
    "icon": "seldon-component",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--3qou"
  },
  "textLabel": {
    "className": "sdn-text-label sdn-text-label--xohb"
  },
  "textLabel2": {
    "className": "sdn-text-label sdn-text-label--fdei"
  },
  "menuItem2": {
    "role": "menuitem",
    "aria-hidden": "false",
    "className": "sdn-menu-item sdn-menu-item--rrtt"
  },
  "icon2": {
    "icon": "seldon-component",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--3qou"
  },
  "textLabel3": {
    "className": "sdn-text-label sdn-text-label--xohb"
  },
  "textLabel4": {
    "className": "sdn-text-label sdn-text-label--fdei"
  },
  "hr": {
    "aria-hidden": "false",
    "className": "sdn-hr sdn-hr--lrmt"
  },
  "menuItemCheckbox": {
    "role": "menuitemcheckbox",
    "aria-hidden": "false",
    "className": "sdn-menu-item sdn-menu-item--rrtt"
  },
  "icon3": {
    "icon": "material-check",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--3qou"
  },
  "textLabel5": {
    "className": "sdn-text-label sdn-text-label--xohb"
  },
  "menuItemRadio": {
    "role": "menuitemradio",
    "aria-hidden": "false",
    "className": "sdn-menu-item sdn-menu-item--rrtt"
  },
  "icon4": {
    "icon": "material-radioButtonChecked",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--3qou"
  },
  "textLabel6": {
    "className": "sdn-text-label sdn-text-label--xohb"
  }
}

const rootClassName = computed(() => combineClassNames("sdn-menu", props.className))
const rootAttrs = { "role": sdn["role"], "aria-hidden": sdn["aria-hidden"] }
const menuItemProps = computed(() => mergeSlot(sdn.menuItem, props.menuItem))
const iconProps = computed(() => mergeSlot(sdn.icon, props.icon))
const textLabelProps = computed(() => mergeSlot(sdn.textLabel, props.textLabel))
const textLabel2Props = computed(() => mergeSlot(sdn.textLabel2, props.textLabel2))
const menuItem2Props = computed(() => mergeSlot(sdn.menuItem2, props.menuItem2))
const icon2Props = computed(() => mergeSlot(sdn.icon2, props.icon2))
const textLabel3Props = computed(() => mergeSlot(sdn.textLabel3, props.textLabel3))
const textLabel4Props = computed(() => mergeSlot(sdn.textLabel4, props.textLabel4))
const hrProps = computed(() => mergeSlot(sdn.hr, props.hr))
const menuItemCheckboxProps = computed(() => mergeSlot(sdn.menuItemCheckbox, props.menuItemCheckbox))
const icon3Props = computed(() => mergeSlot(sdn.icon3, props.icon3))
const textLabel5Props = computed(() => mergeSlot(sdn.textLabel5, props.textLabel5))
const menuItemRadioProps = computed(() => mergeSlot(sdn.menuItemRadio, props.menuItemRadio))
const icon4Props = computed(() => mergeSlot(sdn.icon4, props.icon4))
const textLabel6Props = computed(() => mergeSlot(sdn.textLabel6, props.textLabel6))
</script>

<template>
    <div :class="rootClassName" v-bind="rootAttrs">
      <slot>
        <MenuItem v-if="menuItemProps !== null" v-bind="menuItemProps">
          <Icon v-if="iconProps !== null" v-bind="iconProps" />
          <TextLabel v-if="textLabel && textLabelProps" v-bind="textLabelProps" />
          <TextLabel v-if="textLabel2 && textLabel2Props" v-bind="textLabel2Props" />
        </MenuItem>
        <MenuItem v-if="menuItem2Props !== null" v-bind="menuItem2Props">
          <Icon v-if="icon2Props !== null" v-bind="icon2Props" />
          <TextLabel v-if="textLabel3 && textLabel3Props" v-bind="textLabel3Props" />
          <TextLabel v-if="textLabel4 && textLabel4Props" v-bind="textLabel4Props" />
        </MenuItem>
        <Hr v-if="hrProps !== null" v-bind="hrProps" />
        <MenuItemCheckbox v-if="menuItemCheckboxProps !== null" v-bind="menuItemCheckboxProps">
          <Icon v-if="icon3Props !== null" v-bind="icon3Props" />
          <TextLabel v-if="textLabel5 && textLabel5Props" v-bind="textLabel5Props" />
        </MenuItemCheckbox>
        <MenuItemRadio v-if="menuItemRadioProps !== null" v-bind="menuItemRadioProps">
          <Icon v-if="icon4Props !== null" v-bind="icon4Props" />
          <TextLabel v-if="textLabel6 && textLabel6Props" v-bind="textLabel6Props" />
        </MenuItemRadio>
      </slot>
    </div>
</template>

// packages/editor/apps/react/seldon/parts/Menu.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/
import { HTMLAttributes } from "react"

import { MenuItem, MenuItemProps } from "../elements/MenuItem"
import {
  MenuItemCheckbox,
  MenuItemCheckboxProps,
} from "../elements/MenuItemCheckbox"
import { MenuItemRadio, MenuItemRadioProps } from "../elements/MenuItemRadio"
import { Frame } from "../frames/Frame"
import { Hr, HrProps } from "../primitives/Hr"
import { Icon, IconProps } from "../primitives/Icon"
import { TextLabel, TextLabelProps } from "../primitives/TextLabel"
import { applyRef } from "../utils/apply-ref"
import { combineClassNames } from "../utils/class-name"

export interface MenuProps extends HTMLAttributes<HTMLElement> {
  className?: string
  "data-seldon-ref"?: string
  seldonRefs?: Record<string, Record<string, unknown>>
  menuItem?: MenuItemProps | null
  icon?: IconProps | null
  textLabel?: TextLabelProps | null
  textLabel2?: TextLabelProps | null
  menuItem2?: MenuItemProps | null
  icon2?: IconProps | null
  textLabel3?: TextLabelProps | null
  textLabel4?: TextLabelProps | null
  hr?: HrProps | null
  menuItemCheckbox?: MenuItemCheckboxProps | null
  icon3?: IconProps | null
  textLabel5?: TextLabelProps | null
  menuItemRadio?: MenuItemRadioProps | null
  icon4?: IconProps | null
  textLabel6?: TextLabelProps | null
}

/*****
 * Menu: Menu
 * Level: Part
 * Intent: Floating list of actions anchored to a trigger.
 * Tags: menu, dropdown, actions, part, overlay, UI
 * Type: Default
 *
 * @example
 * ```tsx
 * <Menu
 *   role="menu"
 *   aria-hidden="false"
 * />
 * ```
 *****/
export function Menu({
  className = "",
  menuItem = sdn.menuItem,
  icon = sdn.icon,
  textLabel,
  textLabel2,
  menuItem2 = sdn.menuItem2,
  icon2 = sdn.icon2,
  textLabel3,
  textLabel4,
  hr = sdn.hr,
  menuItemCheckbox = sdn.menuItemCheckbox,
  icon3 = sdn.icon3,
  textLabel5,
  menuItemRadio = sdn.menuItemRadio,
  icon4 = sdn.icon4,
  textLabel6,
  children,
  seldonRefs,
  ...props
}: MenuProps) {
  const menuClassName = combineClassNames("sdn-menu", className)
  const menuItemProps = applyRef(
    seldonRefs,
    menuItem === null
      ? null
      : {
          ...sdn.menuItem,
          ...menuItem,
          className: combineClassNames(
            sdn.menuItem?.className,
            menuItem?.className,
          ),
        },
  )
  const iconProps = applyRef(
    seldonRefs,
    icon === null
      ? null
      : {
          ...sdn.icon,
          ...icon,
          className: combineClassNames(sdn.icon?.className, icon?.className),
        },
  )
  const textLabelProps = applyRef(
    seldonRefs,
    textLabel === null
      ? null
      : {
          ...sdn.textLabel,
          ...textLabel,
          className: combineClassNames(
            sdn.textLabel?.className,
            textLabel?.className,
          ),
        },
  )
  const textLabel2Props = applyRef(
    seldonRefs,
    textLabel2 === null
      ? null
      : {
          ...sdn.textLabel2,
          ...textLabel2,
          className: combineClassNames(
            sdn.textLabel2?.className,
            textLabel2?.className,
          ),
        },
  )
  const menuItem2Props = applyRef(
    seldonRefs,
    menuItem2 === null
      ? null
      : {
          ...sdn.menuItem2,
          ...menuItem2,
          className: combineClassNames(
            sdn.menuItem2?.className,
            menuItem2?.className,
          ),
        },
  )
  const icon2Props = applyRef(
    seldonRefs,
    icon2 === null
      ? null
      : {
          ...sdn.icon2,
          ...icon2,
          className: combineClassNames(sdn.icon2?.className, icon2?.className),
        },
  )
  const textLabel3Props = applyRef(
    seldonRefs,
    textLabel3 === null
      ? null
      : {
          ...sdn.textLabel3,
          ...textLabel3,
          className: combineClassNames(
            sdn.textLabel3?.className,
            textLabel3?.className,
          ),
        },
  )
  const textLabel4Props = applyRef(
    seldonRefs,
    textLabel4 === null
      ? null
      : {
          ...sdn.textLabel4,
          ...textLabel4,
          className: combineClassNames(
            sdn.textLabel4?.className,
            textLabel4?.className,
          ),
        },
  )
  const hrProps = applyRef(
    seldonRefs,
    hr === null
      ? null
      : {
          ...sdn.hr,
          ...hr,
          className: combineClassNames(sdn.hr?.className, hr?.className),
        },
  )
  const menuItemCheckboxProps = applyRef(
    seldonRefs,
    menuItemCheckbox === null
      ? null
      : {
          ...sdn.menuItemCheckbox,
          ...menuItemCheckbox,
          className: combineClassNames(
            sdn.menuItemCheckbox?.className,
            menuItemCheckbox?.className,
          ),
        },
  )
  const icon3Props = applyRef(
    seldonRefs,
    icon3 === null
      ? null
      : {
          ...sdn.icon3,
          ...icon3,
          className: combineClassNames(sdn.icon3?.className, icon3?.className),
        },
  )
  const textLabel5Props = applyRef(
    seldonRefs,
    textLabel5 === null
      ? null
      : {
          ...sdn.textLabel5,
          ...textLabel5,
          className: combineClassNames(
            sdn.textLabel5?.className,
            textLabel5?.className,
          ),
        },
  )
  const menuItemRadioProps = applyRef(
    seldonRefs,
    menuItemRadio === null
      ? null
      : {
          ...sdn.menuItemRadio,
          ...menuItemRadio,
          className: combineClassNames(
            sdn.menuItemRadio?.className,
            menuItemRadio?.className,
          ),
        },
  )
  const icon4Props = applyRef(
    seldonRefs,
    icon4 === null
      ? null
      : {
          ...sdn.icon4,
          ...icon4,
          className: combineClassNames(sdn.icon4?.className, icon4?.className),
        },
  )
  const textLabel6Props = applyRef(
    seldonRefs,
    textLabel6 === null
      ? null
      : {
          ...sdn.textLabel6,
          ...textLabel6,
          className: combineClassNames(
            sdn.textLabel6?.className,
            textLabel6?.className,
          ),
        },
  )

  return (
    <Frame
      className={menuClassName}
      role={sdn["role"]}
      aria-hidden={sdn["aria-hidden"]}
      {...props}
    >
      {children !== undefined ? (
        children
      ) : (
        <>
          {menuItemProps !== null && (
            <MenuItem {...menuItemProps}>
              {icon && iconProps && <Icon {...iconProps} />}
              {textLabel && textLabelProps && <TextLabel {...textLabelProps} />}
              {textLabel2 && textLabel2Props && (
                <TextLabel {...textLabel2Props} />
              )}
            </MenuItem>
          )}
          {menuItem2Props !== null && (
            <MenuItem {...menuItem2Props}>
              {icon2 && icon2Props && <Icon {...icon2Props} />}
              {textLabel3 && textLabel3Props && (
                <TextLabel {...textLabel3Props} />
              )}
              {textLabel4 && textLabel4Props && (
                <TextLabel {...textLabel4Props} />
              )}
            </MenuItem>
          )}
          {hrProps !== null && <Hr {...hrProps} />}
          {menuItemCheckboxProps !== null && (
            <MenuItemCheckbox {...menuItemCheckboxProps}>
              {icon3 && icon3Props && <Icon {...icon3Props} />}
              {textLabel5 && textLabel5Props && (
                <TextLabel {...textLabel5Props} />
              )}
            </MenuItemCheckbox>
          )}
          {menuItemRadioProps !== null && (
            <MenuItemRadio {...menuItemRadioProps}>
              {icon4 && icon4Props && <Icon {...icon4Props} />}
              {textLabel6 && textLabel6Props && (
                <TextLabel {...textLabel6Props} />
              )}
            </MenuItemRadio>
          )}
        </>
      )}
    </Frame>
  )
}

//
// Default property values
//
const sdn: MenuProps = {
  role: "menu",
  "aria-hidden": "false",
  className: "sdn-menu",
  menuItem: {
    role: "menuitem",
    "aria-hidden": "false",
    className: "sdn-menu-item sdn-menu-item--rrtt",
  },
  icon: {
    icon: "seldon-component",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--3qou",
  },
  textLabel: {
    className: "sdn-text-label sdn-text-label--xohb",
  },
  textLabel2: {
    className: "sdn-text-label sdn-text-label--fdei",
  },
  menuItem2: {
    role: "menuitem",
    "aria-hidden": "false",
    className: "sdn-menu-item sdn-menu-item--rrtt",
  },
  icon2: {
    icon: "seldon-component",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--3qou",
  },
  textLabel3: {
    className: "sdn-text-label sdn-text-label--xohb",
  },
  textLabel4: {
    className: "sdn-text-label sdn-text-label--fdei",
  },
  hr: {
    "aria-hidden": "false",
    className: "sdn-hr sdn-hr--lrmt",
  },
  menuItemCheckbox: {
    role: "menuitemcheckbox",
    "aria-hidden": "false",
    className: "sdn-menu-item sdn-menu-item--rrtt",
  },
  icon3: {
    icon: "material-check",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--3qou",
  },
  textLabel5: {
    className: "sdn-text-label sdn-text-label--xohb",
  },
  menuItemRadio: {
    role: "menuitemradio",
    "aria-hidden": "false",
    className: "sdn-menu-item sdn-menu-item--rrtt",
  },
  icon4: {
    icon: "material-radioButtonChecked",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--3qou",
  },
  textLabel6: {
    className: "sdn-text-label sdn-text-label--xohb",
  },
}
