// packages/editor/apps/vue/app/toaster/Toast.vue
<script setup lang="ts">
// BESPOKE-VIEW: hand-authored transitional View with inline token styling.
// Replace with a generated workspace component once one covers the toast card.
// Vue port of the React `Toast.bespoke`.
import { motion } from "motion-v"

import type { CSSProperties } from "vue"

defineProps<{ message: string }>()

/** How far a toast rises as it arrives, in animation pixels rather than layout. */
const RISE_DISTANCE = 10

const toastVariants = {
  initial: { opacity: 0, y: RISE_DISTANCE },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: RISE_DISTANCE },
}

const styles: Record<string, CSSProperties> = {
  toast: {
    padding: "var(--sdn-paddings-cozy)",
    backgroundColor: "var(--sdn-swatch-white)",
    borderRadius: "var(--sdn-corners-compact)",
    boxShadow:
      "0 var(--sdn-sizes-xsmall) var(--sdn-sizes-small) color-mix(in srgb, var(--sdn-swatch-black) 15%, transparent)",
    outline: "var(--sdn-border-width-small) solid var(--sdn-swatch-black)",
    color: "var(--sdn-swatch-black)",
  },
  message: { fontSize: "var(--sdn-font-size-small)" },
}
</script>

<template>
  <motion.div
    layout
    :variants="toastVariants"
    initial="initial"
    animate="animate"
    exit="exit"
    :style="styles.toast"
    role="status"
  >
    <p :style="styles.message">{{ message }}</p>
  </motion.div>
</template>

// packages/editor/seldon/custom-components/feedback/Toast.tsx
// BESPOKE-VIEW: hand-authored transitional View with inline token styling.
// Replace with a generated workspace component once one covers the toast card.
import { motion } from "framer-motion"

interface ToastProps {
  message: string
}

const toastVariants = {
  initial: { opacity: 0, y: 10 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: 10 },
}

/** Animated toast card. */
export function Toast({ message }: ToastProps) {
  return (
    <motion.div
      layout
      variants={toastVariants}
      initial="initial"
      animate="animate"
      exit="exit"
      style={{
        padding: "1rem 1.5rem",
        backgroundColor: "var(--sdn-swatch-white)",
        borderRadius: "0.75rem",
        boxShadow:
          "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
        outline: "1px solid var(--sdn-swatch-black)",
        color: "var(--sdn-swatch-black)",
      }}
    >
      <p style={{ fontSize: "var(--sdn-font-size-small)" }}>{message}</p>
    </motion.div>
  )
}
