// packages/editor/apps/vue/seldon/modules/PanelHari.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/*****
 * Panel: PanelHari
 * Level: Module
 * Intent: Schema for modal-style dialog panels with overlay behavior, used for alerts, confirmations, or embedded interactive content.
 * Tags: panel, dialog, modal, ui, overlay, popup, interaction, alert
 * Type: Inline
 *
 * @example
 * ```vue
 * <PanelHari
 *   role="dialog"
 *   aria-hidden="false"
 * />
 * ```
 *****/
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"
import { combineClassNames, mergeSlot } from "../utils/class-names"
import Frame from "../frames/Frame.vue"
import Bar from "../parts/Bar.vue"
import ButtonIconic from "../elements/ButtonIconic.vue"
import ButtonMenu from "../elements/ButtonMenu.vue"
import ButtonToggle from "../elements/ButtonToggle.vue"
import Chip from "../elements/Chip.vue"
import Icon from "../primitives/Icon.vue"
import Textarea from "../primitives/Textarea.vue"
import TextLabel from "../primitives/TextLabel.vue"
import TextTitle from "../primitives/TextTitle.vue"

const props = defineProps<{
  className?: string
  bar?: Record<string, unknown> | null
  textTitle?: Record<string, unknown> | null
  frame?: Record<string, unknown> | null
  buttonToggle?: Record<string, unknown> | null
  icon?: Record<string, unknown> | null
  buttonToggle2?: Record<string, unknown> | null
  icon2?: Record<string, unknown> | null
  buttonToggle3?: Record<string, unknown> | null
  icon3?: Record<string, unknown> | null
  buttonIconic?: Record<string, unknown> | null
  icon4?: Record<string, unknown> | null
  buttonIconic2?: Record<string, unknown> | null
  icon5?: Record<string, unknown> | null
  frame2?: Record<string, unknown> | null
  frame3?: Record<string, unknown> | null
  textarea?: Record<string, unknown> | null
  frame4?: Record<string, unknown> | null
  frame5?: Record<string, unknown> | null
  buttonMenu?: Record<string, unknown> | null
  textLabel?: Record<string, unknown> | null
  icon6?: Record<string, unknown> | null
  buttonMenu2?: Record<string, unknown> | null
  textLabel2?: Record<string, unknown> | null
  icon7?: Record<string, unknown> | null
  chip?: Record<string, unknown> | null
  textLabel3?: Record<string, unknown> | null
  buttonIconic3?: Record<string, unknown> | null
  icon8?: Record<string, unknown> | null
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "role": "dialog",
  "aria-hidden": "false",
  "className": "sdn-panel-hari sdn-panel",
  "bar": {
    "aria-hidden": "false",
    "className": "sdn-bar sdn-bar--9xs7"
  },
  "textTitle": {
    "className": "sdn-text-title sdn-text-title--ulid"
  },
  "frame": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--i5kj"
  },
  "buttonToggle": {
    "className": "sdn-button-toggle sdn-button-iconic--pgsr",
    "data-seldon-ref": "hariOutcome"
  },
  "icon": {
    "icon": "material-outputCircle",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--vsau"
  },
  "buttonToggle2": {
    "className": "sdn-button-toggle sdn-button-iconic--pgsr",
    "data-seldon-ref": "hariTools"
  },
  "icon2": {
    "icon": "material-buildCircle",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--vsau"
  },
  "buttonToggle3": {
    "className": "sdn-button-toggle sdn-button-iconic--pgsr",
    "data-seldon-ref": "hariClamp"
  },
  "icon3": {
    "icon": "material-neurology",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--vsau"
  },
  "buttonIconic": {
    "className": "sdn-button-iconic sdn-button-iconic--pgsr"
  },
  "icon4": {
    "icon": "seldon-reset",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--rezm"
  },
  "buttonIconic2": {
    "className": "sdn-button-iconic sdn-button-iconic--pgsr",
    "data-seldon-ref": "hariClose"
  },
  "icon5": {
    "icon": "material-close",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--rezm"
  },
  "frame2": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--vorn",
    "data-seldon-ref": "turns"
  },
  "frame3": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--jhsq"
  },
  "textarea": {
    "className": "sdn-textarea sdn-textarea--2upw",
    "data-seldon-ref": "hariInput"
  },
  "frame4": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--meos"
  },
  "frame5": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--a5w4"
  },
  "buttonMenu": {
    "className": "sdn-button-menu sdn-button-menu--ipe0",
    "data-seldon-ref": "hariModel"
  },
  "textLabel": {
    "className": "sdn-text-label sdn-text-label--sa6t"
  },
  "icon6": {
    "icon": "material-chevronDown",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--y2ct"
  },
  "buttonMenu2": {
    "className": "sdn-button-menu sdn-button-menu--ipe0",
    "data-seldon-ref": "hariThinking"
  },
  "textLabel2": {
    "className": "sdn-text-label sdn-text-label--sa6t"
  },
  "icon7": {
    "icon": "material-chevronDown",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--y2ct"
  },
  "chip": {
    "className": "sdn-chip sdn-chip--lo6k",
    "data-seldon-ref": "hariSelection"
  },
  "textLabel3": {
    "className": "sdn-text-label sdn-text-label--lug5"
  },
  "buttonIconic3": {
    "className": "sdn-button-iconic sdn-button-iconic--wh0i",
    "data-seldon-ref": "hariSend"
  },
  "icon8": {
    "icon": "material-arrowUpward",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--umgs"
  }
}

const rootClassName = computed(() => combineClassNames("sdn-panel-hari", props.className))
const rootAttrs = { "role": sdn["role"], "aria-hidden": sdn["aria-hidden"] }
const barProps = computed(() => mergeSlot(sdn.bar, props.bar))
const textTitleProps = computed(() => mergeSlot(sdn.textTitle, props.textTitle))
const frameProps = computed(() => mergeSlot(sdn.frame, props.frame))
const buttonToggleProps = computed(() => mergeSlot(sdn.buttonToggle, props.buttonToggle))
const iconProps = computed(() => mergeSlot(sdn.icon, props.icon))
const buttonToggle2Props = computed(() => mergeSlot(sdn.buttonToggle2, props.buttonToggle2))
const icon2Props = computed(() => mergeSlot(sdn.icon2, props.icon2))
const buttonToggle3Props = computed(() => mergeSlot(sdn.buttonToggle3, props.buttonToggle3))
const icon3Props = computed(() => mergeSlot(sdn.icon3, props.icon3))
const buttonIconicProps = computed(() => mergeSlot(sdn.buttonIconic, props.buttonIconic))
const icon4Props = computed(() => mergeSlot(sdn.icon4, props.icon4))
const buttonIconic2Props = computed(() => mergeSlot(sdn.buttonIconic2, props.buttonIconic2))
const icon5Props = computed(() => mergeSlot(sdn.icon5, props.icon5))
const frame2Props = computed(() => mergeSlot(sdn.frame2, props.frame2))
const frame3Props = computed(() => mergeSlot(sdn.frame3, props.frame3))
const textareaProps = computed(() => mergeSlot(sdn.textarea, props.textarea))
const frame4Props = computed(() => mergeSlot(sdn.frame4, props.frame4))
const frame5Props = computed(() => mergeSlot(sdn.frame5, props.frame5))
const buttonMenuProps = computed(() => mergeSlot(sdn.buttonMenu, props.buttonMenu))
const textLabelProps = computed(() => mergeSlot(sdn.textLabel, props.textLabel))
const icon6Props = computed(() => mergeSlot(sdn.icon6, props.icon6))
const buttonMenu2Props = computed(() => mergeSlot(sdn.buttonMenu2, props.buttonMenu2))
const textLabel2Props = computed(() => mergeSlot(sdn.textLabel2, props.textLabel2))
const icon7Props = computed(() => mergeSlot(sdn.icon7, props.icon7))
const chipProps = computed(() => mergeSlot(sdn.chip, props.chip))
const textLabel3Props = computed(() => mergeSlot(sdn.textLabel3, props.textLabel3))
const buttonIconic3Props = computed(() => mergeSlot(sdn.buttonIconic3, props.buttonIconic3))
const icon8Props = computed(() => mergeSlot(sdn.icon8, props.icon8))
</script>

<template>
    <div :class="rootClassName" v-bind="rootAttrs">
      <slot>
        <Bar v-if="barProps !== null" v-bind="barProps">
          <TextTitle v-if="textTitle && textTitleProps" v-bind="textTitleProps" />
          <Frame v-bind="frameProps" v-if="frame">
            <ButtonToggle v-if="buttonToggle && buttonToggleProps" v-bind="buttonToggleProps" :icon="iconProps" />
            <ButtonToggle v-if="buttonToggle2 && buttonToggle2Props" v-bind="buttonToggle2Props" :icon="icon2Props" />
            <ButtonToggle v-if="buttonToggle3 && buttonToggle3Props" v-bind="buttonToggle3Props" :icon="icon3Props" />
          </Frame>
          <ButtonIconic v-if="buttonIconicProps !== null" v-bind="buttonIconicProps" :icon="icon4Props" />
          <ButtonIconic v-if="buttonIconic2 && buttonIconic2Props" v-bind="buttonIconic2Props" :icon="icon5Props" />
        </Bar>
        <Frame v-bind="frame2Props">
          <slot name="turns" />
        </Frame>
        <Frame v-bind="frame3Props" v-if="frame3">
          <Textarea v-if="textarea && textareaProps" v-bind="textareaProps" />
        </Frame>
        <Frame v-bind="frame4Props" v-if="frame4">
          <Frame v-bind="frame5Props" v-if="frame5">
            <ButtonMenu v-if="buttonMenu && buttonMenuProps" v-bind="buttonMenuProps">
              <TextLabel v-if="textLabel && textLabelProps" v-bind="textLabelProps" />
              <Icon v-if="icon6Props !== null" v-bind="icon6Props" />
            </ButtonMenu>
            <ButtonMenu v-if="buttonMenu2 && buttonMenu2Props" v-bind="buttonMenu2Props">
              <TextLabel v-if="textLabel2 && textLabel2Props" v-bind="textLabel2Props" />
              <Icon v-if="icon7Props !== null" v-bind="icon7Props" />
            </ButtonMenu>
            <Chip v-if="chip && chipProps" v-bind="chipProps">
              <TextLabel v-if="textLabel3 && textLabel3Props" v-bind="textLabel3Props" />
            </Chip>
            <ButtonIconic v-if="buttonIconic3 && buttonIconic3Props" v-bind="buttonIconic3Props" :icon="icon8Props" />
          </Frame>
        </Frame>
      </slot>
    </div>
</template>

// packages/editor-react/seldon/modules/PanelHari.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/
import { HTMLAttributes } from "react"
import { ButtonIconic, ButtonIconicProps } from "../elements/ButtonIconic"
import { ButtonMenu, ButtonMenuProps } from "../elements/ButtonMenu"
import { ButtonToggle, ButtonToggleProps } from "../elements/ButtonToggle"
import { Chip, ChipProps } from "../elements/Chip"
import { Frame, FrameProps } from "../frames/Frame"
import { HTMLDiv } from "../native-react/HTML.Div"
import { Bar, BarProps } from "../parts/Bar"
import { Icon, IconProps } from "../primitives/Icon"
import { TextLabel, TextLabelProps } from "../primitives/TextLabel"
import { TextTitle, TextTitleProps } from "../primitives/TextTitle"
import { Textarea, TextareaProps } from "../primitives/Textarea"
import { applyRef } from "../utils/apply-ref"
import { combineClassNames } from "../utils/class-name"

export interface PanelHariProps extends HTMLAttributes<HTMLElement> {
  className?: string
  "data-seldon-ref"?: string
  seldonRefs?: Record<string, Record<string, unknown>>
  bar?: BarProps | null
  textTitle?: TextTitleProps | null
  frame?: FrameProps | null
  buttonToggle?: ButtonToggleProps | null
  icon?: IconProps | null
  buttonToggle2?: ButtonToggleProps | null
  icon2?: IconProps | null
  buttonToggle3?: ButtonToggleProps | null
  icon3?: IconProps | null
  buttonIconic?: ButtonIconicProps | null
  icon4?: IconProps | null
  buttonIconic2?: ButtonIconicProps | null
  icon5?: IconProps | null
  frame2?: FrameProps | null
  frame3?: FrameProps | null
  textarea?: TextareaProps | null
  frame4?: FrameProps | null
  frame5?: FrameProps | null
  buttonMenu?: ButtonMenuProps | null
  textLabel?: TextLabelProps | null
  icon6?: IconProps | null
  buttonMenu2?: ButtonMenuProps | null
  textLabel2?: TextLabelProps | null
  icon7?: IconProps | null
  chip?: ChipProps | null
  textLabel3?: TextLabelProps | null
  buttonIconic3?: ButtonIconicProps | null
  icon8?: IconProps | null
}

/*****
 * Panel: PanelHari
 * Level: Module
 * Intent: Schema for modal-style dialog panels with overlay behavior, used for alerts, confirmations, or embedded interactive content.
 * Tags: panel, dialog, modal, ui, overlay, popup, interaction, alert
 * Type: Inline
 *
 * @example
 * ```tsx
 * <PanelHari
 *   role="dialog"
 *   aria-hidden="false"
 * />
 * ```
 *****/
export function PanelHari({
  className = "",
  bar = sdn.bar,
  textTitle,
  frame = sdn.frame,
  buttonToggle,
  icon = sdn.icon,
  buttonToggle2,
  icon2 = sdn.icon2,
  buttonToggle3,
  icon3 = sdn.icon3,
  buttonIconic = sdn.buttonIconic,
  icon4 = sdn.icon4,
  buttonIconic2,
  icon5 = sdn.icon5,
  frame2 = sdn.frame2,
  frame3 = sdn.frame3,
  textarea,
  frame4 = sdn.frame4,
  frame5 = sdn.frame5,
  buttonMenu,
  textLabel,
  icon6 = sdn.icon6,
  buttonMenu2,
  textLabel2,
  icon7 = sdn.icon7,
  chip,
  textLabel3,
  buttonIconic3,
  icon8 = sdn.icon8,
  children,
  seldonRefs,
  ...props
}: PanelHariProps) {
  const panelHariClassName = combineClassNames("sdn-panel-hari", className)
  const barProps = applyRef(
    seldonRefs,
    bar === null
      ? null
      : {
          ...sdn.bar,
          ...bar,
          className: combineClassNames(sdn.bar?.className, bar?.className),
        },
  )
  const textTitleProps = applyRef(
    seldonRefs,
    textTitle === null
      ? null
      : {
          ...sdn.textTitle,
          ...textTitle,
          className: combineClassNames(
            sdn.textTitle?.className,
            textTitle?.className,
          ),
        },
  )
  const frameProps = applyRef(
    seldonRefs,
    frame === null
      ? null
      : {
          ...sdn.frame,
          ...frame,
          className: combineClassNames(sdn.frame?.className, frame?.className),
        },
  )
  const buttonToggleProps = applyRef(
    seldonRefs,
    buttonToggle === null
      ? null
      : {
          ...sdn.buttonToggle,
          ...buttonToggle,
          className: combineClassNames(
            sdn.buttonToggle?.className,
            buttonToggle?.className,
          ),
        },
  )
  const iconProps = applyRef(
    seldonRefs,
    icon === null
      ? null
      : {
          ...sdn.icon,
          ...icon,
          className: combineClassNames(sdn.icon?.className, icon?.className),
        },
  )
  const buttonToggle2Props = applyRef(
    seldonRefs,
    buttonToggle2 === null
      ? null
      : {
          ...sdn.buttonToggle2,
          ...buttonToggle2,
          className: combineClassNames(
            sdn.buttonToggle2?.className,
            buttonToggle2?.className,
          ),
        },
  )
  const icon2Props = applyRef(
    seldonRefs,
    icon2 === null
      ? null
      : {
          ...sdn.icon2,
          ...icon2,
          className: combineClassNames(sdn.icon2?.className, icon2?.className),
        },
  )
  const buttonToggle3Props = applyRef(
    seldonRefs,
    buttonToggle3 === null
      ? null
      : {
          ...sdn.buttonToggle3,
          ...buttonToggle3,
          className: combineClassNames(
            sdn.buttonToggle3?.className,
            buttonToggle3?.className,
          ),
        },
  )
  const icon3Props = applyRef(
    seldonRefs,
    icon3 === null
      ? null
      : {
          ...sdn.icon3,
          ...icon3,
          className: combineClassNames(sdn.icon3?.className, icon3?.className),
        },
  )
  const buttonIconicProps = applyRef(
    seldonRefs,
    buttonIconic === null
      ? null
      : {
          ...sdn.buttonIconic,
          ...buttonIconic,
          className: combineClassNames(
            sdn.buttonIconic?.className,
            buttonIconic?.className,
          ),
        },
  )
  const icon4Props = applyRef(
    seldonRefs,
    icon4 === null
      ? null
      : {
          ...sdn.icon4,
          ...icon4,
          className: combineClassNames(sdn.icon4?.className, icon4?.className),
        },
  )
  const buttonIconic2Props = applyRef(
    seldonRefs,
    buttonIconic2 === null
      ? null
      : {
          ...sdn.buttonIconic2,
          ...buttonIconic2,
          className: combineClassNames(
            sdn.buttonIconic2?.className,
            buttonIconic2?.className,
          ),
        },
  )
  const icon5Props = applyRef(
    seldonRefs,
    icon5 === null
      ? null
      : {
          ...sdn.icon5,
          ...icon5,
          className: combineClassNames(sdn.icon5?.className, icon5?.className),
        },
  )
  const frame2Props = applyRef(
    seldonRefs,
    frame2 === null
      ? null
      : {
          ...sdn.frame2,
          ...frame2,
          className: combineClassNames(
            sdn.frame2?.className,
            frame2?.className,
          ),
        },
  )
  const frame3Props = applyRef(
    seldonRefs,
    frame3 === null
      ? null
      : {
          ...sdn.frame3,
          ...frame3,
          className: combineClassNames(
            sdn.frame3?.className,
            frame3?.className,
          ),
        },
  )
  const textareaProps = applyRef(
    seldonRefs,
    textarea === null
      ? null
      : {
          ...sdn.textarea,
          ...textarea,
          className: combineClassNames(
            sdn.textarea?.className,
            textarea?.className,
          ),
        },
  )
  const frame4Props = applyRef(
    seldonRefs,
    frame4 === null
      ? null
      : {
          ...sdn.frame4,
          ...frame4,
          className: combineClassNames(
            sdn.frame4?.className,
            frame4?.className,
          ),
        },
  )
  const frame5Props = applyRef(
    seldonRefs,
    frame5 === null
      ? null
      : {
          ...sdn.frame5,
          ...frame5,
          className: combineClassNames(
            sdn.frame5?.className,
            frame5?.className,
          ),
        },
  )
  const buttonMenuProps = applyRef(
    seldonRefs,
    buttonMenu === null
      ? null
      : {
          ...sdn.buttonMenu,
          ...buttonMenu,
          className: combineClassNames(
            sdn.buttonMenu?.className,
            buttonMenu?.className,
          ),
        },
  )
  const textLabelProps = applyRef(
    seldonRefs,
    textLabel === null
      ? null
      : {
          ...sdn.textLabel,
          ...textLabel,
          className: combineClassNames(
            sdn.textLabel?.className,
            textLabel?.className,
          ),
        },
  )
  const icon6Props = applyRef(
    seldonRefs,
    icon6 === null
      ? null
      : {
          ...sdn.icon6,
          ...icon6,
          className: combineClassNames(sdn.icon6?.className, icon6?.className),
        },
  )
  const buttonMenu2Props = applyRef(
    seldonRefs,
    buttonMenu2 === null
      ? null
      : {
          ...sdn.buttonMenu2,
          ...buttonMenu2,
          className: combineClassNames(
            sdn.buttonMenu2?.className,
            buttonMenu2?.className,
          ),
        },
  )
  const textLabel2Props = applyRef(
    seldonRefs,
    textLabel2 === null
      ? null
      : {
          ...sdn.textLabel2,
          ...textLabel2,
          className: combineClassNames(
            sdn.textLabel2?.className,
            textLabel2?.className,
          ),
        },
  )
  const icon7Props = applyRef(
    seldonRefs,
    icon7 === null
      ? null
      : {
          ...sdn.icon7,
          ...icon7,
          className: combineClassNames(sdn.icon7?.className, icon7?.className),
        },
  )
  const chipProps = applyRef(
    seldonRefs,
    chip === null
      ? null
      : {
          ...sdn.chip,
          ...chip,
          className: combineClassNames(sdn.chip?.className, chip?.className),
        },
  )
  const textLabel3Props = applyRef(
    seldonRefs,
    textLabel3 === null
      ? null
      : {
          ...sdn.textLabel3,
          ...textLabel3,
          className: combineClassNames(
            sdn.textLabel3?.className,
            textLabel3?.className,
          ),
        },
  )
  const buttonIconic3Props = applyRef(
    seldonRefs,
    buttonIconic3 === null
      ? null
      : {
          ...sdn.buttonIconic3,
          ...buttonIconic3,
          className: combineClassNames(
            sdn.buttonIconic3?.className,
            buttonIconic3?.className,
          ),
        },
  )
  const icon8Props = applyRef(
    seldonRefs,
    icon8 === null
      ? null
      : {
          ...sdn.icon8,
          ...icon8,
          className: combineClassNames(sdn.icon8?.className, icon8?.className),
        },
  )

  return (
    <HTMLDiv
      className={panelHariClassName}
      role={sdn["role"]}
      aria-hidden={sdn["aria-hidden"]}
      {...props}
    >
      {children !== undefined ? (
        children
      ) : (
        <>
          {barProps !== null && (
            <Bar {...barProps}>
              {textTitle && textTitleProps && <TextTitle {...textTitleProps} />}
              <Frame {...frameProps}>
                {buttonToggle && buttonToggleProps && (
                  <ButtonToggle {...buttonToggleProps} icon={iconProps} />
                )}
                {buttonToggle2 && buttonToggle2Props && (
                  <ButtonToggle {...buttonToggle2Props} icon={icon2Props} />
                )}
                {buttonToggle3 && buttonToggle3Props && (
                  <ButtonToggle {...buttonToggle3Props} icon={icon3Props} />
                )}
              </Frame>
              {buttonIconic && buttonIconicProps && (
                <ButtonIconic {...buttonIconicProps} icon={icon4Props} />
              )}
              {buttonIconic2 && buttonIconic2Props && (
                <ButtonIconic {...buttonIconic2Props} icon={icon5Props} />
              )}
            </Bar>
          )}
          <Frame {...frame2Props}></Frame>
          <Frame {...frame3Props}>
            {textarea && textareaProps && <Textarea {...textareaProps} />}
          </Frame>
          <Frame {...frame4Props}>
            <Frame {...frame5Props}>
              {buttonMenu && buttonMenuProps && (
                <ButtonMenu {...buttonMenuProps}>
                  {textLabel && textLabelProps && (
                    <TextLabel {...textLabelProps} />
                  )}
                  {icon6 && icon6Props && <Icon {...icon6Props} />}
                </ButtonMenu>
              )}
              {buttonMenu2 && buttonMenu2Props && (
                <ButtonMenu {...buttonMenu2Props}>
                  {textLabel2 && textLabel2Props && (
                    <TextLabel {...textLabel2Props} />
                  )}
                  {icon7 && icon7Props && <Icon {...icon7Props} />}
                </ButtonMenu>
              )}
              {chip && chipProps && (
                <Chip {...chipProps}>
                  {textLabel3 && textLabel3Props && (
                    <TextLabel {...textLabel3Props} />
                  )}
                </Chip>
              )}
              {buttonIconic3 && buttonIconic3Props && (
                <ButtonIconic {...buttonIconic3Props} icon={icon8Props} />
              )}
            </Frame>
          </Frame>
        </>
      )}
    </HTMLDiv>
  )
}

//
// Default property values
//
const sdn: PanelHariProps = {
  role: "dialog",
  "aria-hidden": "false",
  className: "sdn-panel-hari sdn-panel",
  bar: {
    "aria-hidden": "false",
    className: "sdn-bar sdn-bar--9xs7",
  },
  textTitle: {
    className: "sdn-text-title sdn-text-title--ulid",
  },
  frame: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--i5kj",
  },
  buttonToggle: {
    className: "sdn-button-toggle sdn-button-iconic--pgsr",
    "data-seldon-ref": "hariOutcome",
  },
  icon: {
    icon: "material-outputCircle",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--vsau",
  },
  buttonToggle2: {
    className: "sdn-button-toggle sdn-button-iconic--pgsr",
    "data-seldon-ref": "hariTools",
  },
  icon2: {
    icon: "material-buildCircle",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--vsau",
  },
  buttonToggle3: {
    className: "sdn-button-toggle sdn-button-iconic--pgsr",
    "data-seldon-ref": "hariClamp",
  },
  icon3: {
    icon: "material-neurology",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--vsau",
  },
  buttonIconic: {
    className: "sdn-button-iconic sdn-button-iconic--pgsr",
  },
  icon4: {
    icon: "seldon-reset",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--rezm",
  },
  buttonIconic2: {
    className: "sdn-button-iconic sdn-button-iconic--pgsr",
    "data-seldon-ref": "hariClose",
  },
  icon5: {
    icon: "material-close",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--rezm",
  },
  frame2: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--vorn",
    "data-seldon-ref": "turns",
  },
  frame3: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--jhsq",
  },
  textarea: {
    className: "sdn-textarea sdn-textarea--2upw",
    "data-seldon-ref": "hariInput",
  },
  frame4: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--meos",
  },
  frame5: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--a5w4",
  },
  buttonMenu: {
    className: "sdn-button-menu sdn-button-menu--ipe0",
    "data-seldon-ref": "hariModel",
  },
  textLabel: {
    className: "sdn-text-label sdn-text-label--sa6t",
  },
  icon6: {
    icon: "material-chevronDown",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--y2ct",
  },
  buttonMenu2: {
    className: "sdn-button-menu sdn-button-menu--ipe0",
    "data-seldon-ref": "hariThinking",
  },
  textLabel2: {
    className: "sdn-text-label sdn-text-label--sa6t",
  },
  icon7: {
    icon: "material-chevronDown",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--y2ct",
  },
  chip: {
    className: "sdn-chip sdn-chip--lo6k",
    "data-seldon-ref": "hariSelection",
  },
  textLabel3: {
    className: "sdn-text-label sdn-text-label--lug5",
  },
  buttonIconic3: {
    className: "sdn-button-iconic sdn-button-iconic--wh0i",
    "data-seldon-ref": "hariSend",
  },
  icon8: {
    icon: "material-arrowUpward",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--umgs",
  },
}
