// packages/editor-react/app/sidebars/properties/Property.tsx
import { useRowActionsMenu } from "@app/menus/hooks/use-row-actions-menu"
import { mergeStateProps } from "@app/views/state-props"
import { ChangeEvent, memo, useCallback } from "react"
import { IndentationLevel } from "../hooks/use-indentation"
import { RowPropertyProps, useRowProperty } from "./hooks/use-row-property"
import { ComboboxFieldProps } from "@seldon/components/elements/ComboboxField"
import { ItemProperty } from "@seldon/components/elements/ItemProperty"
import { ItemPropertyToggle } from "@seldon/components/elements/ItemPropertyToggle"
import { FramerExpandable } from "@app/sidebars/FramerExpandable.bespoke"
import { LayerDragRow } from "./LayerDragRow"
import { PropertyOptionsListbox } from "./PropertyOptionsListbox"
import { arePropertyRowPropsEqual } from "./helpers/property-row-memo"

/**
 * View-model for a property row. Value rows bind the generated `ItemProperty`.
 * Boolean rows (`wrapChildren`, `clip`) bind the generated `ItemPropertyToggle`,
 * whose toggle owns the value. Both Views share the same row slots (name,
 * disclosure, actions) through one `seldonRefs` channel.
 */
function PropertyInner(props: RowPropertyProps) {
  const view = useRowProperty(props)
  const optionsMenu = useRowActionsMenu(view.resetActions, {
    focusTargetRef: view.focusTargetRef,
  })

  const { listItemProps, control } = view
  const switchControl = control.kind === "switch" ? control : null

  // The row's status maps to a generated leaf state (activated, invalid, or
  // disabled). The state props tint the row's content leaves (name, value,
  // value icon), replacing inline status colors, the same way the board row
  // drives activated.
  const stateRef = view.stateRef

  // Indeterminate can't be expressed as a prop, so it is set through the toggle
  // input's ref. It reflects the unset ("mixed") state.
  const toggleSwitchRef = useCallback(
    (node: HTMLInputElement | null) => {
      if (node) {
        node.indeterminate = switchControl?.mixed ?? false
      }
    },
    [switchControl?.mixed],
  )

  const onToggleSwitchChange = useCallback(
    (event: ChangeEvent<HTMLInputElement>) => {
      switchControl?.onToggle(event.currentTarget.checked)
    },
    [switchControl],
  )

  const toggleAriaChecked = switchControl?.mixed
    ? "mixed"
    : (switchControl?.checked ?? false)

  // Sub-property rows for a compound or shorthand parent. Wrapped in
  // `IndentationLevel` so each nesting depth adds one indent step and shifts the
  // whole row, matching the objects-sidebar tree.
  const childRows = view.hasChildren ? (
    <FramerExpandable isExpanded={view.isExpanded}>
      <IndentationLevel>
        {view.childItems.map((childProps) => (
          <Property key={childProps.property.key} {...childProps} />
        ))}
      </IndentationLevel>
    </FramerExpandable>
  ) : null

  // Boolean rows render the dedicated `ItemPropertyToggle` View. The toggle
  // slot carries the value through `toggleValue`; the shared row slots bind the
  // same hook props as `ItemProperty`. The `toggleIcon` slot shows the row's
  // property glyph, the same `icon2` source the value cell uses on other rows.
  if (switchControl) {
    // The toggle shows its value through its own on/off color, so the override
    // "activated" tint must not also land on it, or an overridden "off" toggle
    // reads as active. Drop activated for the control while keeping invalid and
    // disabled; the label and icon still carry the override tint.
    const toggleStateRef =
      props.property.status === "override" ? undefined : stateRef
    const toggleRefs: Record<string, Record<string, unknown>> = {
      propertyToggle: { ...listItemProps.buttonIconic },
      propertyToggleIcon: { ...listItemProps.icon },
      propertyLabel: mergeStateProps(view.nameLabelProps, stateRef),
      propertyActions: { ...optionsMenu.buttonIconic },
      toggleValue: mergeStateProps(
        {
          checked: switchControl.checked,
          "aria-checked": toggleAriaChecked,
          ref: toggleSwitchRef,
          onChange: onToggleSwitchChange,
        },
        toggleStateRef,
      ),
    }
    if (listItemProps.icon2) {
      toggleRefs.toggleIcon = mergeStateProps(listItemProps.icon2, stateRef)
    }

    return (
      <>
        <ItemPropertyToggle
          buttonIconic={{}}
          formControlCombobox={{}}
          input={{}}
          icon2={{}}
          toggleSwitch={{}}
          buttonIconic2={{}}
          seldonRefs={toggleRefs}
          onClick={view.onRowClick}
          onDoubleClick={view.onRowDoubleClick}
        />
        {optionsMenu.menu}
        {childRows}
      </>
    )
  }

  // Drive each slot through its stable workspace ref. The value `input` slot is
  // both the read-only display and, in edit mode, the live combobox/text control
  // (see `buildPropertyValueInput`), mirroring the objects-sidebar name slot. The
  // trailing actions icon keeps the generated `seldon-more` default, hidden by
  // the actions button placeholder.
  const seldonRefs: Record<string, Record<string, unknown>> = {
    propertyToggle: { ...listItemProps.buttonIconic },
    propertyToggleIcon: { ...listItemProps.icon },
    propertyLabel: mergeStateProps(view.nameLabelProps, stateRef),
    // Look-parent group rows own no value. The generated value input still
    // renders (kept for row-height alignment), so clear its "Value" placeholder
    // so the group row reads blank instead of showing placeholder text.
    valueLabel: mergeStateProps(
      view.valueLabelProps,
      props.property.isLookParent ? { placeholder: "" } : undefined,
      stateRef,
    ),
    valueOptionsMenu: { ...listItemProps.buttonIconic2 },
    propertyActions: { ...optionsMenu.buttonIconic },
  }
  if (listItemProps.icon2) {
    seldonRefs.valueIcon = mergeStateProps(listItemProps.icon2, stateRef)
  }

  // Anchor the floating option list to the value field and enter edit on a single
  // click of the field. `ComboboxField` forwards the ref (React 19 ref-as-prop)
  // to its `Frame` div, which the position hook measures, and forwards `onClick`
  // to the same div. The display input is inert, so the click lands on the field.
  // Hover and selected styling come from the generated `ComboboxField` CSS.
  // Group rows (look-parent: Modulation, Color Harmony, Font Family, swatch
  // groups, etc.) own no value. Keep the frame in place so row layout stays
  // aligned, but disable it: `aria-disabled` marks the state, and
  // `pointerEvents: none` stops both the hover styling and click-into-edit, so
  // the row body's own click still toggles the disclosure.
  const comboboxField = props.property.isLookParent
    ? ({
        "aria-disabled": true,
        style: { pointerEvents: "none" },
      } as ComboboxFieldProps)
    : ({
        ref: view.setValueFieldRef,
        onClick: view.onValueFieldClick,
      } as ComboboxFieldProps)

  // Positional enabler: suppress `icon2` with `null` when the value icon is
  // hidden; otherwise leave it on its slot default so the bound `valueIcon` ref
  // paints the glyph. Dynamic color chips (`icon-custom-color-value`) resolve
  // through the same slot via the generated `Icon`'s runtime registry.
  const valueIconSlot = listItemProps.icon2 ? undefined : null

  // Render the exported `ItemProperty` through its slots. `LayerDragRow` wraps a
  // multi-layer paint parent as a drag source and passes other rows through
  // unwrapped. `input` (the property-name slot) is conditional, so it keeps a
  // positional enabler. `icon3` (the options-menu icon) has no workspace ref
  // yet, so it stays positional; add a `valueOptionsMenuIcon` ref to move it
  // onto `seldonRefs`.
  return (
    <>
      <LayerDragRow
        layerDrag={view.layerDrag}
        label={props.property.label}
        icon={props.property.icon}
      >
        <ItemProperty
          input={{}}
          comboboxField={comboboxField}
          icon2={valueIconSlot}
          icon3={listItemProps.icon3}
          seldonRefs={seldonRefs}
          onClick={view.onRowClick}
          onDoubleClick={view.onRowDoubleClick}
        />
      </LayerDragRow>
      {optionsMenu.menu}
      <PropertyOptionsListbox control={control} onEndEdit={view.endEdit} />
      {childRows}
    </>
  )
}

export const Property = memo(PropertyInner, arePropertyRowPropsEqual)

// packages/editor/apps/vue/app/sidebars/properties/Property.vue
<script setup lang="ts">
import ComboboxOptions from "@app/menus/ComboboxOptions.vue"
import MenuController from "@app/menus/MenuController.vue"
import { useRowActionsMenu } from "@app/menus/use-row-actions-menu"
import FramerExpandable from "@app/sidebars/FramerExpandable.vue"
import { mergeStateProps } from "@app/sidebars/state-props"
import { useDispatch } from "@app/workspace/use-dispatch"
import ItemProperty from "@seldon/components/elements/ItemProperty.vue"
import ItemPropertyToggle from "@seldon/components/elements/ItemPropertyToggle.vue"
import { computed, nextTick, ref, watch } from "vue"

import { usePropertyCardScope } from "./hooks/use-property-card-scope"
import { useRowProperty } from "./hooks/use-row-property"
import { useLayerDragStore } from "./layer-drag-store"

import type { ComboboxOptionItem } from "@app/menus/types"
import type { Board, Instance, Theme, Variant, Workspace } from "@seldon/core"
import type {
  FontCollectionEditingContext,
  IconSetEditingContext,
  ThemeEditingContext,
} from "@seldon/editor/lib/properties/inspector/editing-contexts"
import type { FlatProperty } from "@seldon/editor/lib/properties/inspector/properties-data"

const props = withDefaults(
  defineProps<{
    property: FlatProperty
    workspace: Workspace
    node: Variant | Instance | Board
    theme?: Theme
    allProperties: FlatProperty[]
    themeEditingContext: ThemeEditingContext | null
    fontCollectionEditingContext: FontCollectionEditingContext | null
    iconSetEditingContext: IconSetEditingContext | null
    depth?: number
    presentation?: "sidebar" | "token"
  }>(),
  { depth: 0, presentation: "sidebar" },
)

const rowStyle = computed(() =>
  props.depth > 0 ? { paddingLeft: `${props.depth * 12}px` } : undefined,
)

const dispatch = useDispatch()
const layerDrag = useLayerDragStore()

const view = useRowProperty({
  property: computed(() => props.property),
  workspace: computed(() => props.workspace),
  node: computed(() => props.node),
  theme: computed(() => props.theme),
  allProperties: computed(() => props.allProperties),
  themeEditingContext: computed(() => props.themeEditingContext),
  fontCollectionEditingContext: computed(() => props.fontCollectionEditingContext),
  iconSetEditingContext: computed(() => props.iconSetEditingContext),
})

const control = view.control
const isLookParent = computed(() => Boolean(props.property.isLookParent))
const isSwitch = computed(() => control.kind.value === "switch")

// Token-card chrome. The top row drops its name, since the card names the token. Every
// leaf in the card drops its disclosure, so a facet sits flush at the card's left edge
// instead of behind the empty toggle the tree reserves. A row that owns a toggle keeps
// its disclosure so a compound can still expand.
const cardScope = usePropertyCardScope()
const inCard = cardScope !== null
const isToken = computed(() => props.presentation === "token")
const hideDisclosure = computed(() => inCard && !view.showDisclosure.value)

// The tree indents each nesting depth to match the objects sidebar; a card keeps its
// facets flush at the left edge instead.
const childDepth = computed(() => (inCard ? props.depth : props.depth + 1))

// Keep the expandable mounted for every compound or shorthand parent, even when
// the current value drops its facets (a Background set to None reseeds to a bare
// layer). AnimatePresence then plays the collapse from the last open facets, and
// the enter when the value adds them back, instead of snapping. `view.isExpanded`
// already reads false for None, so a mounted-but-empty parent stays collapsed.
const isCompoundParent = computed(
  () => Boolean(props.property.isCompound) || Boolean(props.property.isShorthand),
)

const actionsMenu = useRowActionsMenu(() => view.resetActions.value, {
  ariaLabel: "Property actions",
})

// ---- Shared slot props ----
const nameProps = computed(() => mergeStateProps(view.nameLabelProps.value, view.stateRef.value))

// Kept in the DOM but out of layout, so a hidden name never shifts the value.
const nameLabelSlot = computed(() =>
  isToken.value
    ? { ...nameProps.value, style: { ...(nameProps.value.style as object), display: "none" } }
    : nameProps.value,
)

// ---- ItemProperty (value rows) ----
const valueIconProps = computed(() =>
  view.listItemProps.value.icon2
    ? mergeStateProps(view.listItemProps.value.icon2, view.stateRef.value)
    : null,
)
const valueLabelProps = computed(() =>
  mergeStateProps(
    view.valueLabelProps.value,
    isLookParent.value ? { placeholder: "" } : undefined,
    view.stateRef.value,
  ),
)
// A dimmed row is read-only, so its value field drops the editable hover
// outline. A link row (Source) keeps a pointer cursor since its value still
// opens an external page on click.
const readOnlyFieldClass = computed(() => {
  if (!props.property.isDimmed) return undefined

  return props.property.linkHref ? "sdn-field-readonly sdn-field-link" : "sdn-field-readonly"
})

const comboboxFieldProps = computed(() =>
  isLookParent.value
    ? { "aria-disabled": true, style: { pointerEvents: "none" } }
    : {
        onClick: view.onValueFieldClick,
        "data-frame-ref": "true",
        className: readOnlyFieldClass.value,
      },
)

// Positional enabler: suppress `icon2` with `null` when the value icon is hidden;
// otherwise leave it on its slot default so the bound `propertyValueIcon` ref
// paints the glyph. Dynamic color chips resolve through the same slot.
const valueIconSlot = computed(() => (view.listItemProps.value.icon2 ? undefined : null))

// Drive each slot through its stable workspace ref. The row name and the row value
// are separate input slots, so they bind through `propertyLabel` and
// `propertyValueLabel`. The trailing actions icon keeps the generated `seldon-more`
// default, hidden by the actions button placeholder.
const seldonRefs = computed(() => ({
  propertyDisclosure: view.listItemProps.value.buttonIconic,
  propertyDisclosureIcon: view.listItemProps.value.icon,
  propertyLabel: nameLabelSlot.value,
  propertyValueField: comboboxFieldProps.value,
  propertyValueIcon: valueIconProps.value ?? {},
  propertyValueLabel: valueLabelProps.value,
  propertyValueMenu: view.listItemProps.value.buttonIconic2,
  propertyValueMenuIcon: view.listItemProps.value.icon3,
  propertyActions: actionsMenu.buttonIconic.value,
}))

// ---- ItemPropertyToggle (switch rows) ----
const toggleIconProps = computed(() =>
  view.listItemProps.value.icon2
    ? mergeStateProps(view.listItemProps.value.icon2, view.stateRef.value)
    : null,
)
const toggleSwitchProps = computed(() => {
  const state = control.switchState.value
  const checked = state.checked
  return mergeStateProps(
    {
      role: "switch",
      "aria-checked": state.mixed ? "mixed" : checked ? "true" : "false",
      style: { cursor: "pointer" },
      onClick: (event: MouseEvent) => {
        event.stopPropagation()
        control.onSwitchToggle(!checked)
      },
    },
    props.property.status === "override" ? undefined : view.stateRef.value,
  )
})

// A boolean row renders its own View, so its slots carry their own ref names. The
// shared row slots pair up by role: `propertyToggleLabel` against `propertyLabel`,
// `propertyToggleDisclosure` against `propertyDisclosure`.
const toggleRefs = computed(() => ({
  propertyToggleDisclosure: view.listItemProps.value.buttonIconic,
  propertyToggleDisclosureIcon: view.listItemProps.value.icon,
  propertyToggleLabel: nameProps.value,
  propertyToggleIcon: toggleIconProps.value ?? {},
  propertyToggleSwitch: toggleSwitchProps.value,
  propertyToggleActions: actionsMenu.buttonIconic.value,
}))

// ---- Combobox floating options ----
const anchorEl = ref<HTMLElement | null>(null)
const comboboxOpen = computed(
  () =>
    control.kind.value === "combobox" &&
    control.combobox.open.value &&
    control.combobox.hasFilteredOptions.value,
)
const filteredGroups = computed<ComboboxOptionItem[][]>(() => control.combobox.filteredGroups.value)
const resolveIcon = computed(() => control.resolveOptionIcon.value)

watch(
  () => control.combobox.open.value,
  (open) => {
    if (!open) return
    void nextTick(() => {
      const el = view.rowRef.value?.$el as HTMLElement | undefined
      anchorEl.value = el?.querySelector<HTMLElement>(".sdn-combobox-field") ?? el ?? null
    })
  },
)

function onSelectOption(value: string): void {
  control.combobox.handleSelect(value)
}
function onCloseOptions(): void {
  control.combobox.handleClose()
  view.endEdit()
}

// ---- Layer drag reorder (native) ----
const dropZone = ref<"before" | "after" | null>(null)
const isDraggable = computed(() => view.layerDrag.value !== null)

function onDragStart(event: DragEvent): void {
  const context = view.layerDrag.value
  if (!context) return
  layerDrag.start(context.property, context.layerIndex)
  if (event.dataTransfer) {
    event.dataTransfer.effectAllowed = "move"
    event.dataTransfer.setData("text/plain", `${context.layerIndex}`)
  }
}

function onDragEnd(): void {
  layerDrag.end()
  dropZone.value = null
}

function onDragOver(event: DragEvent): void {
  const context = view.layerDrag.value
  if (!context) return
  if (layerDrag.property !== context.property) return
  if (layerDrag.fromIndex === context.layerIndex) return
  const target = event.currentTarget as HTMLElement
  const rect = target.getBoundingClientRect()
  dropZone.value = event.clientY - rect.top < rect.height / 2 ? "before" : "after"
  event.preventDefault()
  if (event.dataTransfer) event.dataTransfer.dropEffect = "move"
}

function onDragLeave(): void {
  dropZone.value = null
}

function onDrop(event: DragEvent): void {
  const context = view.layerDrag.value
  const from = layerDrag.fromIndex
  const property = layerDrag.property
  dropZone.value = null
  if (!context || from === null || property !== context.property) {
    layerDrag.end()
    return
  }
  if (from === context.layerIndex) {
    layerDrag.end()
    return
  }
  event.preventDefault()
  dispatch({
    type: "reorder_node_layer",
    payload: {
      nodeId: (props.node as Variant | Instance).id,
      property,
      fromIndex: from,
      toIndex: context.layerIndex,
    },
  } as never)
  layerDrag.end()
}
</script>

<template>
  <ItemPropertyToggle
    v-if="isSwitch"
    :ref="(el: any) => (view.rowRef.value = el)"
    class="properties-row"
    :style="rowStyle"
    :seldon-refs="toggleRefs"
    :button-iconic="{}"
    :form-control-combobox="{}"
    :input="{}"
    :icon2="{}"
    :toggle-switch="{}"
    :button-iconic2="{}"
    @click="view.onRowClick"
    @dblclick="view.onRowDoubleClick"
  />

  <ItemProperty
    v-else
    :ref="(el: any) => (view.rowRef.value = el)"
    class="properties-row"
    :class="{
      'properties-row--drop-before': dropZone === 'before',
      'properties-row--drop-after': dropZone === 'after',
    }"
    :style="rowStyle"
    :draggable="isDraggable"
    :seldon-refs="seldonRefs"
    :button-iconic="hideDisclosure ? null : undefined"
    :input="{}"
    :icon2="valueIconSlot"
    @click="view.onRowClick"
    @dblclick="view.onRowDoubleClick"
    @dragstart="onDragStart"
    @dragend="onDragEnd"
    @dragover="onDragOver"
    @dragleave="onDragLeave"
    @drop="onDrop"
  />

  <MenuController
    v-if="actionsMenu.hasActions.value"
    :open="actionsMenu.open.value"
    :anchor="actionsMenu.anchor.value"
    :items="actionsMenu.menuItems.value"
    align="end"
    @close="actionsMenu.close"
  />

  <ComboboxOptions
    v-if="comboboxOpen"
    :open="comboboxOpen"
    :anchor="anchorEl"
    :option-groups="filteredGroups"
    :value="control.storedValue.value"
    :resolve-icon="resolveIcon"
    @select="onSelectOption"
    @close="onCloseOptions"
  />

  <FramerExpandable v-if="isCompoundParent" :is-expanded="view.isExpanded.value">
    <template v-if="view.hasChildren.value">
      <Property
        v-for="child in view.children.value"
        :key="child.key"
        :property="child"
        :workspace="workspace"
        :node="node"
        :theme="theme"
        :all-properties="allProperties"
        :theme-editing-context="themeEditingContext"
        :font-collection-editing-context="fontCollectionEditingContext"
        :icon-set-editing-context="iconSetEditingContext"
        :depth="childDepth"
      />
    </template>
  </FramerExpandable>
</template>

<style scoped>
.properties-row--drop-before {
  box-shadow: inset 0 2px 0 var(--sdn-swatch-active, #6366f1);
}
.properties-row--drop-after {
  box-shadow: inset 0 -2px 0 var(--sdn-swatch-active, #6366f1);
}
</style>
