// packages/editor-react/app/dialogs/components/ComponentsDialog.tsx
"use client"

import { usePanel } from "@app/editor/hooks/use-panel"
import { useTool } from "@app/editor/hooks/use-tool"
import { useAutoSelectNode } from "@app/workspace/hooks/use-auto-select-node"
import { useWorkspace } from "@app/workspace/hooks/use-workspace"
import { confirmMissingSchemaVariants } from "@seldon/editor/lib/workspace/confirm-missing-schema-variants"
import { useCallback } from "react"

import { invariant } from "@seldon/core"
import { validateComponentInsertionForUI } from "@seldon/core/workspace/reducers/helpers/validation"
import { InstanceId, VariantId } from "@seldon/core/workspace/types"

import { PanelDialogController } from "../PanelDialogController"
import {
  CatalogComponentItem,
  FilterComponentPredicate,
  useDialog,
} from "../hooks/use-dialog"

/**
 * Dialog for inserting an existing variant into the selected target node.
 */
export function ComponentsDialog() {
  const { activePanel, target, closePanel } = usePanel()
  const { setActiveTool } = useTool()
  const { dispatchWithAutoSelect } = useAutoSelectNode()
  const { workspace } = useWorkspace()

  const shouldShowComponent = useCallback<FilterComponentPredicate>(
    (schema) => {
      if (!target) return false

      // Use workspace validation system instead of custom logic
      const validation = validateComponentInsertionForUI(
        schema.id,
        target.nodeId as VariantId | InstanceId,
        workspace,
      )

      return validation.isValid
    },
    [target, workspace],
  )

  const { categories, query, setQuery } = useDialog({
    shouldShowComponent,
  })

  const handlePick = useCallback(
    async (item: CatalogComponentItem) => {
      invariant(target, "No target selected")

      // If the variant doesn't exist yet, create it
      if (!item.variantId) {
        const variantFallbacks = await confirmMissingSchemaVariants(
          item.componentId,
        )
        if (variantFallbacks === null) {
          return
        }

        dispatchWithAutoSelect({
          type: "add_component_and_insert_default_instance",
          payload: {
            boardKey: item.componentId,
            variantFallbacks: variantFallbacks.length
              ? variantFallbacks
              : undefined,
            target: {
              parentId: target.nodeId as VariantId | InstanceId,
              index: target.index,
            },
          },
        })
      } else {
        dispatchWithAutoSelect({
          type: "insert_variant_instance",
          payload: {
            variantId: item.variantId,
            target: {
              parentId: target.nodeId as VariantId | InstanceId,
              index: target.index,
            },
          },
        })
      }

      setActiveTool("select")
    },
    [target, dispatchWithAutoSelect, setActiveTool],
  )

  if (activePanel !== "component") return null

  return (
    <PanelDialogController
      title="Insert component"
      confirmButtonText="Insert component"
      categories={categories}
      query={query}
      onQueryChange={setQuery}
      onPick={handlePick}
      onClose={closePanel}
    />
  )
}

// packages/editor-vue/app/dialogs/ComponentsDialog.vue
<script setup lang="ts">
import type { ComponentSchema } from "@seldon/core/components/types"
import { validateComponentInsertionForUI } from "@seldon/core/workspace/reducers/helpers/validation"
import type { InstanceId, VariantId } from "@seldon/core/workspace/types"
import {
  useCatalogDialog,
  type CatalogItem,
} from "@app/dialogs/use-catalog-dialog"
import PanelDialogController from "@app/dialogs/PanelDialogController.vue"
import { usePanelStore } from "@app/editor/panel-store"
import { useToolStore } from "@app/editor/tool-store"
import { useAutoSelectNode } from "@app/workspace/use-auto-select-node"
import { useWorkspace } from "@app/workspace/use-workspace"
import { confirmMissingSchemaVariants } from "@seldon/editor/lib/workspace/confirm-missing-schema-variants"
import { storeToRefs } from "pinia"
import { computed, watch } from "vue"

const panel = usePanelStore()
const { activePanel, target } = storeToRefs(panel)
const tool = useToolStore()
const { workspace } = useWorkspace()
const { dispatchWithAutoSelect } = useAutoSelectNode()

const isOpen = computed(() => activePanel.value === "component")

function shouldShow(schema: ComponentSchema): boolean {
  const current = target.value
  if (!current) return false
  const validation = validateComponentInsertionForUI(
    schema.id,
    current.nodeId as VariantId | InstanceId,
    workspace.value,
  )
  return validation.isValid
}

const { categories, query } = useCatalogDialog(shouldShow)

watch(isOpen, (open) => {
  if (open) query.value = ""
})

function setQuery(next: string): void {
  query.value = next
}

async function pick(item: CatalogItem): Promise<void> {
  const current = target.value
  if (!current) return
  const variantFallbacks = await confirmMissingSchemaVariants(item.componentId)
  if (variantFallbacks === null) return

  dispatchWithAutoSelect({
    type: "add_component_and_insert_default_instance",
    payload: {
      boardKey: item.componentId,
      variantFallbacks: variantFallbacks.length ? variantFallbacks : undefined,
      target: {
        parentId: current.nodeId as VariantId | InstanceId,
        index: current.index,
      },
    },
  })
  tool.setActiveTool("select")
}

function close(): void {
  panel.closePanel()
}
</script>

<template>
  <PanelDialogController
    v-if="isOpen"
    title="Insert component"
    confirm-button-text="Insert component"
    :categories="categories"
    :query="query"
    :on-query-change="setQuery"
    :on-pick="pick"
    :on-close="close"
  />
</template>
