// packages/editor/apps/vue/app/dialogs/ThemesDialog.vue
<script setup lang="ts">
import { useAddRemoveCommands } from "@app/commands/use-add-remove-commands"
import PanelDialogController from "@app/dialogs/PanelDialogController.vue"
import { useStockCatalog } from "@app/dialogs/use-stock-catalog"
import { usePanelStore } from "@app/editor/panel-store"
import { useWorkspace } from "@app/workspace/use-workspace"
import { storeToRefs } from "pinia"
import { computed } from "vue"

import { STOCK_THEMES } from "@seldon/core/themes/catalog"

import type { CatalogDialogItem } from "@app/dialogs/types"

const THEME_ICON = "seldon-theme"

const panel = usePanelStore()
const { activePanel } = storeToRefs(panel)
const { workspace } = useWorkspace()
const { addTheme } = useAddRemoveCommands()

const isOpen = computed(() => activePanel.value === "add-theme")

const items = computed<CatalogDialogItem[]>(() =>
  STOCK_THEMES.filter((theme) => !workspace.value.boards[theme.metadata.id]).map((theme) => ({
    id: theme.metadata.id,
    icon: THEME_ICON,
    name: theme.metadata.name,
    description: theme.metadata.description ?? "",
  })),
)

const { categories, query } = useStockCatalog({ category: "Themes", items })

function setQuery(next: string): void {
  query.value = next
}

function pick(item: CatalogDialogItem): void {
  addTheme(item.id)
}

function close(): void {
  panel.closePanel()
}
</script>

<template>
  <PanelDialogController
    v-if="isOpen"
    title="Add theme"
    confirm-button-text="Add theme"
    :categories="categories"
    :query="query"
    :on-query-change="setQuery"
    :on-pick="pick"
    :on-close="close"
  />
</template>

// packages/editor/app/dialogs/themes/ThemesDialog.tsx
"use client"

import { useCallback, useMemo } from "react"
import { STOCK_THEMES } from "@seldon/core/themes/catalog"
import { useWorkspace } from "@lib/workspace/hooks/use-workspace"
import { useAddRemoveCommands } from "@lib/hooks/commands/use-add-remove-commands"
import { usePanel } from "@lib/hooks/use-panel"
import { useStockCatalog } from "../hooks/use-stock-catalog"
import { PanelDialogController } from "../PanelDialogController"
import { CatalogDialogItem } from "../types"

const THEME_ICON = "seldon-theme"

/**
 * Dialog for adding a stock theme board to the workspace.
 */
export function ThemesDialog() {
  const { activePanel, closePanel } = usePanel()
  const { workspace } = useWorkspace()
  const { addTheme } = useAddRemoveCommands()

  const currentBoards = useMemo(
    () => Object.keys(workspace.boards),
    [workspace],
  )

  const items = useMemo<CatalogDialogItem[]>(
    () =>
      STOCK_THEMES.filter(
        (theme) => !currentBoards.includes(theme.metadata.id),
      ).map((theme) => ({
        id: theme.metadata.id,
        icon: THEME_ICON,
        name: theme.metadata.name,
        description: theme.metadata.description,
      })),
    [currentBoards],
  )

  const { categories, query, setQuery } = useStockCatalog({
    category: "Themes",
    items,
  })

  const handlePick = useCallback(
    (item: CatalogDialogItem) => addTheme(item.id),
    [addTheme],
  )

  if (activePanel !== "add-theme") return null

  return (
    <PanelDialogController
      title="Add theme"
      confirmButtonText="Add theme"
      categories={categories}
      query={query}
      onQueryChange={setQuery}
      onPick={handlePick}
      onClose={closePanel}
    />
  )
}
