// packages/editor-vue/seldon/parts/BarMenus.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/*****
 * Bar: BarMenus
 * Level: Part
 * Intent: Groups related controls in a horizontal bar with buttons, navigation, or tabs layouts.
 * Tags: bar, controls, buttons, navigation, tabs, UI, layout, group
 * Type: Custom
 *
 * @example
 * ```vue
 * <BarMenus
 *   role="menubar"
 *   aria-hidden="false"
 * />
 * ```
 *****/
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"
import { combineClassNames, mergeSlot } from "../utils/class-names"
import ButtonSimple from "../elements/ButtonSimple.vue"
import TextLabel from "../primitives/TextLabel.vue"

const props = defineProps<{
  className?: string
  buttonSimple?: Record<string, unknown> | null
  textLabel?: Record<string, unknown> | null
  buttonSimple2?: Record<string, unknown> | null
  textLabel2?: Record<string, unknown> | null
  buttonSimple3?: Record<string, unknown> | null
  textLabel3?: Record<string, unknown> | null
  buttonSimple4?: Record<string, unknown> | null
  textLabel4?: Record<string, unknown> | null
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "role": "menubar",
  "aria-hidden": "false",
  "className": "sdn-bar-menus sdn-bar",
  "buttonSimple": {
    "aria-haspopup": "menu",
    "className": "sdn-button-simple sdn-button-simple--fjtm"
  },
  "textLabel": {
    "className": "sdn-text-label sdn-text-label--ylte"
  },
  "buttonSimple2": {
    "aria-haspopup": "menu",
    "className": "sdn-button-simple sdn-button-simple--fjtm"
  },
  "textLabel2": {
    "className": "sdn-text-label sdn-text-label--ylte"
  },
  "buttonSimple3": {
    "aria-haspopup": "menu",
    "className": "sdn-button-simple sdn-button-simple--fjtm"
  },
  "textLabel3": {
    "className": "sdn-text-label sdn-text-label--ylte"
  },
  "buttonSimple4": {
    "aria-haspopup": "menu",
    "className": "sdn-button-simple sdn-button-simple--fjtm"
  },
  "textLabel4": {
    "className": "sdn-text-label sdn-text-label--ylte"
  }
}

const rootClassName = computed(() => combineClassNames("sdn-bar-menus", props.className))
const rootAttrs = { "role": sdn["role"], "aria-hidden": sdn["aria-hidden"] }
const buttonSimpleProps = computed(() => mergeSlot(sdn.buttonSimple, props.buttonSimple))
const textLabelProps = computed(() => mergeSlot(sdn.textLabel, props.textLabel))
const buttonSimple2Props = computed(() => mergeSlot(sdn.buttonSimple2, props.buttonSimple2))
const textLabel2Props = computed(() => mergeSlot(sdn.textLabel2, props.textLabel2))
const buttonSimple3Props = computed(() => mergeSlot(sdn.buttonSimple3, props.buttonSimple3))
const textLabel3Props = computed(() => mergeSlot(sdn.textLabel3, props.textLabel3))
const buttonSimple4Props = computed(() => mergeSlot(sdn.buttonSimple4, props.buttonSimple4))
const textLabel4Props = computed(() => mergeSlot(sdn.textLabel4, props.textLabel4))
</script>

<template>
    <div :class="rootClassName" v-bind="rootAttrs">
      <slot>
        <ButtonSimple v-if="buttonSimpleProps !== null" v-bind="buttonSimpleProps">
          <TextLabel v-if="textLabel && textLabelProps" v-bind="textLabelProps" />
        </ButtonSimple>
        <ButtonSimple v-if="buttonSimple2Props !== null" v-bind="buttonSimple2Props">
          <TextLabel v-if="textLabel2 && textLabel2Props" v-bind="textLabel2Props" />
        </ButtonSimple>
        <ButtonSimple v-if="buttonSimple3Props !== null" v-bind="buttonSimple3Props">
          <TextLabel v-if="textLabel3 && textLabel3Props" v-bind="textLabel3Props" />
        </ButtonSimple>
        <ButtonSimple v-if="buttonSimple4Props !== null" v-bind="buttonSimple4Props">
          <TextLabel v-if="textLabel4 && textLabel4Props" v-bind="textLabel4Props" />
        </ButtonSimple>
      </slot>
    </div>
</template>

// packages/editor-react/seldon/parts/BarMenus.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/
import { HTMLAttributes } from "react"

import { ButtonSimple, ButtonSimpleProps } from "../elements/ButtonSimple"
import { Frame } from "../frames/Frame"
import { TextLabel, TextLabelProps } from "../primitives/TextLabel"
import { applyRef } from "../utils/apply-ref"
import { combineClassNames } from "../utils/class-name"

export interface BarMenusProps extends HTMLAttributes<HTMLElement> {
  className?: string
  "data-seldon-ref"?: string
  seldonRefs?: Record<string, Record<string, unknown>>
  buttonSimple?: ButtonSimpleProps | null
  textLabel?: TextLabelProps | null
  buttonSimple2?: ButtonSimpleProps | null
  textLabel2?: TextLabelProps | null
  buttonSimple3?: ButtonSimpleProps | null
  textLabel3?: TextLabelProps | null
  buttonSimple4?: ButtonSimpleProps | null
  textLabel4?: TextLabelProps | null
}

/*****
 * Bar: BarMenus
 * Level: Part
 * Intent: Groups related controls in a horizontal bar with buttons, navigation, or tabs layouts.
 * Tags: bar, controls, buttons, navigation, tabs, UI, layout, group
 * Type: Custom
 *
 * @example
 * ```tsx
 * <BarMenus
 *   role="menubar"
 *   aria-hidden="false"
 * />
 * ```
 *****/
export function BarMenus({
  className = "",
  buttonSimple = sdn.buttonSimple,
  textLabel,
  buttonSimple2 = sdn.buttonSimple2,
  textLabel2,
  buttonSimple3 = sdn.buttonSimple3,
  textLabel3,
  buttonSimple4 = sdn.buttonSimple4,
  textLabel4,
  children,
  seldonRefs,
  ...props
}: BarMenusProps) {
  const barMenusClassName = combineClassNames("sdn-bar-menus", className)
  const buttonSimpleProps = applyRef(
    seldonRefs,
    buttonSimple === null
      ? null
      : {
          ...sdn.buttonSimple,
          ...buttonSimple,
          className: combineClassNames(
            sdn.buttonSimple?.className,
            buttonSimple?.className,
          ),
        },
  )
  const textLabelProps = applyRef(
    seldonRefs,
    textLabel === null
      ? null
      : {
          ...sdn.textLabel,
          ...textLabel,
          className: combineClassNames(
            sdn.textLabel?.className,
            textLabel?.className,
          ),
        },
  )
  const buttonSimple2Props = applyRef(
    seldonRefs,
    buttonSimple2 === null
      ? null
      : {
          ...sdn.buttonSimple2,
          ...buttonSimple2,
          className: combineClassNames(
            sdn.buttonSimple2?.className,
            buttonSimple2?.className,
          ),
        },
  )
  const textLabel2Props = applyRef(
    seldonRefs,
    textLabel2 === null
      ? null
      : {
          ...sdn.textLabel2,
          ...textLabel2,
          className: combineClassNames(
            sdn.textLabel2?.className,
            textLabel2?.className,
          ),
        },
  )
  const buttonSimple3Props = applyRef(
    seldonRefs,
    buttonSimple3 === null
      ? null
      : {
          ...sdn.buttonSimple3,
          ...buttonSimple3,
          className: combineClassNames(
            sdn.buttonSimple3?.className,
            buttonSimple3?.className,
          ),
        },
  )
  const textLabel3Props = applyRef(
    seldonRefs,
    textLabel3 === null
      ? null
      : {
          ...sdn.textLabel3,
          ...textLabel3,
          className: combineClassNames(
            sdn.textLabel3?.className,
            textLabel3?.className,
          ),
        },
  )
  const buttonSimple4Props = applyRef(
    seldonRefs,
    buttonSimple4 === null
      ? null
      : {
          ...sdn.buttonSimple4,
          ...buttonSimple4,
          className: combineClassNames(
            sdn.buttonSimple4?.className,
            buttonSimple4?.className,
          ),
        },
  )
  const textLabel4Props = applyRef(
    seldonRefs,
    textLabel4 === null
      ? null
      : {
          ...sdn.textLabel4,
          ...textLabel4,
          className: combineClassNames(
            sdn.textLabel4?.className,
            textLabel4?.className,
          ),
        },
  )

  return (
    <Frame
      className={barMenusClassName}
      role={sdn["role"]}
      aria-hidden={sdn["aria-hidden"]}
      {...props}
    >
      {children !== undefined ? (
        children
      ) : (
        <>
          {buttonSimpleProps !== null && (
            <ButtonSimple {...buttonSimpleProps}>
              {textLabel && textLabelProps && <TextLabel {...textLabelProps} />}
            </ButtonSimple>
          )}
          {buttonSimple2Props !== null && (
            <ButtonSimple {...buttonSimple2Props}>
              {textLabel2 && textLabel2Props && (
                <TextLabel {...textLabel2Props} />
              )}
            </ButtonSimple>
          )}
          {buttonSimple3Props !== null && (
            <ButtonSimple {...buttonSimple3Props}>
              {textLabel3 && textLabel3Props && (
                <TextLabel {...textLabel3Props} />
              )}
            </ButtonSimple>
          )}
          {buttonSimple4Props !== null && (
            <ButtonSimple {...buttonSimple4Props}>
              {textLabel4 && textLabel4Props && (
                <TextLabel {...textLabel4Props} />
              )}
            </ButtonSimple>
          )}
        </>
      )}
    </Frame>
  )
}

//
// Default property values
//
const sdn: BarMenusProps = {
  role: "menubar",
  "aria-hidden": "false",
  className: "sdn-bar-menus sdn-bar",
  buttonSimple: {
    "aria-haspopup": "menu",
    className: "sdn-button-simple sdn-button-simple--fjtm",
  },
  textLabel: {
    className: "sdn-text-label sdn-text-label--ylte",
  },
  buttonSimple2: {
    "aria-haspopup": "menu",
    className: "sdn-button-simple sdn-button-simple--fjtm",
  },
  textLabel2: {
    className: "sdn-text-label sdn-text-label--ylte",
  },
  buttonSimple3: {
    "aria-haspopup": "menu",
    className: "sdn-button-simple sdn-button-simple--fjtm",
  },
  textLabel3: {
    className: "sdn-text-label sdn-text-label--ylte",
  },
  buttonSimple4: {
    "aria-haspopup": "menu",
    className: "sdn-button-simple sdn-button-simple--fjtm",
  },
  textLabel4: {
    className: "sdn-text-label sdn-text-label--ylte",
  },
}
