// packages/editor/apps/vue/app/toaster/Toaster.vue
<script setup lang="ts">
import { useToastStore } from "@app/toaster/toast-store"
import { AnimatePresence } from "motion-v"
import { storeToRefs } from "pinia"

import Toast from "./Toast.vue"
import ToastStack from "./ToastStack.vue"

const toastStore = useToastStore()
const { toasts } = storeToRefs(toastStore)
</script>

<template>
  <Teleport to="body">
    <ToastStack>
      <AnimatePresence mode="popLayout">
        <Toast v-for="toast in toasts" :key="toast.id" :message="toast.message" />
      </AnimatePresence>
    </ToastStack>
  </Teleport>
</template>

// packages/editor-react/app/toaster/Toaster.tsx
"use client"

import { AnimatePresence } from "framer-motion"
import { useShallow } from "zustand/react/shallow"
import { useToastStore } from "./hooks/use-toast-store"
import { Toast } from "./Toast.bespoke"
import { ToastStack } from "./ToastStack.bespoke"

export function Toasts() {
  const toasts = useToastStore(useShallow((state) => state.toasts))

  return (
    <ToastStack>
      <AnimatePresence mode="popLayout">
        {toasts.map((toast) => (
          <Toast key={toast.id} message={toast.message} />
        ))}
      </AnimatePresence>
    </ToastStack>
  )
}
