// packages/editor/app/LoadEditorFonts.tsx
"use client"

import { useMemo } from "react"
import { workspaceFontCollectionService } from "@seldon/core/workspace/services"
import { buildFontFaceCss } from "@lib/font-collections/build-font-face-css"
import { useWorkspace } from "@lib/workspace/hooks/use-workspace"

/**
 * Self-hosts every enabled font-collection family for the canvas. The enabled
 * families' woff2 files are served from `public/font-files`, so this injects a
 * single `@font-face` stylesheet and makes no network request to a font host.
 */
export function LoadEditorFonts() {
  const { workspace } = useWorkspace({ usePreview: false })

  const fontFaceCss = useMemo(() => {
    const families =
      workspaceFontCollectionService.getEnabledRemoteFamilies(workspace)
    return buildFontFaceCss(families)
  }, [workspace])

  if (!fontFaceCss) {
    return null
  }

  return <style>{fontFaceCss}</style>
}

// packages/editor/apps/vue/app/editor/LoadEditorFonts.vue
<script setup lang="ts">
import { buildFontFaceCss } from "@seldon/editor/lib/font-collections/build-font-face-css"
import { computed } from "vue"

import { workspaceFontCollectionService } from "@seldon/core/workspace/services"

import type { Workspace } from "@seldon/core/workspace/types"

const props = defineProps<{ workspace: Workspace }>()

// Self-hosts every enabled font-collection family for the canvas. The enabled
// families' woff2 files are served from `public/font-files`, so this injects a
// single `@font-face` stylesheet with no request to a font host. Mirrors the
// React `LoadEditorFonts`.
const fontFaceCss = computed(() => {
  const families = workspaceFontCollectionService.getEnabledRemoteFamilies(props.workspace)
  return buildFontFaceCss(families)
})
</script>

<template>
  <Teleport to="head">
    <component :is="'style'" v-if="fontFaceCss">{{ fontFaceCss }}</component>
  </Teleport>
</template>
