// packages/editor/seldon/parts/ListStandard.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/
import { HTMLAttributes } from "react"
import { Button, ButtonProps } from "../elements/Button"
import { Item, ItemProps } from "../elements/Item"
import { Frame, FrameProps } from "../frames/Frame"
import { HTMLUl } from "../native-react/HTML.Ul"
import { Icon, IconProps } from "../primitives/Icon"
import { InputCheckbox, InputCheckboxProps } from "../primitives/InputCheckbox"
import { TextLabel, TextLabelProps } from "../primitives/TextLabel"
import { TextSubtitle, TextSubtitleProps } from "../primitives/TextSubtitle"
import { TextTitle, TextTitleProps } from "../primitives/TextTitle"
import { applyRef } from "../utils/apply-ref"
import { combineClassNames } from "../utils/class-name"

export interface ListStandardProps extends HTMLAttributes<HTMLUListElement> {
  className?: string
  "data-seldon-ref"?: string
  seldonRefs?: Record<string, Record<string, unknown>>
  item?: ItemProps | null
  inputCheckbox?: InputCheckboxProps | null
  frame?: FrameProps | null
  textTitle?: TextTitleProps | null
  textSubtitle?: TextSubtitleProps | null
  button?: ButtonProps | null
  icon?: IconProps | null
  textLabel?: TextLabelProps | null
  item2?: ItemProps | null
  inputCheckbox2?: InputCheckboxProps | null
  frame2?: FrameProps | null
  textTitle2?: TextTitleProps | null
  textSubtitle2?: TextSubtitleProps | null
  button2?: ButtonProps | null
  icon2?: IconProps | null
  textLabel2?: TextLabelProps | null
  item3?: ItemProps | null
  inputCheckbox3?: InputCheckboxProps | null
  frame3?: FrameProps | null
  textTitle3?: TextTitleProps | null
  textSubtitle3?: TextSubtitleProps | null
  button3?: ButtonProps | null
  icon3?: IconProps | null
  textLabel3?: TextLabelProps | null
}

/*****
 * List: Standard
 * Level: Part
 * Intent: General-purpose vertical list schema for rendering repeated content items such as posts, links, or summaries.
 * Tags: list, standard, vertical, ui, content, items, generic, repeater
 * Type: Default
 *
 * @example
 * ```tsx
 * <ListStandard
 *   aria-hidden="false"
 *   item="{}"
 *   inputCheckbox="{}"
 *   frame="{}"
 *   textTitle="Product Title"
 *   textSubtitle2="Product Title"
 *   button={() => {}}
 *   icon="material-star"
 *   textLabel="{}"
 *   item2="{}"
 *   item3="{}"
 * />
 * ```
 *****/
export function ListStandard({
  className = "",
  item = sdn.item,
  inputCheckbox,
  frame = sdn.frame,
  textTitle,
  textSubtitle,
  button = sdn.button,
  icon = sdn.icon,
  textLabel,
  item2 = sdn.item2,
  inputCheckbox2,
  frame2 = sdn.frame2,
  textTitle2,
  textSubtitle2,
  button2 = sdn.button2,
  icon2 = sdn.icon2,
  textLabel2,
  item3 = sdn.item3,
  inputCheckbox3,
  frame3 = sdn.frame3,
  textTitle3,
  textSubtitle3,
  button3 = sdn.button3,
  icon3 = sdn.icon3,
  textLabel3,
  children,
  seldonRefs,
  ...props
}: ListStandardProps) {
  const listStandardClassName = combineClassNames(
    "sdn-list-standard",
    className,
  )
  const itemProps = applyRef(
    seldonRefs,
    item === null
      ? null
      : {
          ...sdn.item,
          ...item,
          className: combineClassNames(sdn.item?.className, item?.className),
        },
  )
  const inputCheckboxProps = applyRef(
    seldonRefs,
    inputCheckbox === null
      ? null
      : {
          ...sdn.inputCheckbox,
          ...inputCheckbox,
          className: combineClassNames(
            sdn.inputCheckbox?.className,
            inputCheckbox?.className,
          ),
        },
  )
  const frameProps = applyRef(
    seldonRefs,
    frame === null
      ? null
      : {
          ...sdn.frame,
          ...frame,
          className: combineClassNames(sdn.frame?.className, frame?.className),
        },
  )
  const textTitleProps = applyRef(
    seldonRefs,
    textTitle === null
      ? null
      : {
          ...sdn.textTitle,
          ...textTitle,
          className: combineClassNames(
            sdn.textTitle?.className,
            textTitle?.className,
          ),
        },
  )
  const textSubtitleProps = applyRef(
    seldonRefs,
    textSubtitle === null
      ? null
      : {
          ...sdn.textSubtitle,
          ...textSubtitle,
          className: combineClassNames(
            sdn.textSubtitle?.className,
            textSubtitle?.className,
          ),
        },
  )
  const buttonProps = applyRef(
    seldonRefs,
    button === null
      ? null
      : {
          ...sdn.button,
          ...button,
          className: combineClassNames(
            sdn.button?.className,
            button?.className,
          ),
        },
  )
  const iconProps = applyRef(
    seldonRefs,
    icon === null
      ? null
      : {
          ...sdn.icon,
          ...icon,
          className: combineClassNames(sdn.icon?.className, icon?.className),
        },
  )
  const textLabelProps = applyRef(
    seldonRefs,
    textLabel === null
      ? null
      : {
          ...sdn.textLabel,
          ...textLabel,
          className: combineClassNames(
            sdn.textLabel?.className,
            textLabel?.className,
          ),
        },
  )
  const item2Props = applyRef(
    seldonRefs,
    item2 === null
      ? null
      : {
          ...sdn.item2,
          ...item2,
          className: combineClassNames(sdn.item2?.className, item2?.className),
        },
  )
  const inputCheckbox2Props = applyRef(
    seldonRefs,
    inputCheckbox2 === null
      ? null
      : {
          ...sdn.inputCheckbox2,
          ...inputCheckbox2,
          className: combineClassNames(
            sdn.inputCheckbox2?.className,
            inputCheckbox2?.className,
          ),
        },
  )
  const frame2Props = applyRef(
    seldonRefs,
    frame2 === null
      ? null
      : {
          ...sdn.frame2,
          ...frame2,
          className: combineClassNames(
            sdn.frame2?.className,
            frame2?.className,
          ),
        },
  )
  const textTitle2Props = applyRef(
    seldonRefs,
    textTitle2 === null
      ? null
      : {
          ...sdn.textTitle2,
          ...textTitle2,
          className: combineClassNames(
            sdn.textTitle2?.className,
            textTitle2?.className,
          ),
        },
  )
  const textSubtitle2Props = applyRef(
    seldonRefs,
    textSubtitle2 === null
      ? null
      : {
          ...sdn.textSubtitle2,
          ...textSubtitle2,
          className: combineClassNames(
            sdn.textSubtitle2?.className,
            textSubtitle2?.className,
          ),
        },
  )
  const button2Props = applyRef(
    seldonRefs,
    button2 === null
      ? null
      : {
          ...sdn.button2,
          ...button2,
          className: combineClassNames(
            sdn.button2?.className,
            button2?.className,
          ),
        },
  )
  const icon2Props = applyRef(
    seldonRefs,
    icon2 === null
      ? null
      : {
          ...sdn.icon2,
          ...icon2,
          className: combineClassNames(sdn.icon2?.className, icon2?.className),
        },
  )
  const textLabel2Props = applyRef(
    seldonRefs,
    textLabel2 === null
      ? null
      : {
          ...sdn.textLabel2,
          ...textLabel2,
          className: combineClassNames(
            sdn.textLabel2?.className,
            textLabel2?.className,
          ),
        },
  )
  const item3Props = applyRef(
    seldonRefs,
    item3 === null
      ? null
      : {
          ...sdn.item3,
          ...item3,
          className: combineClassNames(sdn.item3?.className, item3?.className),
        },
  )
  const inputCheckbox3Props = applyRef(
    seldonRefs,
    inputCheckbox3 === null
      ? null
      : {
          ...sdn.inputCheckbox3,
          ...inputCheckbox3,
          className: combineClassNames(
            sdn.inputCheckbox3?.className,
            inputCheckbox3?.className,
          ),
        },
  )
  const frame3Props = applyRef(
    seldonRefs,
    frame3 === null
      ? null
      : {
          ...sdn.frame3,
          ...frame3,
          className: combineClassNames(
            sdn.frame3?.className,
            frame3?.className,
          ),
        },
  )
  const textTitle3Props = applyRef(
    seldonRefs,
    textTitle3 === null
      ? null
      : {
          ...sdn.textTitle3,
          ...textTitle3,
          className: combineClassNames(
            sdn.textTitle3?.className,
            textTitle3?.className,
          ),
        },
  )
  const textSubtitle3Props = applyRef(
    seldonRefs,
    textSubtitle3 === null
      ? null
      : {
          ...sdn.textSubtitle3,
          ...textSubtitle3,
          className: combineClassNames(
            sdn.textSubtitle3?.className,
            textSubtitle3?.className,
          ),
        },
  )
  const button3Props = applyRef(
    seldonRefs,
    button3 === null
      ? null
      : {
          ...sdn.button3,
          ...button3,
          className: combineClassNames(
            sdn.button3?.className,
            button3?.className,
          ),
        },
  )
  const icon3Props = applyRef(
    seldonRefs,
    icon3 === null
      ? null
      : {
          ...sdn.icon3,
          ...icon3,
          className: combineClassNames(sdn.icon3?.className, icon3?.className),
        },
  )
  const textLabel3Props = applyRef(
    seldonRefs,
    textLabel3 === null
      ? null
      : {
          ...sdn.textLabel3,
          ...textLabel3,
          className: combineClassNames(
            sdn.textLabel3?.className,
            textLabel3?.className,
          ),
        },
  )

  return (
    <HTMLUl
      className={listStandardClassName}
      aria-hidden={sdn["aria-hidden"]}
      {...props}
    >
      {children !== undefined ? (
        children
      ) : (
        <>
          {itemProps !== null && (
            <Item {...itemProps}>
              {inputCheckbox && inputCheckboxProps && (
                <InputCheckbox {...inputCheckboxProps} />
              )}
              <Frame {...frameProps}>
                {textTitle && textTitleProps && (
                  <TextTitle {...textTitleProps} />
                )}
                {textSubtitle && textSubtitleProps && (
                  <TextSubtitle {...textSubtitleProps} />
                )}
              </Frame>
              {button && buttonProps && (
                <Button {...buttonProps}>
                  {icon && iconProps && <Icon {...iconProps} />}
                  {textLabel && textLabelProps && (
                    <TextLabel {...textLabelProps} />
                  )}
                </Button>
              )}
            </Item>
          )}
          {item2Props !== null && (
            <Item {...item2Props}>
              {inputCheckbox2 && inputCheckbox2Props && (
                <InputCheckbox {...inputCheckbox2Props} />
              )}
              <Frame {...frame2Props}>
                {textTitle2 && textTitle2Props && (
                  <TextTitle {...textTitle2Props} />
                )}
                {textSubtitle2 && textSubtitle2Props && (
                  <TextSubtitle {...textSubtitle2Props} />
                )}
              </Frame>
              {button2 && button2Props && (
                <Button {...button2Props}>
                  {icon2 && icon2Props && <Icon {...icon2Props} />}
                  {textLabel2 && textLabel2Props && (
                    <TextLabel {...textLabel2Props} />
                  )}
                </Button>
              )}
            </Item>
          )}
          {item3Props !== null && (
            <Item {...item3Props}>
              {inputCheckbox3 && inputCheckbox3Props && (
                <InputCheckbox {...inputCheckbox3Props} />
              )}
              <Frame {...frame3Props}>
                {textTitle3 && textTitle3Props && (
                  <TextTitle {...textTitle3Props} />
                )}
                {textSubtitle3 && textSubtitle3Props && (
                  <TextSubtitle {...textSubtitle3Props} />
                )}
              </Frame>
              {button3 && button3Props && (
                <Button {...button3Props}>
                  {icon3 && icon3Props && <Icon {...icon3Props} />}
                  {textLabel3 && textLabel3Props && (
                    <TextLabel {...textLabel3Props} />
                  )}
                </Button>
              )}
            </Item>
          )}
        </>
      )}
    </HTMLUl>
  )
}

//
// Default property values
//
const sdn: ListStandardProps = {
  "aria-hidden": "false",
  className: "sdn-list-standard",
  item: {
    "aria-hidden": "false",
    className: "sdn-item sdn-item--vvmc",
  },
  inputCheckbox: {
    className: "sdn-input-checkbox sdn-input-checkbox--vajr",
  },
  frame: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--nhfs",
  },
  textTitle: {
    className: "sdn-text-title sdn-text-label--yqnd",
  },
  textSubtitle: {
    className: "sdn-text-subtitle sdn-text-subtitle--pyri",
  },
  button: {
    className: "sdn-button sdn-button-iconic--pgsr",
  },
  icon: {
    icon: "seldon-component",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--umgs",
  },
  textLabel: {
    className: "sdn-text-label sdn-text-label--ylte",
  },
  item2: {
    "aria-hidden": "false",
    className: "sdn-item sdn-item--vvmc",
  },
  inputCheckbox2: {
    className: "sdn-input-checkbox sdn-input-checkbox--vajr",
  },
  frame2: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--nhfs",
  },
  textTitle2: {
    className: "sdn-text-title sdn-text-label--yqnd",
  },
  textSubtitle2: {
    className: "sdn-text-subtitle sdn-text-subtitle--pyri",
  },
  button2: {
    className: "sdn-button sdn-button-iconic--pgsr",
  },
  icon2: {
    icon: "seldon-component",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--umgs",
  },
  textLabel2: {
    className: "sdn-text-label sdn-text-label--ylte",
  },
  item3: {
    "aria-hidden": "false",
    className: "sdn-item sdn-item--7egk",
  },
  inputCheckbox3: {
    className: "sdn-input-checkbox sdn-input-checkbox--vajr",
  },
  frame3: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--nhfs",
  },
  textTitle3: {
    className: "sdn-text-title sdn-text-label--yqnd",
  },
  textSubtitle3: {
    className: "sdn-text-subtitle sdn-text-subtitle--pyri",
  },
  button3: {
    className: "sdn-button sdn-button-iconic--pgsr",
  },
  icon3: {
    icon: "seldon-component",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--umgs",
  },
  textLabel3: {
    className: "sdn-text-label sdn-text-label--ylte",
  },
}

// packages/editor-vue/seldon/parts/ListStandard.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/*****
 * List: Standard
 * Level: Part
 * Intent: General-purpose vertical list schema for rendering repeated content items such as posts, links, or summaries.
 * Tags: list, standard, vertical, ui, content, items, generic, repeater
 * Type: Default
 *
 * @example
 * ```vue
 * <ListStandard
 *   aria-hidden="false"
 *   item="{}"
 *   inputCheckbox="{}"
 *   frame="{}"
 *   textTitle="Product Title"
 *   textSubtitle2="Product Title"
 *   button={() => {}}
 *   icon="material-star"
 *   textLabel="{}"
 *   item2="{}"
 *   item3="{}"
 * />
 * ```
 *****/
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"
import { combineClassNames, mergeSlot } from "../utils/class-names"
import Frame from "../frames/Frame.vue"
import Button from "../elements/Button.vue"
import Icon from "../primitives/Icon.vue"
import InputCheckbox from "../primitives/InputCheckbox.vue"
import Item from "../elements/Item.vue"
import TextLabel from "../primitives/TextLabel.vue"
import TextSubtitle from "../primitives/TextSubtitle.vue"
import TextTitle from "../primitives/TextTitle.vue"

const props = defineProps<{
  className?: string
  item?: Record<string, unknown> | null
  inputCheckbox?: Record<string, unknown> | null
  frame?: Record<string, unknown> | null
  textTitle?: Record<string, unknown> | null
  textSubtitle?: Record<string, unknown> | null
  button?: Record<string, unknown> | null
  icon?: Record<string, unknown> | null
  textLabel?: Record<string, unknown> | null
  item2?: Record<string, unknown> | null
  inputCheckbox2?: Record<string, unknown> | null
  frame2?: Record<string, unknown> | null
  textTitle2?: Record<string, unknown> | null
  textSubtitle2?: Record<string, unknown> | null
  button2?: Record<string, unknown> | null
  icon2?: Record<string, unknown> | null
  textLabel2?: Record<string, unknown> | null
  item3?: Record<string, unknown> | null
  inputCheckbox3?: Record<string, unknown> | null
  frame3?: Record<string, unknown> | null
  textTitle3?: Record<string, unknown> | null
  textSubtitle3?: Record<string, unknown> | null
  button3?: Record<string, unknown> | null
  icon3?: Record<string, unknown> | null
  textLabel3?: Record<string, unknown> | null
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "aria-hidden": "false",
  "className": "sdn-list-standard",
  "item": {
    "aria-hidden": "false",
    "className": "sdn-item sdn-item--vvmc"
  },
  "inputCheckbox": {
    "className": "sdn-input-checkbox sdn-input-checkbox--vajr"
  },
  "frame": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--nhfs"
  },
  "textTitle": {
    "className": "sdn-text-title sdn-text-label--yqnd"
  },
  "textSubtitle": {
    "className": "sdn-text-subtitle sdn-text-subtitle--pyri"
  },
  "button": {
    "className": "sdn-button sdn-button-iconic--pgsr"
  },
  "icon": {
    "icon": "seldon-component",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--umgs"
  },
  "textLabel": {
    "className": "sdn-text-label sdn-text-label--ylte"
  },
  "item2": {
    "aria-hidden": "false",
    "className": "sdn-item sdn-item--vvmc"
  },
  "inputCheckbox2": {
    "className": "sdn-input-checkbox sdn-input-checkbox--vajr"
  },
  "frame2": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--nhfs"
  },
  "textTitle2": {
    "className": "sdn-text-title sdn-text-label--yqnd"
  },
  "textSubtitle2": {
    "className": "sdn-text-subtitle sdn-text-subtitle--pyri"
  },
  "button2": {
    "className": "sdn-button sdn-button-iconic--pgsr"
  },
  "icon2": {
    "icon": "seldon-component",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--umgs"
  },
  "textLabel2": {
    "className": "sdn-text-label sdn-text-label--ylte"
  },
  "item3": {
    "aria-hidden": "false",
    "className": "sdn-item sdn-item--7egk"
  },
  "inputCheckbox3": {
    "className": "sdn-input-checkbox sdn-input-checkbox--vajr"
  },
  "frame3": {
    "wrapperElement": "div",
    "aria-hidden": "false",
    "className": "sdn-frame sdn-frame--nhfs"
  },
  "textTitle3": {
    "className": "sdn-text-title sdn-text-label--yqnd"
  },
  "textSubtitle3": {
    "className": "sdn-text-subtitle sdn-text-subtitle--pyri"
  },
  "button3": {
    "className": "sdn-button sdn-button-iconic--pgsr"
  },
  "icon3": {
    "icon": "seldon-component",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--umgs"
  },
  "textLabel3": {
    "className": "sdn-text-label sdn-text-label--ylte"
  }
}

const rootClassName = computed(() => combineClassNames("sdn-list-standard", props.className))
const rootAttrs = { "aria-hidden": sdn["aria-hidden"] }
const itemProps = computed(() => mergeSlot(sdn.item, props.item))
const inputCheckboxProps = computed(() => mergeSlot(sdn.inputCheckbox, props.inputCheckbox))
const frameProps = computed(() => mergeSlot(sdn.frame, props.frame))
const textTitleProps = computed(() => mergeSlot(sdn.textTitle, props.textTitle))
const textSubtitleProps = computed(() => mergeSlot(sdn.textSubtitle, props.textSubtitle))
const buttonProps = computed(() => mergeSlot(sdn.button, props.button))
const iconProps = computed(() => mergeSlot(sdn.icon, props.icon))
const textLabelProps = computed(() => mergeSlot(sdn.textLabel, props.textLabel))
const item2Props = computed(() => mergeSlot(sdn.item2, props.item2))
const inputCheckbox2Props = computed(() => mergeSlot(sdn.inputCheckbox2, props.inputCheckbox2))
const frame2Props = computed(() => mergeSlot(sdn.frame2, props.frame2))
const textTitle2Props = computed(() => mergeSlot(sdn.textTitle2, props.textTitle2))
const textSubtitle2Props = computed(() => mergeSlot(sdn.textSubtitle2, props.textSubtitle2))
const button2Props = computed(() => mergeSlot(sdn.button2, props.button2))
const icon2Props = computed(() => mergeSlot(sdn.icon2, props.icon2))
const textLabel2Props = computed(() => mergeSlot(sdn.textLabel2, props.textLabel2))
const item3Props = computed(() => mergeSlot(sdn.item3, props.item3))
const inputCheckbox3Props = computed(() => mergeSlot(sdn.inputCheckbox3, props.inputCheckbox3))
const frame3Props = computed(() => mergeSlot(sdn.frame3, props.frame3))
const textTitle3Props = computed(() => mergeSlot(sdn.textTitle3, props.textTitle3))
const textSubtitle3Props = computed(() => mergeSlot(sdn.textSubtitle3, props.textSubtitle3))
const button3Props = computed(() => mergeSlot(sdn.button3, props.button3))
const icon3Props = computed(() => mergeSlot(sdn.icon3, props.icon3))
const textLabel3Props = computed(() => mergeSlot(sdn.textLabel3, props.textLabel3))
</script>

<template>
    <ul :class="rootClassName" v-bind="rootAttrs">
      <slot>
        <Item v-if="itemProps !== null" v-bind="itemProps">
          <InputCheckbox v-if="inputCheckbox && inputCheckboxProps" v-bind="inputCheckboxProps" />
          <Frame v-bind="frameProps" v-if="frame">
            <TextTitle v-if="textTitle && textTitleProps" v-bind="textTitleProps" />
            <TextSubtitle v-if="textSubtitle && textSubtitleProps" v-bind="textSubtitleProps" />
          </Frame>
          <Button v-if="buttonProps !== null" v-bind="buttonProps">
            <Icon v-if="iconProps !== null" v-bind="iconProps" />
            <TextLabel v-if="textLabel && textLabelProps" v-bind="textLabelProps" />
          </Button>
        </Item>
        <Item v-if="item2Props !== null" v-bind="item2Props">
          <InputCheckbox v-if="inputCheckbox2 && inputCheckbox2Props" v-bind="inputCheckbox2Props" />
          <Frame v-bind="frame2Props" v-if="frame2">
            <TextTitle v-if="textTitle2 && textTitle2Props" v-bind="textTitle2Props" />
            <TextSubtitle v-if="textSubtitle2 && textSubtitle2Props" v-bind="textSubtitle2Props" />
          </Frame>
          <Button v-if="button2Props !== null" v-bind="button2Props">
            <Icon v-if="icon2Props !== null" v-bind="icon2Props" />
            <TextLabel v-if="textLabel2 && textLabel2Props" v-bind="textLabel2Props" />
          </Button>
        </Item>
        <Item v-if="item3Props !== null" v-bind="item3Props">
          <InputCheckbox v-if="inputCheckbox3 && inputCheckbox3Props" v-bind="inputCheckbox3Props" />
          <Frame v-bind="frame3Props" v-if="frame3">
            <TextTitle v-if="textTitle3 && textTitle3Props" v-bind="textTitle3Props" />
            <TextSubtitle v-if="textSubtitle3 && textSubtitle3Props" v-bind="textSubtitle3Props" />
          </Frame>
          <Button v-if="button3Props !== null" v-bind="button3Props">
            <Icon v-if="icon3Props !== null" v-bind="icon3Props" />
            <TextLabel v-if="textLabel3 && textLabel3Props" v-bind="textLabel3Props" />
          </Button>
        </Item>
      </slot>
    </ul>
</template>
