// packages/editor/apps/vue/seldon/frames/Container.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/**
 * Container: Container
 * Level: Frame
 * Intent: Grid container schema used to arrange children in a CSS grid with a configurable number of columns and rows. Use it instead of Frame when children should align to a shared grid; Frame remains the flexbox container.
 * Tags: container, layout, grid, ui, box, content, sizing
 * Type: Default
 *
 * @example
 * ```vue
 * <Container
 *   wrapperElement="div"
 *   aria-hidden="false"
 * />
 * ```
 */
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"
import { combineClassNames } from "../utils/class-names"

const props = defineProps<{
  className?: string
  wrapperElement?: unknown
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "wrapperElement": "div",
  "aria-hidden": "false"
}

const rootClassName = computed(() => combineClassNames("sdn-container", props.className))
const rootAttrs = { "aria-hidden": sdn["aria-hidden"] }
</script>

<template>
    <component :is="(props.wrapperElement as string) ?? sdn.wrapperElement ?? 'div'" :class="rootClassName" v-bind="rootAttrs"><slot></slot></component>
</template>

// packages/editor/apps/react/sdn/frames/Container.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

import { HTMLAttributes } from "react"

import { HTMLArticle } from "../native-react/HTML.Article"
import { HTMLAside } from "../native-react/HTML.Aside"
import { HTMLBlockquote } from "../native-react/HTML.Blockquote"
import { HTMLDiv } from "../native-react/HTML.Div"
import { HTMLFieldset } from "../native-react/HTML.Fieldset"
import { HTMLFigure } from "../native-react/HTML.Figure"
import { HTMLFooter } from "../native-react/HTML.Footer"
import { HTMLForm } from "../native-react/HTML.Form"
import { HTMLHeader } from "../native-react/HTML.Header"
import { HTMLLi } from "../native-react/HTML.Li"
import { HTMLMain } from "../native-react/HTML.Main"
import { HTMLMenu } from "../native-react/HTML.Menu"
import { HTMLNav } from "../native-react/HTML.Nav"
import { HTMLOl } from "../native-react/HTML.Ol"
import { HTMLSection } from "../native-react/HTML.Section"
import { HTMLTable } from "../native-react/HTML.Table"
import { HTMLTbody } from "../native-react/HTML.Tbody"
import { HTMLTfoot } from "../native-react/HTML.Tfoot"
import { HTMLThead } from "../native-react/HTML.Thead"
import { HTMLTr } from "../native-react/HTML.Tr"
import { HTMLUl } from "../native-react/HTML.Ul"
import { combineClassNames } from "../utils/class-name"

export interface ContainerProps extends HTMLAttributes<
  | HTMLElement
  | HTMLElement
  | HTMLQuoteElement
  | HTMLElement
  | HTMLFieldSetElement
  | HTMLElement
  | HTMLElement
  | HTMLFormElement
  | HTMLElement
  | HTMLLIElement
  | HTMLElement
  | HTMLMenuElement
  | HTMLElement
  | HTMLOListElement
  | HTMLElement
  | HTMLTableElement
  | HTMLTableSectionElement
  | HTMLTableSectionElement
  | HTMLTableSectionElement
  | HTMLTableRowElement
  | HTMLUListElement
> {
  "data-seldon-ref"?: string
  wrapperElement?:
    | "div"
    | "section"
    | "article"
    | "aside"
    | "main"
    | "nav"
    | "header"
    | "footer"
    | "ul"
    | "ol"
    | "li"
    | "form"
    | "fieldset"
    | "figure"
    | "menu"
    | "blockquote"
    | "table"
    | "thead"
    | "tbody"
    | "tfoot"
    | "tr"
}

//
// Default property values
//
const sdn: ContainerProps = {
  wrapperElement: "div",
  "aria-hidden": "false",
}

/**
 * Container: Container
 * Level: Frame
 * Intent: Grid container schema used to arrange children in a CSS grid with a configurable number of columns and rows. Use it instead of Frame when children should align to a shared grid; Frame remains the flexbox container.
 * Tags: container, layout, grid, ui, box, content, sizing
 * Type: Default
 *
 * @example
 * ```tsx
 * <Container
 *   wrapperElement="div"
 *   aria-hidden="false"
 * />
 * ```
 */
export function Container({
  className = "",
  wrapperElement = sdn.wrapperElement,
  ...props
}: ContainerProps) {
  const containerClassName = combineClassNames("sdn-container", className)

  switch (wrapperElement) {
    case "section":
      return (
        <HTMLSection className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "article":
      return (
        <HTMLArticle className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "aside":
      return (
        <HTMLAside className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "main":
      return <HTMLMain className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    case "nav":
      return <HTMLNav className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    case "header":
      return (
        <HTMLHeader className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "footer":
      return (
        <HTMLFooter className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "ul":
      return <HTMLUl className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    case "ol":
      return <HTMLOl className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    case "li":
      return <HTMLLi className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    case "form":
      return <HTMLForm className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    case "fieldset":
      return (
        <HTMLFieldset className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "figure":
      return (
        <HTMLFigure className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "menu":
      return <HTMLMenu className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    case "blockquote":
      return (
        <HTMLBlockquote
          className={containerClassName}
          aria-hidden={sdn["aria-hidden"]}
          {...props}
        />
      )
    case "table":
      return (
        <HTMLTable className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "thead":
      return (
        <HTMLThead className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "tbody":
      return (
        <HTMLTbody className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "tfoot":
      return (
        <HTMLTfoot className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
      )
    case "tr":
      return <HTMLTr className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    default:
      return <HTMLDiv className={containerClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
  }
}
