// packages/editor-react/app/overlays/FocusRing.tsx
import { CSSProperties } from "react"
import { Frame } from "@seldon/components/frames/Frame"

interface FocusRingProps {
  style: CSSProperties
}

/** Fixed, top-most ring drawn around the focused element. Position and size arrive via style. */
export function FocusRing({ style }: FocusRingProps) {
  return (
    <Frame className="editor-focus-ring" style={style} aria-hidden="true" />
  )
}

// packages/editor-vue/app/overlays/FocusRing.vue
<script setup lang="ts">
import type { CSSProperties } from "vue"

/** Fixed, top-most ring drawn around the focused element. Position and size arrive via style. */
defineProps<{ style: CSSProperties }>()
</script>

<template>
  <div class="editor-focus-ring" :style="style" aria-hidden="true" />
</template>
