// packages/editor-react/app/sidebars/properties/PropertiesSidebar.tsx
import { MenuController, MenuEntry } from "@app/menus"
import { FramerExpandable } from "@app/sidebars/FramerExpandable.bespoke"
import { useAddToast } from "@app/toaster/hooks/use-add-toast"
import { useObjectProperties } from "@app/workspace/hooks/use-object-properties"
import { Frame } from "@seldon/components/frames/Frame"
import { SidebarProperties } from "@seldon/components/modules/SidebarProperties"
import {
  FontCollectionEditingContext,
  IconSetEditingContext,
  ThemeEditingContext,
} from "@seldon/editor/lib/properties/inspector/editing-contexts"
import { filterPropertySections } from "@seldon/editor/lib/properties/inspector/filter-property-sections"
import { PropertySection } from "@seldon/editor/lib/properties/inspector/get-property-sections"
import { ThemePropertySection } from "@seldon/editor/lib/properties/inspector/get-theme-property-sections"
import { getIconRowCategory } from "@seldon/editor/lib/properties/inspector/icon-set-properties-data"
import {
  FlatProperty,
  getAllowedBorderSides,
  getPropertiesSubjectId,
} from "@seldon/editor/lib/properties/inspector/properties-data"
import { getComponentKey } from "@seldon/editor/lib/workspace/workspace-accessors"
import { LayoutGroup } from "framer-motion"
import {
  Fragment,
  type MouseEvent as ReactMouseEvent,
  useCallback,
  useDeferredValue,
  useMemo,
  useRef,
  useState,
} from "react"

import {
  Board,
  Instance,
  type LayeredPaintKey,
  Theme,
  Variant,
  Workspace,
  getBorderSideOptions,
  getLayerAddOptions,
  isThemeCustomTokenSection,
} from "@seldon/core"
import { PropertyDisplayCategory } from "@seldon/core/properties/schemas"
import { isBoard } from "@seldon/core/workspace/helpers/components/is-board"

import { Category } from "./Category"
import { CssBlock } from "./CssBlock"
import { Property } from "./Property"
import { useBoardStateMenu } from "./hooks/use-board-state-menu"
import {
  useBorderSideVisibility,
  useRevealedBorderSides,
} from "./hooks/use-border-side-visibility"
import { useFilterInput } from "./hooks/use-filter-input"
import { useLayerDragMonitor } from "./hooks/use-layer-drag-monitor"
import { usePropertiesSidebar } from "./hooks/use-properties-sidebar"
import { PropertyEditNavigationProvider } from "./hooks/use-property-edit-navigation"
import { useIsCategoryExpanded } from "./hooks/use-property-expansion"

const PROPERTIES_TREE_GAP = "var(--sdn-gaps-tight)"

export interface PropertyTreeProps {
  workspace: Workspace
  node: Variant | Instance | Board
  theme?: Theme
  themeEditingContext?: ThemeEditingContext | null
  fontCollectionEditingContext?: FontCollectionEditingContext | null
  iconSetEditingContext?: IconSetEditingContext | null
  /**
   * Families rows for the Families section, when provided. Holds parent family
   * rows and their child variant and license rows in one flat list.
   */
  familyProperties?: FlatProperty[]
  /**
   * Icon rows for the per-category icon set sections, when provided. Holds
   * parent subcategory rows and their child icon rows in one flat list.
   */
  iconProperties?: FlatProperty[]
  sections: Array<PropertySection | ThemePropertySection>
  allProperties: FlatProperty[]
  cssStrings: string[]
  cssSelector: string | null
}

/**
 * View-model for the properties sidebar. Renders the no-selection shell or
 * the property tree for the current selection.
 */
export function PropertiesSidebar() {
  const state = usePropertiesSidebar()
  const filter = useFilterInput()

  // Selecting a node rebuilds and remounts the whole inspector, which is heavy
  // enough to block the triggering click. Render the tree from a deferred copy
  // of the state so the click commits immediately and the new inspector fills
  // in at transition priority. While a row is being edited the live value comes
  // from the control's own input state, so a one-frame-late tree update is not
  // visible. This works for the external selection store, where startTransition
  // would not.
  const deferredState = useDeferredValue(state)

  // Live-filter the rendered rows by label or current value. The lookup table
  // (`allProperties`) stays full so a matched compound or shorthand parent can
  // still resolve its child rows.
  const sections = useMemo(
    () =>
      deferredState.kind === "tree"
        ? filterPropertySections(deferredState.treeProps.sections, filter.query)
        : [],
    [deferredState, filter.query],
  )

  // The header State menu selects the active interaction state for the selected
  // node's board tree. Its trigger is the generated `menuState` ButtonMenu; the
  // dropdown anchors to it through the shared MenuController.
  const stateMenu = useBoardStateMenu()
  const [stateMenuOpen, setStateMenuOpen] = useState(false)
  const stateMenuAnchor = useRef<HTMLElement | null>(null)
  const openStateMenu = useCallback(
    (event: ReactMouseEvent<HTMLButtonElement>) => {
      stateMenuAnchor.current = event.currentTarget
      setStateMenuOpen((open) => !open)
    },
    [],
  )
  const closeStateMenu = useCallback(() => setStateMenuOpen(false), [])

  const menuStateSlot = {
    onClick: openStateMenu,
    disabled: stateMenu.disabled,
    "data-testid": "board-state-trigger",
  }
  const stateLabelSlot = { children: stateMenu.label }
  const stateMenuController = (
    <MenuController
      open={stateMenuOpen}
      anchorRef={stateMenuAnchor}
      onClose={closeStateMenu}
      items={stateMenu.items}
      align="end"
    />
  )

  if (deferredState.kind === "empty") {
    return (
      <>
        <SidebarProperties
          data-testid="properties-sidebar"
          comboboxFieldFilter={filter.comboboxField}
          input={filter.input}
          buttonIconic={filter.buttonIconic}
          buttonMenu={menuStateSlot}
          textLabel={stateLabelSlot}
          style={styles.sidebar}
        />
        {stateMenuController}
      </>
    )
  }

  const seldonRefs = {
    propertiesContainer: {
      style: styles.frame,
      children: (
        <PropertiesTree {...deferredState.treeProps} sections={sections} />
      ),
    },
  }

  return (
    <>
      <SidebarProperties
        data-testid="properties-sidebar"
        comboboxFieldFilter={filter.comboboxField}
        input={filter.input}
        buttonIconic={filter.buttonIconic}
        buttonMenu={menuStateSlot}
        textLabel={stateLabelSlot}
        seldonRefs={seldonRefs}
        style={styles.sidebar}
      />
      {stateMenuController}
    </>
  )
}

/**
 * Orchestrates rendering of property sections and properties in a tree
 * structure. Groups properties into sections and handles expansion state.
 */
function PropertiesTree({
  workspace,
  node,
  theme,
  themeEditingContext,
  fontCollectionEditingContext,
  iconSetEditingContext,
  familyProperties,
  iconProperties,
  sections,
  allProperties,
  cssStrings,
  cssSelector,
}: PropertyTreeProps) {
  useLayerDragMonitor()

  const sectionNodes = sections.map((section) => (
    <TreeSection
      key={section.category}
      section={section}
      workspace={workspace}
      node={node}
      theme={theme}
      cssStrings={cssStrings}
      cssSelector={cssSelector}
      allProperties={allProperties}
      familyProperties={familyProperties}
      iconProperties={iconProperties}
      themeEditingContext={themeEditingContext}
      fontCollectionEditingContext={fontCollectionEditingContext}
      iconSetEditingContext={iconSetEditingContext}
    />
  ))

  return (
    <Frame style={styles.scroller}>
      <Frame style={styles.tree}>
        <PropertyEditNavigationProvider>
          <LayoutGroup>{sectionNodes}</LayoutGroup>
        </PropertyEditNavigationProvider>
      </Frame>
    </Frame>
  )
}

interface TreeSectionProps {
  section: PropertySection | ThemePropertySection
  workspace: Workspace
  node: Variant | Instance | Board
  theme?: Theme
  cssStrings: string[]
  cssSelector: string | null
  allProperties: FlatProperty[]
  familyProperties?: FlatProperty[]
  iconProperties?: FlatProperty[]
  themeEditingContext?: ThemeEditingContext | null
  fontCollectionEditingContext?: FontCollectionEditingContext | null
  iconSetEditingContext?: IconSetEditingContext | null
}

/**
 * Renders one property section: its category header and the expandable body.
 * Resolves the row-level `allProperties` and editing contexts once for the
 * section so the row map stays a plain iteration.
 */
function TreeSection({
  section,
  workspace,
  node,
  theme,
  cssStrings,
  cssSelector,
  allProperties,
  familyProperties,
  iconProperties,
  themeEditingContext,
  fontCollectionEditingContext,
  iconSetEditingContext,
}: TreeSectionProps) {
  const isExpanded = useIsCategoryExpanded(section.category)
  const isFamilies = section.category === "families"
  const isIconCategory =
    !!iconProperties && getIconRowCategory(`icon.${section.category}`) !== null

  const rowAllProperties =
    isFamilies && familyProperties
      ? familyProperties
      : isIconCategory && iconProperties
        ? iconProperties
        : allProperties
  const rowFontCollectionContext = isFamilies
    ? fontCollectionEditingContext
    : null
  const rowIconSetContext = isIconCategory ? iconSetEditingContext : null

  const addToast = useAddToast()
  const handleCopyCss = useCallback(async () => {
    const cssText = cssStrings.join("\n")
    try {
      await navigator.clipboard.writeText(cssText)
      addToast("CSS copied to clipboard")
    } catch (error) {
      console.error("Failed to copy to clipboard:", error)
    }
  }, [cssStrings, addToast])

  const handleCopySelector = useCallback(async () => {
    if (!cssSelector) return
    const indentedDeclarations = cssStrings
      .map((declaration) => `  ${declaration}`)
      .join("\n")
    const ruleText = `${cssSelector} {\n${indentedDeclarations}\n}`
    try {
      await navigator.clipboard.writeText(ruleText)
      addToast("Selector copied to clipboard")
    } catch (error) {
      console.error("Failed to copy to clipboard:", error)
    }
  }, [cssSelector, cssStrings, addToast])

  // Theme variants can add a custom token to any custom-capable section. The
  // "+" button shows only in theme editing on a variant, never on `core`.
  const onAddCustom = useMemo<(() => void) | undefined>(() => {
    if (!themeEditingContext?.isThemeEditing) return undefined
    if (!themeEditingContext.canAddCustom) return undefined
    if (!isThemeCustomTokenSection(section.category)) return undefined
    const themeSection = section.category
    return () => themeEditingContext.addCustomToken(themeSection)
  }, [themeEditingContext, section.category])

  const { addNodeLayer, applyBoardPropertiesToAllBoards, resetComponentBoard } =
    useObjectProperties()
  const { toggleBorderSide } = useBorderSideVisibility()
  const borderSubjectId = getPropertiesSubjectId(node)
  const shownBorderSides = useRevealedBorderSides(borderSubjectId)

  // A board's header section (the attributes category) carries the board-level
  // commands: pushing this board's setup (properties and theme) onto every
  // other component board, and resetting the board back to its defaults. Both
  // are single workspace actions, so an AI agent fires the same mutations.
  const boardActions = useMemo<MenuEntry[]>(() => {
    if (!isBoard(node)) return []
    if (section.category !== PropertyDisplayCategory.ATTRIBUTES) return []

    const boardKey = getComponentKey(node)
    return [
      {
        id: "apply-to-all-boards",
        label: "Apply to All Boards",
        onSelect: () => {
          const confirmed = window.confirm(
            "Apply this board's properties and theme to all other component boards? This overwrites their board setup.",
          )
          if (!confirmed) return
          applyBoardPropertiesToAllBoards({ sourceBoardKey: boardKey })
        },
        testId: "board-apply-to-all",
      },
      "separator",
      {
        id: "reset-board",
        label: "Reset Board",
        onSelect: () => {
          const confirmed = window.confirm(
            "Reset this board's properties and theme to their defaults?",
          )
          if (!confirmed) return
          resetComponentBoard({ boardKey })
        },
        testId: "board-reset",
      },
    ]
  }, [
    node,
    section.category,
    applyBoardPropertiesToAllBoards,
    resetComponentBoard,
  ])

  // A component node can stack extra paint layers. Offer "Add Background/Gradient/
  // Shadow" on the category that owns each exposed layered property.
  const layerAddActions = useMemo<MenuEntry[]>(() => {
    const inEditingMode =
      !!themeEditingContext?.isThemeEditing ||
      !!fontCollectionEditingContext?.isFontCollectionEditing ||
      !!iconSetEditingContext?.isIconSetEditing
    if (inEditingMode || isBoard(node)) return []

    const layeredKeys: LayeredPaintKey[] = ["background", "shadow"]
    const exposedKeys = layeredKeys.filter((key) =>
      section.properties.some(
        (property) => property.key === key && property.status !== "not used",
      ),
    )

    // Core decides each layered property's add options (Background splits into
    // typed Color/Image/Gradient seeds; others add a single empty layer).
    const entries: MenuEntry[] = []
    for (const key of exposedKeys) {
      for (const option of getLayerAddOptions(key)) {
        if (option.separatorBefore && entries.length > 0) {
          entries.push("separator")
        }
        entries.push({
          id: option.id,
          label: option.label,
          onSelect: () => addNodeLayer(key, option.seed),
          testId: option.id,
        })
      }
    }
    return entries
  }, [
    node,
    section.properties,
    themeEditingContext,
    fontCollectionEditingContext,
    iconSetEditingContext,
    addNodeLayer,
  ])

  // The appearance section (the one that owns the `border` row) can show or hide
  // each border side row. Each entry toggles visibility only; it writes nothing
  // to the node. Sides the schema does not expose render dimmed and inert.
  const borderSideActions = useMemo<MenuEntry[]>(() => {
    const inEditingMode =
      !!themeEditingContext?.isThemeEditing ||
      !!fontCollectionEditingContext?.isFontCollectionEditing ||
      !!iconSetEditingContext?.isIconSetEditing
    if (inEditingMode || isBoard(node)) return []

    const hasBorderRow = section.properties.some(
      (property) => property.key === "border",
    )
    if (!hasBorderRow) return []

    const allowed = new Set(getAllowedBorderSides(node, workspace))
    return getBorderSideOptions().map((option) => {
      const isAllowed = allowed.has(option.side)
      const isShown = shownBorderSides.has(option.side)
      return {
        id: option.id,
        label: `${isShown ? "Hide" : "Show"} ${option.label}`,
        disabled: !isAllowed,
        onSelect: isAllowed
          ? () => toggleBorderSide(borderSubjectId, option.side)
          : undefined,
        testId: option.id,
      }
    })
  }, [
    node,
    workspace,
    section.properties,
    shownBorderSides,
    borderSubjectId,
    toggleBorderSide,
    themeEditingContext,
    fontCollectionEditingContext,
    iconSetEditingContext,
  ])

  const sectionActions = useMemo((): MenuEntry[] | undefined => {
    if (boardActions.length > 0) return boardActions
    if (section.category === "css" && cssStrings.length > 0) {
      const actions: MenuEntry[] = [
        {
          id: "copy-css",
          label: "Copy CSS",
          onSelect: () => {
            void handleCopyCss()
          },
          testId: "copy-css",
        },
      ]
      if (cssSelector) {
        actions.push({
          id: "copy-selector",
          label: "Copy Selector",
          onSelect: () => {
            void handleCopySelector()
          },
          testId: "copy-selector",
        })
      }
      return actions
    }
    const appearanceActions: MenuEntry[] =
      layerAddActions.length > 0 && borderSideActions.length > 0
        ? [...layerAddActions, "separator", ...borderSideActions]
        : [...layerAddActions, ...borderSideActions]
    return appearanceActions.length > 0 ? appearanceActions : undefined
  }, [
    section.category,
    cssStrings.length,
    cssSelector,
    handleCopyCss,
    handleCopySelector,
    boardActions,
    layerAddActions,
    borderSideActions,
  ])

  const content =
    section.category === "css" ? (
      <CssBlock cssProperties={cssStrings} />
    ) : (
      section.properties.map((property) => (
        <Property
          key={property.key}
          property={property}
          workspace={workspace}
          node={node}
          theme={theme}
          allProperties={rowAllProperties}
          themeEditingContext={themeEditingContext}
          fontCollectionEditingContext={rowFontCollectionContext}
          iconSetEditingContext={rowIconSetContext}
        />
      ))
    )

  return (
    <Fragment>
      <Category
        section={section}
        actions={sectionActions}
        onAddCustom={onAddCustom}
      />
      <FramerExpandable isExpanded={isExpanded}>{content}</FramerExpandable>
    </Fragment>
  )
}

const styles = {
  sidebar: {
    height: "100%",
    minHeight: 0,
  },
  frame: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
  },
  scroller: {
    flex: 1,
    minHeight: 0,
    overflowX: "hidden" as const,
    overflowY: "auto" as const,
  },
  tree: {
    padding: "var(--sdn-paddings-tight) 0 var(--sdn-paddings-cozy) 0",
    display: "flex",
    flexDirection: "column" as const,
    gap: PROPERTIES_TREE_GAP,
  },
}

// packages/editor-vue/app/sidebars/properties/PropertiesSidebar.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import type { Workspace } from "@seldon/core"
import { isThemeCustomTokenSection } from "@seldon/core"
import { filterPropertySections } from "@seldon/editor/lib/properties/inspector/filter-property-sections"
import { getIconRowCategory } from "@seldon/editor/lib/properties/inspector/icon-set-properties-data"
import { getPropertiesSubjectId } from "@seldon/editor/lib/properties/inspector/properties-data"
import type { FlatProperty } from "@seldon/editor/lib/properties/inspector/properties-data"
import type {
  FontCollectionEditingContext,
  IconSetEditingContext,
} from "@seldon/editor/lib/properties/inspector/editing-contexts"
import SidebarProperties from "@seldon/components/modules/SidebarProperties.vue"
import Frame from "@seldon/components/frames/Frame.vue"
import MenuController from "@app/menus/MenuController.vue"
import type { MenuEntry } from "@app/menus/types"
import { useDispatch } from "@app/workspace/use-dispatch"
import { useToastStore } from "@app/toaster/toast-store"
import Category from "./Category.vue"
import Property from "./Property.vue"
import CssBlock from "./CssBlock.vue"
import { buildSectionActions } from "./helpers/build-section-actions"
import { useBoardStateMenu } from "./hooks/use-board-state-menu"
import { useBorderSideVisibilityStore } from "./hooks/use-border-side-visibility"
import { useFilterInput } from "./hooks/use-filter-input"
import { usePropertiesSidebar } from "./hooks/use-properties-sidebar"
import { providePropertyEditNavigation } from "./use-property-edit-navigation"
import type { PropertySection } from "./types"

defineProps<{ workspace?: Workspace }>()

providePropertyEditNavigation()

const state = usePropertiesSidebar()
const filter = useFilterInput()
const stateMenu = useBoardStateMenu()
const dispatch = useDispatch()
const toast = useToastStore()
const borderSides = useBorderSideVisibilityStore()

const tree = computed(() =>
  state.value.kind === "tree" ? state.value.tree : null,
)
const isEmpty = computed(() => state.value.kind === "empty")

const filteredSections = computed<PropertySection[]>(() =>
  tree.value ? filterPropertySections(tree.value.sections, filter.query.value) : [],
)

// ---- Header State menu ----
const stateMenuOpen = ref(false)
const stateMenuAnchor = ref<HTMLElement | null>(null)
function openStateMenu(event: MouseEvent): void {
  stateMenuAnchor.value = event.currentTarget as HTMLElement
  stateMenuOpen.value = !stateMenuOpen.value
}
function closeStateMenu(): void {
  stateMenuOpen.value = false
}
const menuStateSlot = computed(() => ({
  onClick: openStateMenu,
  disabled: stateMenu.value.disabled,
  "data-testid": "board-state-trigger",
}))
const stateLabelSlot = computed(() => ({ children: stateMenu.value.label }))

// ---- Per-section helpers ----
function isCssSection(section: PropertySection): boolean {
  return section.category === "css"
}
function isFamiliesSection(section: PropertySection): boolean {
  return section.category === "families"
}
function isIconCategorySection(section: PropertySection): boolean {
  return (
    Boolean(tree.value?.iconProperties) &&
    getIconRowCategory(`icon.${section.category}`) !== null
  )
}

function rowAllProperties(section: PropertySection): FlatProperty[] {
  const current = tree.value
  if (!current) return []
  if (isFamiliesSection(section) && current.familyProperties) {
    return current.familyProperties
  }
  if (isIconCategorySection(section) && current.iconProperties) {
    return current.iconProperties
  }
  return current.allProperties
}
function rowFontContext(
  section: PropertySection,
): FontCollectionEditingContext | null {
  return isFamiliesSection(section)
    ? (tree.value?.fontCollectionEditingContext ?? null)
    : null
}
function rowIconContext(
  section: PropertySection,
): IconSetEditingContext | null {
  return isIconCategorySection(section)
    ? (tree.value?.iconSetEditingContext ?? null)
    : null
}

function sectionActions(section: PropertySection): MenuEntry[] | undefined {
  const current = tree.value
  if (!current) return undefined
  const inEditingContext =
    Boolean(current.themeEditingContext?.isThemeEditing) ||
    Boolean(current.fontCollectionEditingContext?.isFontCollectionEditing) ||
    Boolean(current.iconSetEditingContext?.isIconSetEditing)
  return buildSectionActions({
    section,
    node: current.node,
    workspace: current.workspace,
    cssStrings: current.cssStrings,
    cssSelector: current.cssSelector,
    inEditingContext,
    shownBorderSides: borderSides.revealed(getPropertiesSubjectId(current.node)),
    toggleBorderSide: (subjectId, side) =>
      borderSides.toggle(subjectId, side),
    dispatch: (action) => dispatch(action as never),
    addToast: toast.addToast,
  })
}

function sectionAddCustom(section: PropertySection): (() => void) | undefined {
  const themeCtx = tree.value?.themeEditingContext
  if (!themeCtx?.isThemeEditing || !themeCtx.canAddCustom) return undefined
  if (!isThemeCustomTokenSection(section.category)) return undefined
  const target = section.category
  return () => themeCtx.addCustomToken(target)
}
</script>

<template>
  <SidebarProperties
    class="properties-sidebar"
    data-testid="properties-sidebar"
    :combobox-field-filter="filter.comboboxField.value"
    :input="filter.input.value"
    :button-iconic="filter.buttonIconic.value"
    :button-menu="menuStateSlot"
    :text-label="stateLabelSlot"
    :frame2="{}"
  >
    <template v-if="!isEmpty" #properties>
      <Frame class="properties-sidebar__scroll">
        <Frame class="properties-sidebar__tree">
          <template v-for="section in filteredSections" :key="section.category">
            <Category
              :section="section"
              :actions="sectionActions(section)"
              :on-add-custom="sectionAddCustom(section)"
            />
            <CssBlock
              v-if="isCssSection(section)"
              :css-properties="tree!.cssStrings"
            />
            <template v-else>
              <Property
                v-for="property in section.properties"
                :key="property.key"
                :property="property"
                :workspace="tree!.workspace"
                :node="tree!.node"
                :theme="tree!.theme"
                :all-properties="rowAllProperties(section)"
                :theme-editing-context="tree!.themeEditingContext"
                :font-collection-editing-context="rowFontContext(section)"
                :icon-set-editing-context="rowIconContext(section)"
              />
            </template>
          </template>
        </Frame>
      </Frame>
    </template>
  </SidebarProperties>

  <MenuController
    :open="stateMenuOpen"
    :anchor="stateMenuAnchor"
    :items="stateMenu.items"
    align="end"
    @close="closeStateMenu"
  />
</template>

<style scoped>
.properties-sidebar {
  width: 300px;
  height: 100%;
  min-height: 0;
  display: flex;
  flex-direction: column;
}
.properties-sidebar__scroll {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  overflow-x: hidden;
  display: flex;
  flex-direction: column;
}
.properties-sidebar__tree {
  padding: var(--sdn-paddings-tight) 0 var(--sdn-paddings-cozy) 0;
  display: flex;
  flex-direction: column;
  gap: var(--sdn-gaps-tight);
}
</style>
