// packages/editor/apps/vue/app/topbar/TopbarController.vue
<script setup lang="ts">
import { useEditorConfigStore } from "@app/editor/editor-config-store"
import { useAppState } from "@app/editor/use-app-state"
import { useExportStatusStore } from "@app/io/export-status-store"
import MenuController from "@app/menus/MenuController.vue"
import BarTopbar from "@seldon/components/parts/BarTopbar.vue"
import { storeToRefs } from "pinia"
import { computed, ref } from "vue"

import { getChromeThemes } from "./chrome-themes"
import { useMenuConfig } from "./hooks/use-menu-config"
import { useTopbarGradientAnimation } from "./hooks/use-topbar-gradient-animation"
import { TOPBAR_GRADIENT_CLASS } from "./seldon-gradient"

import type { MenuDropdown } from "./menus/types"
import type { InterfaceMode } from "@app/editor/editor-config-store"
import type { AppState } from "@app/editor/use-app-state"
import type { MenuAlign, MenuEntry } from "@app/menus/types"

/** Menu id for the chrome-theme dropdown, distinct from the config menus. */
const CHROME_THEME_MENU_ID = "chrome-theme"

/** Menu id for the interface light/dark mode dropdown. */
const INTERFACE_MODE_MENU_ID = "interface-mode"

/** Interface mode options, in menu order. */
const INTERFACE_MODES: { id: InterfaceMode; label: string }[] = [
  { id: "system", label: "System" },
  { id: "light", label: "Light" },
  { id: "dark", label: "Dark" },
]

type SlotObject = Record<string, unknown> | null
interface MenuSlot {
  button: SlotObject
  label: SlotObject
}
const EMPTY_SLOT: MenuSlot = { button: null, label: null }

const menuConfig = useMenuConfig()
const { appState } = useAppState()
const config = useEditorConfigStore()
const { chromeTheme, interfaceMode } = storeToRefs(config)
const exportStatus = useExportStatusStore()

const chromeThemes = getChromeThemes()

const openMenuId = ref<string | null>(null)
const anchor = ref<HTMLElement | null>(null)
const header = ref<HTMLElement | null>(null)

const gradientRef = useTopbarGradientAnimation()

function closeMenu(): void {
  openMenuId.value = null
}

function handleTriggerClick(id: string, element: HTMLElement): void {
  anchor.value = element
  openMenuId.value = openMenuId.value === id ? null : id
}

function handleTriggerEnter(id: string, element: HTMLElement): void {
  if (openMenuId.value === null) return
  anchor.value = element
  openMenuId.value = id
}

// Alt+Shift+click anywhere on the logo frame (cube + wordmark) toggles the
// export rainbow, a hidden gesture for previewing the animation without running
// an export. A plain click is inert.
function handleLogoClick(event: MouseEvent): void {
  if (!event.altKey || !event.shiftKey) return
  exportStatus.setExporting(!exportStatus.isExporting)
}

/**
 * Maps a topbar menu's items into the `MenuEntry` list the floating
 * `MenuController` consumes, dropping items hidden in the current app state.
 */
function toMenuEntries(menu: MenuDropdown, state: AppState): MenuEntry[] {
  return menu.items.flatMap<MenuEntry>((item) => {
    if (item === "separator") return ["separator"]
    if (item.visibleIn && !item.visibleIn.includes(state)) return []
    return [
      {
        id: item.id,
        label: item.label,
        onSelect: item.action,
        disabled: item.disabled ?? item.enabled === false,
        active: item.active,
        activeMarker: item.activeMarker,
        shortcut: item.shortcut,
        icon: item.icon,
        testId: `menu-item-${item.id}`,
      },
    ]
  })
}

/** Builds a right-side dropdown's `MenuEntry` list, marking the active option. */
function buildDropdownItems<T extends string>(
  options: { id: T; label: string }[],
  activeId: T,
  onSelect: (id: T) => void,
  testIdPrefix: string,
): MenuEntry[] {
  return options.map((option) => ({
    id: option.id,
    label: option.label,
    onSelect: () => onSelect(option.id),
    active: option.id === activeId,
    activeMarker: option.id === activeId ? "bullet" : undefined,
    testId: `${testIdPrefix}-${option.id}`,
  }))
}

const menuSlots = computed<MenuSlot[]>(() =>
  [0, 1, 2, 3, 4, 5].map((index) => {
    const menu = menuConfig.value[index]
    if (!menu) return EMPTY_SLOT
    if (menu.visibleIn && !menu.visibleIn.includes(appState.value)) return EMPTY_SLOT
    return {
      button: {
        "data-testid": `menu-${menu.id}`,
        "aria-haspopup": "menu",
        "aria-expanded": openMenuId.value === menu.id,
        onClick: (event: MouseEvent) =>
          handleTriggerClick(menu.id, event.currentTarget as HTMLElement),
        onPointerenter: (event: PointerEvent) =>
          handleTriggerEnter(menu.id, event.currentTarget as HTMLElement),
      },
      label: { children: menu.label },
    }
  }),
)

const themeMenuItems = computed<MenuEntry[]>(() =>
  buildDropdownItems(
    chromeThemes.map((theme) => ({ id: theme.slug, label: theme.label })),
    chromeTheme.value,
    config.setChromeTheme,
    CHROME_THEME_MENU_ID,
  ),
)

const activeThemeLabel = computed(() => {
  const active = chromeThemes.find((theme) => theme.slug === chromeTheme.value)
  return active?.label ?? chromeTheme.value
})

const themeButton = computed<SlotObject>(() => ({
  "data-testid": `menu-${CHROME_THEME_MENU_ID}`,
  "aria-haspopup": "menu",
  "aria-expanded": openMenuId.value === CHROME_THEME_MENU_ID,
  onClick: (event: MouseEvent) =>
    handleTriggerClick(CHROME_THEME_MENU_ID, event.currentTarget as HTMLElement),
}))

const themeLabel = computed<SlotObject>(() => ({ children: activeThemeLabel.value }))

const modeMenuItems = computed<MenuEntry[]>(() =>
  buildDropdownItems(
    INTERFACE_MODES,
    interfaceMode.value,
    config.setInterfaceMode,
    INTERFACE_MODE_MENU_ID,
  ),
)

const activeModeLabel = computed(() => {
  const active = INTERFACE_MODES.find((mode) => mode.id === interfaceMode.value)
  return active?.label ?? "System"
})

const modeButton = computed<SlotObject>(() => ({
  "data-testid": `menu-${INTERFACE_MODE_MENU_ID}`,
  "aria-haspopup": "menu",
  "aria-expanded": openMenuId.value === INTERFACE_MODE_MENU_ID,
  onClick: (event: MouseEvent) =>
    handleTriggerClick(INTERFACE_MODE_MENU_ID, event.currentTarget as HTMLElement),
}))

const modeLabel = computed<SlotObject>(() => ({ children: activeModeLabel.value }))

const openMenuItems = computed<MenuEntry[]>(() => {
  if (openMenuId.value === CHROME_THEME_MENU_ID) return themeMenuItems.value
  if (openMenuId.value === INTERFACE_MODE_MENU_ID) return modeMenuItems.value
  const menu = menuConfig.value.find((entry) => entry.id === openMenuId.value)
  return menu ? toMenuEntries(menu, appState.value) : []
})

// The theme and mode triggers sit at the right edge, so their menus align to
// the trigger's right and open leftward. The left-side config menus align left.
const menuAlign = computed<MenuAlign>(() =>
  openMenuId.value === CHROME_THEME_MENU_ID || openMenuId.value === INTERFACE_MODE_MENU_ID
    ? "end"
    : "start",
)

const menuOpen = computed(() => openMenuId.value !== null)

const logoProps = { src: "/logo.svg", alt: "Seldon" }
const wordmarkProps = { src: "/wordmark-light.svg", alt: "Seldon" }
const emptySlot = {}

// Inject the gesture onto the generated `logo` frame that wraps both images.
const seldonRefs = { logo: { onClick: handleLogoClick } }
</script>

<template>
  <header ref="header" class="topbar-header">
    <BarTopbar
      data-testid="topbar"
      :seldon-refs="seldonRefs"
      :frame="emptySlot"
      :frame2="emptySlot"
      :image="logoProps"
      :image2="wordmarkProps"
      :frame3="emptySlot"
      :button-simple="menuSlots[0].button"
      :text-label="menuSlots[0].label"
      :button-simple2="menuSlots[1].button"
      :text-label2="menuSlots[1].label"
      :button-simple3="menuSlots[2].button"
      :text-label3="menuSlots[2].label"
      :button-simple4="menuSlots[3].button"
      :text-label4="menuSlots[3].label"
      :button-simple5="menuSlots[4].button"
      :text-label5="menuSlots[4].label"
      :button-simple6="menuSlots[5].button"
      :text-label6="menuSlots[5].label"
      :frame4="emptySlot"
      :button-menu="themeButton"
      :text-label7="themeLabel"
      :icon="emptySlot"
      :button-menu2="modeButton"
      :text-label8="modeLabel"
      :icon2="emptySlot"
    />
    <MenuController
      :open="menuOpen"
      :anchor="anchor"
      :items="openMenuItems"
      :align="menuAlign"
      min-width="220px"
      @close="closeMenu"
    />
    <div ref="gradientRef" :class="TOPBAR_GRADIENT_CLASS" />
  </header>
</template>

<style scoped>
.topbar-header {
  position: relative;
  z-index: 10;
  flex-shrink: 0;
}
</style>

// packages/editor-react/app/topbar/TopbarController.tsx
"use client"

import { getChromeThemes } from "./chrome-themes"
import { useExportStatusStore } from "@app/export/export-status-store"
import { MenuAlign, MenuController, MenuEntry } from "@app/menus"
import {
  CSSProperties,
  MouseEvent,
  PointerEvent,
  useCallback,
  useMemo,
  useRef,
  useState,
} from "react"
import { AppState, useAppState } from "@app/hooks/use-app-state"
import { InterfaceMode, useEditorConfig } from "@app/hooks/use-editor-config"
import { useMenuConfig } from "./hooks/use-menu-config"
import { useTopbarGradientAnimation } from "./hooks/use-topbar-gradient-animation"
import { ButtonMenuProps } from "@seldon/components/elements/ButtonMenu"
import { ButtonSimpleProps } from "@seldon/components/elements/ButtonSimple"
import { Frame } from "@seldon/components/frames/Frame"
import { BarTopbar } from "@seldon/components/parts/BarTopbar"
import { ImageProps } from "@seldon/components/primitives/Image"
import { TextLabelProps } from "@seldon/components/primitives/TextLabel"
import { MenuDropdown } from "./menus/types"
import { TOPBAR_GRADIENT_CLASS } from "./seldon-gradient"

/** Menu id for the chrome-theme dropdown, distinct from the config menus. */
const CHROME_THEME_MENU_ID = "chrome-theme"

/** Menu id for the interface light/dark mode dropdown. */
const INTERFACE_MODE_MENU_ID = "interface-mode"

/** Interface mode options, in menu order. */
const INTERFACE_MODES: { id: InterfaceMode; label: string }[] = [
  { id: "system", label: "System" },
  { id: "light", label: "Light" },
  { id: "dark", label: "Dark" },
]

/**
 * Builds the `MenuEntry` list for a right-side dropdown (chrome theme or mode),
 * marking the active option with a bullet.
 */
function buildDropdownItems<T extends string>(
  options: { id: T; label: string }[],
  activeId: T,
  onSelect: (id: T) => void,
  testIdPrefix: string,
): MenuEntry[] {
  return options.map((option) => ({
    id: option.id,
    label: option.label,
    onSelect: () => onSelect(option.id),
    active: option.id === activeId,
    activeMarker: option.id === activeId ? "bullet" : undefined,
    testId: `${testIdPrefix}-${option.id}`,
  }))
}

/** Builds a right-side dropdown trigger wired to open or close its menu. */
function buildMenuTrigger(
  menuId: string,
  openMenuId: string | null,
  onTriggerClick: (menuId: string, anchor: HTMLElement) => void,
): ButtonMenuProps {
  return {
    "data-testid": `menu-${menuId}`,
    "aria-haspopup": "menu",
    "aria-expanded": openMenuId === menuId,
    onClick: (event: MouseEvent<HTMLButtonElement>) =>
      onTriggerClick(menuId, event.currentTarget),
  } as ButtonMenuProps
}

/**
 * Maps a topbar menu's items into the framework-agnostic `MenuEntry` list the
 * floating `MenuController` consumes, dropping items hidden in the current app state.
 */
function toMenuEntries(menu: MenuDropdown, appState: AppState): MenuEntry[] {
  return menu.items.flatMap<MenuEntry>((item) => {
    if (item === "separator") return ["separator"]
    if (item.visibleIn && !item.visibleIn.includes(appState)) return []
    return [
      {
        id: item.id,
        label: item.label,
        onSelect: item.action,
        disabled: item.disabled ?? item.enabled === false,
        active: item.active,
        activeMarker: item.activeMarker,
        shortcut: item.shortcut,
        icon: item.icon,
        testId: `menu-item-${item.id}`,
      },
    ]
  })
}

interface MenuSlot {
  button: ButtonSimpleProps | null
  label: TextLabelProps | null
}

const EMPTY_SLOT: MenuSlot = { button: null, label: null }

/**
 * View-model for the topbar. Feeds the generated `BarTopbar` view: it injects
 * the logo/wordmark images and maps each menu from `useMenuConfig` onto a
 * `buttonSimple` trigger slot, then overlays a single controlled floating
 * `MenuController` anchored to whichever trigger is open. The right-side slots hold the
 * chrome-theme and interface-mode dropdowns, and the rainbow gradient strip is a
 * custom overlay because the view has no slot for it.
 */
export function TopbarController() {
  const menuConfig = useMenuConfig()
  const { appState } = useAppState()
  const { chromeTheme, setChromeTheme, interfaceMode, setInterfaceMode } =
    useEditorConfig()
  const chromeThemes = useMemo(() => getChromeThemes(), [])
  const [openMenuId, setOpenMenuId] = useState<string | null>(null)
  const anchorRef = useRef<HTMLElement | null>(null)

  const gradientRef = useTopbarGradientAnimation()

  // Alt+Shift+click anywhere on the logo frame (cube + wordmark) toggles the
  // export rainbow, a hidden gesture for previewing the animation without
  // running an export. A plain click is inert.
  const handleLogoClick = useCallback((event: MouseEvent<HTMLDivElement>) => {
    if (!event.altKey || !event.shiftKey) return
    const { isExporting, setExporting } = useExportStatusStore.getState()
    setExporting(!isExporting)
  }, [])

  // Inject the gesture onto the generated `logo` frame that wraps both images.
  const seldonRefs = useMemo(
    () => ({ logo: { onClick: handleLogoClick } }),
    [handleLogoClick],
  )

  const closeMenu = useCallback(() => setOpenMenuId(null), [])

  const handleTriggerClick = useCallback((id: string, el: HTMLElement) => {
    anchorRef.current = el
    setOpenMenuId((current) => (current === id ? null : id))
  }, [])

  const handleTriggerEnter = useCallback(
    (id: string, el: HTMLElement) => {
      if (openMenuId === null) return
      anchorRef.current = el
      setOpenMenuId(id)
    },
    [openMenuId],
  )

  const menuSlots = useMemo<MenuSlot[]>(() => {
    return [0, 1, 2, 3, 4, 5].map((index) => {
      const menu = menuConfig[index]
      if (!menu) return EMPTY_SLOT
      if (menu.visibleIn && !menu.visibleIn.includes(appState))
        return EMPTY_SLOT

      const button = {
        "data-testid": `menu-${menu.id}`,
        "aria-haspopup": "menu",
        "aria-expanded": openMenuId === menu.id,
        onClick: (event: MouseEvent<HTMLButtonElement>) =>
          handleTriggerClick(menu.id, event.currentTarget),
        onPointerEnter: (event: PointerEvent<HTMLButtonElement>) =>
          handleTriggerEnter(menu.id, event.currentTarget),
      } as ButtonSimpleProps
      return { button, label: { children: menu.label } }
    })
  }, [menuConfig, appState, openMenuId, handleTriggerClick, handleTriggerEnter])

  const themeMenuItems = useMemo<MenuEntry[]>(
    () =>
      buildDropdownItems(
        chromeThemes.map((theme) => ({ id: theme.slug, label: theme.label })),
        chromeTheme,
        setChromeTheme,
        CHROME_THEME_MENU_ID,
      ),
    [chromeThemes, chromeTheme, setChromeTheme],
  )

  const activeThemeLabel = useMemo(() => {
    const active = chromeThemes.find((theme) => theme.slug === chromeTheme)
    return active?.label ?? chromeTheme
  }, [chromeThemes, chromeTheme])

  const themeButton = useMemo<ButtonMenuProps>(
    () =>
      buildMenuTrigger(CHROME_THEME_MENU_ID, openMenuId, handleTriggerClick),
    [openMenuId, handleTriggerClick],
  )

  const themeLabel = useMemo<TextLabelProps>(
    () => ({ children: activeThemeLabel }),
    [activeThemeLabel],
  )

  const modeMenuItems = useMemo<MenuEntry[]>(
    () =>
      buildDropdownItems(
        INTERFACE_MODES,
        interfaceMode,
        setInterfaceMode,
        INTERFACE_MODE_MENU_ID,
      ),
    [interfaceMode, setInterfaceMode],
  )

  const activeModeLabel = useMemo(() => {
    const active = INTERFACE_MODES.find((mode) => mode.id === interfaceMode)
    return active?.label ?? "System"
  }, [interfaceMode])

  const modeButton = useMemo<ButtonMenuProps>(
    () =>
      buildMenuTrigger(INTERFACE_MODE_MENU_ID, openMenuId, handleTriggerClick),
    [openMenuId, handleTriggerClick],
  )

  const modeLabel = useMemo<TextLabelProps>(
    () => ({ children: activeModeLabel }),
    [activeModeLabel],
  )

  const openMenuItems = useMemo<MenuEntry[]>(() => {
    if (openMenuId === CHROME_THEME_MENU_ID) return themeMenuItems
    if (openMenuId === INTERFACE_MODE_MENU_ID) return modeMenuItems
    const menu = menuConfig.find((entry) => entry.id === openMenuId)
    return menu ? toMenuEntries(menu, appState) : []
  }, [menuConfig, openMenuId, appState, themeMenuItems, modeMenuItems])

  // The theme and mode triggers sit at the right edge, so their menus align to
  // the trigger's right and open leftward. The left-side config menus align to
  // their left.
  const menuAlign: MenuAlign =
    openMenuId === CHROME_THEME_MENU_ID || openMenuId === INTERFACE_MODE_MENU_ID
      ? "end"
      : "start"

  const menuKey = openMenuId ?? "closed"

  return (
    <Frame wrapperElement="header" style={styles.header}>
      <BarTopbar
        data-testid="topbar"
        seldonRefs={seldonRefs}
        image={logoProps}
        image2={wordmarkProps}
        buttonSimple={menuSlots[0].button}
        textLabel={menuSlots[0].label}
        buttonSimple2={menuSlots[1].button}
        textLabel2={menuSlots[1].label}
        buttonSimple3={menuSlots[2].button}
        textLabel3={menuSlots[2].label}
        buttonSimple4={menuSlots[3].button}
        textLabel4={menuSlots[3].label}
        buttonSimple5={menuSlots[4].button}
        textLabel5={menuSlots[4].label}
        buttonSimple6={menuSlots[5].button}
        textLabel6={menuSlots[5].label}
        buttonMenu={themeButton}
        textLabel7={themeLabel}
        buttonMenu2={modeButton}
        textLabel8={modeLabel}
      />
      <MenuController
        key={menuKey}
        open={openMenuId !== null}
        anchorRef={anchorRef}
        onClose={closeMenu}
        items={openMenuItems}
        align={menuAlign}
        minWidth="220px"
      />
      <Frame ref={gradientRef} className={TOPBAR_GRADIENT_CLASS} />
    </Frame>
  )
}

const logoProps: ImageProps = {
  src: "/logo.svg",
  alt: "Seldon",
}

const wordmarkProps: ImageProps = {
  src: "/wordmark-light.svg",
  alt: "Seldon",
}

const styles: Record<string, CSSProperties> = {
  header: {
    position: "relative",
    zIndex: 10,
    flexShrink: 0,
  },
}
