// packages/editor/apps/vue/app/dialogs/image-upload/ImagePreview.vue
<script setup lang="ts">
import type { CSSProperties } from "vue"
import Frame from "@seldon/components/frames/Frame.vue"
import Image from "@seldon/components/primitives/Image.vue"

withDefaults(defineProps<{ src: string; alt?: string }>(), { alt: "Preview" })
defineEmits<{ (event: "error"): void }>()

const wrapperStyle: CSSProperties = { position: "absolute", inset: "1rem" }
const imageStyle: CSSProperties = {
  width: "100%",
  height: "100%",
  objectFit: "contain",
}
</script>

<template>
  <Frame wrapperElement="div" :style="wrapperStyle">
    <Image
      :src="src"
      :alt="alt"
      :style="imageStyle"
      @error="$emit('error')"
    />
  </Frame>
</template>

// packages/editor/app/dialogs/image-upload/ImagePreview.tsx
import { CSSProperties } from "react"
import { Frame } from "@seldon/components/frames/Frame"
import { Image } from "@seldon/components/primitives/Image"

interface ImagePreviewProps {
  src: string
  alt?: string
  onError?: () => void
}

const wrapperStyle: CSSProperties = { position: "absolute", inset: "1rem" }
const imageStyle: CSSProperties = {
  width: "100%",
  height: "100%",
  objectFit: "contain",
}

/** Contained image preview that reports load failures through `onError`. */
export function ImagePreview({
  src,
  alt = "Preview",
  onError,
}: ImagePreviewProps) {
  return (
    <Frame wrapperElement="div" style={wrapperStyle}>
      <Image src={src} alt={alt} style={imageStyle} onError={onError} />
    </Frame>
  )
}
