// packages/editor-vue/seldon/elements/ButtonTools.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/*****
 * Button: Tools
 * Level: Element
 * Intent: Standard button for triggering actions like submit, confirm, or cancel.
 * Tags: button, action, UI, primary, click, control, submit, call to action
 * Type: Custom
 *
 * @example
 * ```vue
 * <ButtonTools
 *   button={() => {}}
 *   icon="material-star"
 *   textLabel="{}"
 *   button2={() => {}}
 *   button3={() => {}}
 * />
 * ```
 *****/
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"
import { combineClassNames, mergeSlot } from "../utils/class-names"
import Button from "../elements/Button.vue"
import Icon from "../primitives/Icon.vue"
import TextLabel from "../primitives/TextLabel.vue"

const props = defineProps<{
  className?: string
  button?: Record<string, unknown> | null
  icon?: Record<string, unknown> | null
  textLabel?: Record<string, unknown> | null
  button2?: Record<string, unknown> | null
  icon2?: Record<string, unknown> | null
  textLabel2?: Record<string, unknown> | null
  button3?: Record<string, unknown> | null
  icon3?: Record<string, unknown> | null
  textLabel3?: Record<string, unknown> | null
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "button": {
    "className": "sdn-button sdn-button--ivvu"
  },
  "icon": {
    "icon": "seldon-component",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--umgs"
  },
  "textLabel": {
    "className": "sdn-text-label sdn-text-label--7mza"
  },
  "button2": {
    "className": "sdn-button sdn-button--ivvu"
  },
  "icon2": {
    "icon": "seldon-component",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--umgs"
  },
  "textLabel2": {
    "className": "sdn-text-label sdn-text-label--7mza"
  },
  "button3": {
    "className": "sdn-button sdn-button--ivvu"
  },
  "icon3": {
    "icon": "seldon-component",
    "aria-hidden": "true",
    "className": "sdn-icon sdn-icon--umgs"
  },
  "textLabel3": {
    "className": "sdn-text-label sdn-text-label--7mza"
  }
}

const rootClassName = computed(() => combineClassNames("sdn-button-tools", props.className))
const buttonProps = computed(() => mergeSlot(sdn.button, props.button))
const iconProps = computed(() => mergeSlot(sdn.icon, props.icon))
const textLabelProps = computed(() => mergeSlot(sdn.textLabel, props.textLabel))
const button2Props = computed(() => mergeSlot(sdn.button2, props.button2))
const icon2Props = computed(() => mergeSlot(sdn.icon2, props.icon2))
const textLabel2Props = computed(() => mergeSlot(sdn.textLabel2, props.textLabel2))
const button3Props = computed(() => mergeSlot(sdn.button3, props.button3))
const icon3Props = computed(() => mergeSlot(sdn.icon3, props.icon3))
const textLabel3Props = computed(() => mergeSlot(sdn.textLabel3, props.textLabel3))
</script>

<template>
    <button :class="rootClassName">
      <slot>
        <Button v-if="buttonProps !== null" v-bind="buttonProps">
          <Icon v-if="iconProps !== null" v-bind="iconProps" />
          <TextLabel v-if="textLabel && textLabelProps" v-bind="textLabelProps" />
        </Button>
        <Button v-if="button2Props !== null" v-bind="button2Props">
          <Icon v-if="icon2Props !== null" v-bind="icon2Props" />
          <TextLabel v-if="textLabel2 && textLabel2Props" v-bind="textLabel2Props" />
        </Button>
        <Button v-if="button3Props !== null" v-bind="button3Props">
          <Icon v-if="icon3Props !== null" v-bind="icon3Props" />
          <TextLabel v-if="textLabel3 && textLabel3Props" v-bind="textLabel3Props" />
        </Button>
      </slot>
    </button>
</template>

// packages/editor-react/seldon/elements/ButtonTools.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/
import { ButtonHTMLAttributes, forwardRef } from "react"

import { Button, ButtonProps } from "../elements/Button"
import { HTMLButton } from "../native-react/HTML.Button"
import { Icon, IconProps } from "../primitives/Icon"
import { TextLabel, TextLabelProps } from "../primitives/TextLabel"
import { applyRef } from "../utils/apply-ref"
import { combineClassNames } from "../utils/class-name"

export interface ButtonToolsProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  className?: string
  "data-seldon-ref"?: string
  seldonRefs?: Record<string, Record<string, unknown>>
  button?: ButtonProps | null
  icon?: IconProps | null
  textLabel?: TextLabelProps | null
  button2?: ButtonProps | null
  icon2?: IconProps | null
  textLabel2?: TextLabelProps | null
  button3?: ButtonProps | null
  icon3?: IconProps | null
  textLabel3?: TextLabelProps | null
}

/*****
 * Button: Tools
 * Level: Element
 * Intent: Standard button for triggering actions like submit, confirm, or cancel.
 * Tags: button, action, UI, primary, click, control, submit, call to action
 * Type: Custom
 *
 * @example
 * ```tsx
 * <ButtonTools
 *   button={() => {}}
 *   icon="material-star"
 *   textLabel="{}"
 *   button2={() => {}}
 *   button3={() => {}}
 * />
 * ```
 *****/
export const ButtonTools = forwardRef<HTMLButtonElement, ButtonToolsProps>(
  function ButtonTools(
    {
      className = "",
      button = sdn.button,
      icon = sdn.icon,
      textLabel,
      button2 = sdn.button2,
      icon2 = sdn.icon2,
      textLabel2,
      button3 = sdn.button3,
      icon3 = sdn.icon3,
      textLabel3,
      children,
      seldonRefs,
      ...props
    },
    ref,
  ) {
    const buttonToolsClassName = combineClassNames(
      "sdn-button-tools",
      className,
    )
    const buttonProps = applyRef(
      seldonRefs,
      button === null
        ? null
        : {
            ...sdn.button,
            ...button,
            className: combineClassNames(
              sdn.button?.className,
              button?.className,
            ),
          },
    )
    const iconProps = applyRef(
      seldonRefs,
      icon === null
        ? null
        : {
            ...sdn.icon,
            ...icon,
            className: combineClassNames(sdn.icon?.className, icon?.className),
          },
    )
    const textLabelProps = applyRef(
      seldonRefs,
      textLabel === null
        ? null
        : {
            ...sdn.textLabel,
            ...textLabel,
            className: combineClassNames(
              sdn.textLabel?.className,
              textLabel?.className,
            ),
          },
    )
    const button2Props = applyRef(
      seldonRefs,
      button2 === null
        ? null
        : {
            ...sdn.button2,
            ...button2,
            className: combineClassNames(
              sdn.button2?.className,
              button2?.className,
            ),
          },
    )
    const icon2Props = applyRef(
      seldonRefs,
      icon2 === null
        ? null
        : {
            ...sdn.icon2,
            ...icon2,
            className: combineClassNames(
              sdn.icon2?.className,
              icon2?.className,
            ),
          },
    )
    const textLabel2Props = applyRef(
      seldonRefs,
      textLabel2 === null
        ? null
        : {
            ...sdn.textLabel2,
            ...textLabel2,
            className: combineClassNames(
              sdn.textLabel2?.className,
              textLabel2?.className,
            ),
          },
    )
    const button3Props = applyRef(
      seldonRefs,
      button3 === null
        ? null
        : {
            ...sdn.button3,
            ...button3,
            className: combineClassNames(
              sdn.button3?.className,
              button3?.className,
            ),
          },
    )
    const icon3Props = applyRef(
      seldonRefs,
      icon3 === null
        ? null
        : {
            ...sdn.icon3,
            ...icon3,
            className: combineClassNames(
              sdn.icon3?.className,
              icon3?.className,
            ),
          },
    )
    const textLabel3Props = applyRef(
      seldonRefs,
      textLabel3 === null
        ? null
        : {
            ...sdn.textLabel3,
            ...textLabel3,
            className: combineClassNames(
              sdn.textLabel3?.className,
              textLabel3?.className,
            ),
          },
    )

    return (
      <HTMLButton className={buttonToolsClassName} ref={ref} {...props}>
        {children !== undefined ? (
          children
        ) : (
          <>
            {buttonProps !== null && (
              <Button {...buttonProps}>
                {icon && iconProps && <Icon {...iconProps} />}
                {textLabel && textLabelProps && (
                  <TextLabel {...textLabelProps} />
                )}
              </Button>
            )}
            {button2Props !== null && (
              <Button {...button2Props}>
                {icon2 && icon2Props && <Icon {...icon2Props} />}
                {textLabel2 && textLabel2Props && (
                  <TextLabel {...textLabel2Props} />
                )}
              </Button>
            )}
            {button3Props !== null && (
              <Button {...button3Props}>
                {icon3 && icon3Props && <Icon {...icon3Props} />}
                {textLabel3 && textLabel3Props && (
                  <TextLabel {...textLabel3Props} />
                )}
              </Button>
            )}
          </>
        )}
      </HTMLButton>
    )
  },
)

//
// Default property values
//
const sdn: ButtonToolsProps = {
  button: {
    className: "sdn-button sdn-button--ivvu",
  },
  icon: {
    icon: "seldon-component",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--umgs",
  },
  textLabel: {
    className: "sdn-text-label sdn-text-label--7mza",
  },
  button2: {
    className: "sdn-button sdn-button--ivvu",
  },
  icon2: {
    icon: "seldon-component",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--umgs",
  },
  textLabel2: {
    className: "sdn-text-label sdn-text-label--7mza",
  },
  button3: {
    className: "sdn-button sdn-button--ivvu",
  },
  icon3: {
    icon: "seldon-component",
    "aria-hidden": "true",
    className: "sdn-icon sdn-icon--umgs",
  },
  textLabel3: {
    className: "sdn-text-label sdn-text-label--7mza",
  },
}
