// packages/editor-vue/seldon/elements/CalendarDaySelected.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/*****
 * Calendar Day: CalendarDaySelected
 * Level: Element
 * Intent: A single day cell for a calendar grid. The default renders a plain number; variants cover muted out-of-month days, the selected day, and the current day.
 * Tags: calendar, day, date, cell, ui, grid
 * Type: Custom
 *
 * @example
 * ```vue
 * <CalendarDaySelected
 *   wrapperElement="div"
 *   aria-hidden="false"
 *   aria-selected="true"
 * />
 * ```
 *****/
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"
import { combineClassNames, mergeSlot } from "../utils/class-names"
import TextLabel from "../primitives/TextLabel.vue"

const props = defineProps<{
  className?: string
  wrapperElement?: unknown
  textLabel?: Record<string, unknown> | null
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "wrapperElement": "div",
  "aria-hidden": "false",
  "aria-selected": "true",
  "className": "sdn-calendar-day-selected sdn-calendar-day",
  "textLabel": {
    "className": "sdn-text-label sdn-text-label--fye8"
  }
}

const rootClassName = computed(() => combineClassNames("sdn-calendar-day-selected", props.className))
const rootAttrs = { "aria-hidden": sdn["aria-hidden"], "aria-selected": sdn["aria-selected"] }
const textLabelProps = computed(() => mergeSlot(sdn.textLabel, props.textLabel))
</script>

<template>
    <div :class="rootClassName" v-bind="rootAttrs">
      <slot>
        <TextLabel v-if="textLabel && textLabelProps" v-bind="textLabelProps" />
      </slot>
    </div>
</template>

// packages/editor-react/seldon/elements/CalendarDaySelected.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/
import { HTMLAttributes } from "react"

import { Frame } from "../frames/Frame"
import { TextLabel, TextLabelProps } from "../primitives/TextLabel"
import { applyRef } from "../utils/apply-ref"
import { combineClassNames } from "../utils/class-name"

export interface CalendarDaySelectedProps extends HTMLAttributes<HTMLElement> {
  className?: string
  "data-seldon-ref"?: string
  seldonRefs?: Record<string, Record<string, unknown>>
  wrapperElement?:
    | "div"
    | "section"
    | "article"
    | "aside"
    | "main"
    | "nav"
    | "header"
    | "footer"
    | "ul"
    | "ol"
    | "li"
    | "form"
    | "fieldset"
    | "figure"
    | "menu"
    | "blockquote"
    | "table"
    | "thead"
    | "tbody"
    | "tfoot"
    | "tr"
  textLabel?: TextLabelProps | null
}

/*****
 * Calendar Day: CalendarDaySelected
 * Level: Element
 * Intent: A single day cell for a calendar grid. The default renders a plain number; variants cover muted out-of-month days, the selected day, and the current day.
 * Tags: calendar, day, date, cell, ui, grid
 * Type: Custom
 *
 * @example
 * ```tsx
 * <CalendarDaySelected
 *   wrapperElement="div"
 *   aria-hidden="false"
 *   aria-selected="true"
 * />
 * ```
 *****/
export function CalendarDaySelected({
  className = "",
  wrapperElement = sdn.wrapperElement,
  textLabel,
  children,
  seldonRefs,
  ...props
}: CalendarDaySelectedProps) {
  const calendarDaySelectedClassName = combineClassNames(
    "sdn-calendar-day-selected",
    className,
  )
  const textLabelProps = applyRef(
    seldonRefs,
    textLabel === null
      ? null
      : {
          ...sdn.textLabel,
          ...textLabel,
          className: combineClassNames(
            sdn.textLabel?.className,
            textLabel?.className,
          ),
        },
  )

  return (
    <Frame
      className={calendarDaySelectedClassName}
      aria-hidden={sdn["aria-hidden"]}
      aria-selected={sdn["aria-selected"]}
      {...props}
    >
      {children !== undefined ? (
        children
      ) : (
        <>{textLabel && textLabelProps && <TextLabel {...textLabelProps} />}</>
      )}
    </Frame>
  )
}

//
// Default property values
//
const sdn: CalendarDaySelectedProps = {
  wrapperElement: "div",
  "aria-hidden": "false",
  "aria-selected": "true",
  className: "sdn-calendar-day-selected sdn-calendar-day",
  textLabel: {
    className: "sdn-text-label sdn-text-label--fye8",
  },
}
