// packages/editor/apps/vue/seldon/elements/Avatar.vue
/***** * * This code was generated using Seldon (https://github.com/SeldonDigital/seldon) * *
License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md * Do not redistribute or
sublicense without permission. * * You may not use this software, or any derivative works of it, in
whole or in part, * for the purposes of training, fine-tuning, or otherwise improving (directly or
indirectly) * any machine learning or artificial intelligence system without written permission. *
*****/

<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/**
 * Avatar: Avatar
 * Level: Element
 * Intent: Displays a user or entity's image or initials in UI elements like lists, headers, or profiles.
 * Tags: avatar, user image, profile, identity, initials, picture, circle, UI element
 * Type: Default
 *
 * Structure:
 *   Image  image
 *
 * @example
 * ```vue
 * <Avatar
 *   aria-hidden="false"
 *   image="/image.jpg"
 * />
 * ```
 */
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"

import Image from "../primitives/Image.vue"
import { combineClassNames, mergeSlot } from "../utils/class-names"

const props = defineProps<{
  className?: string
  image?: Record<string, unknown> | null
  seldonRefs?: Record<string, Record<string, unknown>>
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "aria-hidden": "false",
  image: {
    src: "/avatar-user.png",
    "aria-hidden": "false",
    className: "sdn-image sdn-image--to5v",
  },
}

const rootClassName = computed(() => combineClassNames("sdn-avatar", props.className))
const rootAttrs = { "aria-hidden": sdn["aria-hidden"] }
const imageProps = computed(() => mergeSlot(sdn.image, props.image, props.seldonRefs))
</script>

<template>
  <div :class="rootClassName" v-bind="rootAttrs">
    <slot>
      <Image v-if="imageProps !== null" v-bind="imageProps" />
    </slot>
  </div>
</template>

// packages/editor/apps/react/sdn/elements/Avatar.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

import { Frame } from "../frames/Frame"
import { Image } from "../primitives/Image"
import { combineClassNames } from "../utils/class-name"
import { mergeSlot } from "../utils/merge-slot"

import type { ImageProps } from "../primitives/Image"
import type { SeldonRefs } from "../utils/merge-slot"
import type { HTMLAttributes } from "react"

export interface AvatarProps extends HTMLAttributes<HTMLElement> {
  "data-seldon-ref"?: string
  seldonRefs?: SeldonRefs

  image?: ImageProps | null
}

//
// Default property values
//
const sdn: AvatarProps = {
  "aria-hidden": "false",
  image: {
    src: "/avatar-user.png",
    "aria-hidden": "false",
    className: "sdn-image sdn-image--to5v",
  },
}

/**
 * Avatar: Avatar
 * Level: Element
 * Intent: Displays a user or entity's image or initials in UI elements like lists, headers, or profiles.
 * Tags: avatar, user image, profile, identity, initials, picture, circle, UI element
 * Type: Default
 *
 * Structure:
 *   Image  image
 *
 * @example
 * ```tsx
 * <Avatar
 *   aria-hidden="false"
 *   image="/image.jpg"
 * />
 * ```
 */
export function Avatar({
  className = "",
  image,

  children,
  seldonRefs,
  ...props
}: AvatarProps) {
  const avatarClassName = combineClassNames("sdn-avatar", className)

  const imageProps = mergeSlot(sdn.image, image, seldonRefs)

  return (
    <Frame className={avatarClassName} aria-hidden={sdn["aria-hidden"]} {...props}>
      {children !== undefined ? children : <>{imageProps !== null && <Image {...imageProps} />}</>}
    </Frame>
  )
}
