// packages/editor/apps/vue/seldon/elements/Chip.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/**
 * Chip: Chip
 * Level: Element
 * Intent: Schema for a small, interactive UI element used to display information, categories, or actions with optional removal or selection states.
 * Tags: chip, ui, tag, label, badge, filter, category, pill
 * Type: Default
 *
 * Structure:
 *   TextLabel  textLabel
 *
 * @example
 * ```vue
 * <Chip
 *   aria-hidden="false"
 *   textLabel="{}"
 * />
 * ```
 */
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"

import TextLabel from "../primitives/TextLabel.vue"
import { combineClassNames, mergeOptionalSlot } from "../utils/class-names"

const props = defineProps<{
  className?: string
  textLabel?: Record<string, unknown> | null
  seldonRefs?: Record<string, Record<string, unknown>>
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "aria-hidden": "false",
  textLabel: {
    children: "999",
    className: "sdn-text-label sdn-text-label--lug5",
  },
}

const rootClassName = computed(() => combineClassNames("sdn-chip", props.className))
const rootAttrs = { "aria-hidden": sdn["aria-hidden"] }
const textLabelProps = computed(() =>
  mergeOptionalSlot(sdn.textLabel, props.textLabel, props.seldonRefs),
)
</script>

<template>
  <span :class="rootClassName" v-bind="rootAttrs">
    <slot>
      <TextLabel v-if="textLabelProps !== null" v-bind="textLabelProps" />
    </slot>
  </span>
</template>

// packages/editor/apps/react/sdn/elements/Chip.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

import { HTMLSpan } from "../native-react/HTML.Span"
import { TextLabel } from "../primitives/TextLabel"
import { combineClassNames } from "../utils/class-name"
import { mergeOptionalSlot } from "../utils/merge-slot"

import type { TextLabelProps } from "../primitives/TextLabel"
import type { SeldonRefs } from "../utils/merge-slot"
import type { HTMLAttributes } from "react"

export interface ChipProps extends HTMLAttributes<HTMLElement> {
  "data-seldon-ref"?: string
  seldonRefs?: SeldonRefs

  textLabel?: TextLabelProps | null
}

//
// Default property values
//
const sdn: ChipProps = {
  "aria-hidden": "false",
  textLabel: {
    children: "999",
    className: "sdn-text-label sdn-text-label--lug5",
  },
}

/**
 * Chip: Chip
 * Level: Element
 * Intent: Schema for a small, interactive UI element used to display information, categories, or actions with optional removal or selection states.
 * Tags: chip, ui, tag, label, badge, filter, category, pill
 * Type: Default
 *
 * Structure:
 *   TextLabel  textLabel
 *
 * @example
 * ```tsx
 * <Chip
 *   aria-hidden="false"
 *   textLabel="{}"
 * />
 * ```
 */
export function Chip({
  className = "",
  textLabel,

  children,
  seldonRefs,
  ...props
}: ChipProps) {
  const chipClassName = combineClassNames("sdn-chip", className)

  const textLabelProps = mergeOptionalSlot(sdn.textLabel, textLabel, seldonRefs)

  return (
    <HTMLSpan className={chipClassName} aria-hidden={sdn["aria-hidden"]} {...props}>
      {children !== undefined ? (
        children
      ) : (
        <>{textLabelProps !== null && <TextLabel {...textLabelProps} />}</>
      )}
    </HTMLSpan>
  )
}
