// packages/editor/apps/vue/sdn/elements/ListItem.vue
<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/**
 * List Item: Item
 * Level: Element
 * Intent: One list item block. Children are inline Text runs for plain, bold, and italic spans.
 * Tags: list text, li, dt, dd, list item, description, element, text
 * Type: Default
 *
 * @example
 * ```vue
 * <ListItem
 *   htmlElement="li"
 *   aria-hidden="false"
 * />
 * ```
 */
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"

import { combineClassNames } from "../utils/class-names"

const props = defineProps<{
  className?: string
  htmlElement?: unknown
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  htmlElement: "li",
  "aria-hidden": "false",
}

const rootClassName = computed(() => combineClassNames("sdn-list-item", props.className))
const rootAttrs = { "aria-hidden": sdn["aria-hidden"] }
</script>

<template>
  <component
    :is="(props.htmlElement as string) ?? sdn.htmlElement ?? 'div'"
    :class="rootClassName"
    v-bind="rootAttrs"
    ><slot></slot
  ></component>
</template>

// packages/editor/apps/react/sdn/elements/ListItem.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

import { HTMLAttributes } from "react"

import { HTMLDd } from "../native-react/HTML.Dd"
import { HTMLDt } from "../native-react/HTML.Dt"
import { HTMLLi } from "../native-react/HTML.Li"
import { combineClassNames } from "../utils/class-name"

export interface ListItemProps extends HTMLAttributes<HTMLElement | HTMLElement | HTMLLIElement> {
  "data-seldon-ref"?: string
  htmlElement?: "li" | "dt" | "dd"
}

//
// Default property values
//
const sdn: ListItemProps = {
  htmlElement: "li",
  "aria-hidden": "false",
}

/**
 * List Item: Item
 * Level: Element
 * Intent: One list item block. Children are inline Text runs for plain, bold, and italic spans.
 * Tags: list text, li, dt, dd, list item, description, element, text
 * Type: Default
 *
 * @example
 * ```tsx
 * <ListItem
 *   htmlElement="li"
 *   aria-hidden="false"
 * />
 * ```
 */
export function ListItem({
  className = "",
  htmlElement = sdn.htmlElement,
  ...props
}: ListItemProps) {
  const listItemClassName = combineClassNames("sdn-list-item", className)

  switch (htmlElement) {
    case "dt":
      return <HTMLDt className={listItemClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    case "dd":
      return <HTMLDd className={listItemClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
    default:
      return <HTMLLi className={listItemClassName} aria-hidden={sdn["aria-hidden"]} {...props} />
  }
}
