// packages/editor/apps/react/seldon/elements/MessageError.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

import { HTMLAttributes } from "react"

import { ButtonSimple, ButtonSimpleProps } from "../elements/ButtonSimple"
import { Frame, FrameProps } from "../frames/Frame"
import { Icon, IconProps } from "../primitives/Icon"
import { TextDescription, TextDescriptionProps } from "../primitives/TextDescription"
import { TextLabel, TextLabelProps } from "../primitives/TextLabel"
import { combineClassNames } from "../utils/class-name"
import { SeldonRefs, mergeOptionalSlot, mergeSlot } from "../utils/merge-slot"

export interface MessageErrorProps extends HTMLAttributes<HTMLElement> {
  "data-seldon-ref"?: string
  seldonRefs?: SeldonRefs

  frame?: FrameProps | null
  icon?: IconProps | null
  textDescription?: TextDescriptionProps | null

  buttonSimple?: ButtonSimpleProps | null
  textLabel?: TextLabelProps | null
}

//
// Default property values
//
const sdn: MessageErrorProps = {
  "aria-hidden": "false",
  frame: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--ieew",
  },
  icon: {
    icon: "material-error",
    className: "sdn-icon sdn-icon--gm8j",
    "data-seldon-ref": "hariErrorIcon",
  },
  textDescription: {
    children: "Something went wrong",
    className: "sdn-text-description sdn-text-label--lbxv",
    "data-seldon-ref": "hariErrorText",
  },

  buttonSimple: {
    className: "sdn-button-simple sdn-button-iconic--iklu",
    "data-seldon-ref": "hariErrorRetry",
  },
  textLabel: {
    children: "Retry",
    className: "sdn-text-label sdn-text-label--aftu",
    "data-seldon-ref": "hariErrorRetryLabel",
  },
}

/**
 * Message: MessageError
 * Level: Element
 * Intent: Transcript message block for an AI chat. Renders one turn piece: a plain text block, a user or assistant message, reasoning, tool activity, an outcome summary, an error, or a status line.
 * Tags: message, chat, transcript, ai, element, text, bubble
 * Type: Inline
 *
 * Structure:
 *   Frame              frame
 *     Icon             icon             -> hariErrorIcon
 *     TextDescription  textDescription  -> hariErrorText
 *   ButtonSimple       buttonSimple     -> hariErrorRetry
 *     TextLabel        textLabel        -> hariErrorRetryLabel
 *
 * @example
 * ```tsx
 * <MessageError
 *   aria-hidden="false"
 *   frame="{}"
 *   icon="material-star"
 *   textDescription="{}"
 *   buttonSimple={() => {}}
 *   textLabel="{}"
 * />
 * ```
 */
export function MessageError({
  className = "",
  frame,
  icon,
  textDescription,

  buttonSimple,
  textLabel,

  children,
  seldonRefs,
  ...props
}: MessageErrorProps) {
  const messageErrorClassName = combineClassNames("sdn-message-error", className)

  const frameProps = mergeSlot(sdn.frame, frame, seldonRefs)
  const iconProps = mergeOptionalSlot(sdn.icon, icon, seldonRefs)
  const textDescriptionProps = mergeOptionalSlot(sdn.textDescription, textDescription, seldonRefs)

  const buttonSimpleProps = mergeSlot(sdn.buttonSimple, buttonSimple, seldonRefs)
  const textLabelProps = mergeOptionalSlot(sdn.textLabel, textLabel, seldonRefs)

  return (
    <Frame className={messageErrorClassName} aria-hidden={sdn["aria-hidden"]} {...props}>
      {children !== undefined ? (
        children
      ) : (
        <>
          <Frame {...frameProps}>
            {iconProps !== null && <Icon {...iconProps} />}
            {textDescriptionProps !== null && <TextDescription {...textDescriptionProps} />}
          </Frame>
          {buttonSimpleProps !== null && (
            <ButtonSimple {...buttonSimpleProps}>
              {textLabelProps !== null && <TextLabel {...textLabelProps} />}
            </ButtonSimple>
          )}
        </>
      )}
    </Frame>
  )
}

// packages/editor/apps/vue/seldon/elements/MessageError.vue
/***** * * This code was generated using Seldon (https://github.com/SeldonDigital/seldon) * *
License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md * Do not redistribute or
sublicense without permission. * * You may not use this software, or any derivative works of it, in
whole or in part, * for the purposes of training, fine-tuning, or otherwise improving (directly or
indirectly) * any machine learning or artificial intelligence system without written permission. *
*****/

<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/**
 * Message: MessageError
 * Level: Element
 * Intent: Transcript message block for an AI chat. Renders one turn piece: a plain text block, a user or assistant message, reasoning, tool activity, an outcome summary, an error, or a status line.
 * Tags: message, chat, transcript, ai, element, text, bubble
 * Type: Inline
 *
 * Structure:
 *   Frame              frame
 *     Icon             icon             -> hariErrorIcon
 *     TextDescription  textDescription  -> hariErrorText
 *   ButtonSimple       buttonSimple     -> hariErrorRetry
 *     TextLabel        textLabel        -> hariErrorRetryLabel
 *
 * @example
 * ```vue
 * <MessageError
 *   aria-hidden="false"
 *   frame="{}"
 *   icon="material-star"
 *   textDescription="{}"
 *   buttonSimple={() => {}}
 *   textLabel="{}"
 * />
 * ```
 */
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"

import ButtonSimple from "../elements/ButtonSimple.vue"
import Frame from "../frames/Frame.vue"
import Icon from "../primitives/Icon.vue"
import TextDescription from "../primitives/TextDescription.vue"
import TextLabel from "../primitives/TextLabel.vue"
import { combineClassNames, mergeOptionalSlot, mergeSlot } from "../utils/class-names"

const props = defineProps<{
  className?: string
  frame?: Record<string, unknown> | null
  icon?: Record<string, unknown> | null
  textDescription?: Record<string, unknown> | null
  buttonSimple?: Record<string, unknown> | null
  textLabel?: Record<string, unknown> | null
  seldonRefs?: Record<string, Record<string, unknown>>
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "aria-hidden": "false",
  frame: {
    wrapperElement: "div",
    "aria-hidden": "false",
    className: "sdn-frame sdn-frame--ieew",
  },
  icon: {
    icon: "material-error",
    className: "sdn-icon sdn-icon--gm8j",
    "data-seldon-ref": "hariErrorIcon",
  },
  textDescription: {
    children: "Something went wrong",
    className: "sdn-text-description sdn-text-label--lbxv",
    "data-seldon-ref": "hariErrorText",
  },
  buttonSimple: {
    className: "sdn-button-simple sdn-button-iconic--iklu",
    "data-seldon-ref": "hariErrorRetry",
  },
  textLabel: {
    children: "Retry",
    className: "sdn-text-label sdn-text-label--aftu",
    "data-seldon-ref": "hariErrorRetryLabel",
  },
}

const rootClassName = computed(() => combineClassNames("sdn-message-error", props.className))
const rootAttrs = { "aria-hidden": sdn["aria-hidden"] }
const frameProps = computed(() => mergeSlot(sdn.frame, props.frame, props.seldonRefs))
const iconProps = computed(() => mergeOptionalSlot(sdn.icon, props.icon, props.seldonRefs))
const textDescriptionProps = computed(() =>
  mergeOptionalSlot(sdn.textDescription, props.textDescription, props.seldonRefs),
)
const buttonSimpleProps = computed(() =>
  mergeSlot(sdn.buttonSimple, props.buttonSimple, props.seldonRefs),
)
const textLabelProps = computed(() =>
  mergeOptionalSlot(sdn.textLabel, props.textLabel, props.seldonRefs),
)
</script>

<template>
  <div :class="rootClassName" v-bind="rootAttrs">
    <slot>
      <Frame v-bind="frameProps">
        <Icon v-if="iconProps !== null" v-bind="iconProps" />
        <TextDescription v-if="textDescriptionProps !== null" v-bind="textDescriptionProps" />
      </Frame>
      <ButtonSimple v-if="buttonSimpleProps !== null" v-bind="buttonSimpleProps">
        <TextLabel v-if="textLabelProps !== null" v-bind="textLabelProps" />
      </ButtonSimple>
    </slot>
  </div>
</template>
