// packages/editor/apps/react/seldon/elements/SectionSectionBrand.tsx
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

import { HTMLAttributes } from "react"

import { Frame } from "../frames/Frame"
import { Image, ImageProps } from "../primitives/Image"
import { TextDescription, TextDescriptionProps } from "../primitives/TextDescription"
import { TextTitle, TextTitleProps } from "../primitives/TextTitle"
import { combineClassNames } from "../utils/class-name"
import { SeldonRefs, mergeOptionalSlot, mergeSlot } from "../utils/merge-slot"

export interface SectionSectionBrandProps extends HTMLAttributes<HTMLElement> {
  "data-seldon-ref"?: string
  seldonRefs?: SeldonRefs

  image?: ImageProps | null

  textTitle?: TextTitleProps | null

  textDescription?: TextDescriptionProps | null
}

//
// Default property values
//
const sdn: SectionSectionBrandProps = {
  "aria-hidden": "false",
  image: {
    src: "https://static.seldon.app/logo.svg",
    "aria-hidden": "false",
    className: "sdn-image sdn-image--wxaq",
  },

  textTitle: {
    children: "Company Name",
    className: "sdn-text-title sdn-text-title--unrf",
  },

  textDescription: {
    children: "Building amazing products for the future.",
    className: "sdn-text-description sdn-text-title--unrf",
  },
}

/**
 * Section: SectionBrand
 * Level: Element
 * Intent: Navigation section containing links to important pages. Can be used in footers, headers, sidebars, or any other layout context. Follows Material Design navigation patterns.
 * Tags: section, navigation, links, menu, element, layout, header, footer, sidebar
 * Type: Custom
 *
 * Structure:
 *   Image            image
 *   TextTitle        textTitle
 *   TextDescription  textDescription
 *
 * @example
 * ```tsx
 * <SectionSectionBrand
 *   aria-hidden="false"
 *   image="/image.jpg"
 *   textTitle="Product Title"
 *   textDescription2="{}"
 * />
 * ```
 */
export function SectionSectionBrand({
  className = "",
  image,

  textTitle,

  textDescription,

  children,
  seldonRefs,
  ...props
}: SectionSectionBrandProps) {
  const sectionSectionBrandClassName = combineClassNames("sdn-section", className)

  const imageProps = mergeSlot(sdn.image, image, seldonRefs)

  const textTitleProps = mergeOptionalSlot(sdn.textTitle, textTitle, seldonRefs)

  const textDescriptionProps = mergeOptionalSlot(sdn.textDescription, textDescription, seldonRefs)

  return (
    <Frame className={sectionSectionBrandClassName} aria-hidden={sdn["aria-hidden"]} {...props}>
      {children !== undefined ? (
        children
      ) : (
        <>
          {imageProps !== null && <Image {...imageProps} />}
          {textTitleProps !== null && <TextTitle {...textTitleProps} />}
          {textDescriptionProps !== null && <TextDescription {...textDescriptionProps} />}
        </>
      )}
    </Frame>
  )
}

// packages/editor/apps/vue/seldon/elements/SectionSectionBrand.vue
/***** * * This code was generated using Seldon (https://github.com/SeldonDigital/seldon) * *
License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md * Do not redistribute or
sublicense without permission. * * You may not use this software, or any derivative works of it, in
whole or in part, * for the purposes of training, fine-tuning, or otherwise improving (directly or
indirectly) * any machine learning or artificial intelligence system without written permission. *
*****/

<script lang="ts">
/*****
 *
 * This code was generated using Seldon (https://github.com/SeldonDigital/seldon)
 *
 * License: https://github.com/SeldonDigital/seldon/blob/main/LICENSE.md
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it, in whole or in part,
 * for the purposes of training, fine-tuning, or otherwise improving (directly or indirectly)
 * any machine learning or artificial intelligence system without written permission.
 *
 *****/

/**
 * Section: SectionBrand
 * Level: Element
 * Intent: Navigation section containing links to important pages. Can be used in footers, headers, sidebars, or any other layout context. Follows Material Design navigation patterns.
 * Tags: section, navigation, links, menu, element, layout, header, footer, sidebar
 * Type: Custom
 *
 * Structure:
 *   Image            image
 *   TextTitle        textTitle
 *   TextDescription  textDescription
 *
 * @example
 * ```vue
 * <SectionSectionBrand
 *   aria-hidden="false"
 *   image="/image.jpg"
 *   textTitle="Product Title"
 *   textDescription2="{}"
 * />
 * ```
 */
export default {}
</script>

<script setup lang="ts">
import { computed } from "vue"

import Image from "../primitives/Image.vue"
import TextDescription from "../primitives/TextDescription.vue"
import TextTitle from "../primitives/TextTitle.vue"
import { combineClassNames, mergeOptionalSlot, mergeSlot } from "../utils/class-names"

const props = defineProps<{
  className?: string
  image?: Record<string, unknown> | null
  textTitle?: Record<string, unknown> | null
  textDescription?: Record<string, unknown> | null
  seldonRefs?: Record<string, Record<string, unknown>>
}>()

//
// Default property values
//
const sdn: Record<string, any> = {
  "aria-hidden": "false",
  image: {
    src: "https://static.seldon.app/logo.svg",
    "aria-hidden": "false",
    className: "sdn-image sdn-image--wxaq",
  },
  textTitle: {
    children: "Company Name",
    className: "sdn-text-title sdn-text-title--unrf",
  },
  textDescription: {
    children: "Building amazing products for the future.",
    className: "sdn-text-description sdn-text-title--unrf",
  },
}

const rootClassName = computed(() => combineClassNames("sdn-section", props.className))
const rootAttrs = { "aria-hidden": sdn["aria-hidden"] }
const imageProps = computed(() => mergeSlot(sdn.image, props.image, props.seldonRefs))
const textTitleProps = computed(() =>
  mergeOptionalSlot(sdn.textTitle, props.textTitle, props.seldonRefs),
)
const textDescriptionProps = computed(() =>
  mergeOptionalSlot(sdn.textDescription, props.textDescription, props.seldonRefs),
)
</script>

<template>
  <div :class="rootClassName" v-bind="rootAttrs">
    <slot>
      <Image v-if="imageProps !== null" v-bind="imageProps" />
      <TextTitle v-if="textTitleProps !== null" v-bind="textTitleProps" />
      <TextDescription v-if="textDescriptionProps !== null" v-bind="textDescriptionProps" />
    </slot>
  </div>
</template>
