// packages/editor/apps/vue/app/menus/ComboboxOptions.vue
<script setup lang="ts">
import { useEditorConfigStore } from "@app/editor/editor-config-store"
import { useResolvedInterfaceMode } from "@app/editor/use-resolved-interface-mode"
import MenuItemOption from "@seldon/components/elements/MenuItemOption.vue"
import MenuOptions from "@seldon/components/parts/MenuOptions.vue"
import Hr from "@seldon/components/primitives/Hr.vue"
import { computeListPosition } from "@seldon/editor/lib/menus/anchor-position"
import { storeToRefs } from "pinia"
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue"

import type { ComboboxOptionItem } from "./types"
import type { ListPosition } from "@seldon/editor/lib/menus/anchor-position"

/** Vertical gap between the trigger and the panel, and min room to open below. */
const PANEL_GAP = 4
const MIN_SPACE_BELOW = 240

/**
 * Controlled floating option list on the generated `MenuOptions`/`MenuItemOption`
 * chrome. The caller owns `open` and the `anchor`. Left-aligns to the anchor,
 * sits at least as wide as it, and grows to fit the widest option, capped to the
 * viewport. Flips above when room is tight, and supports arrow/enter/escape
 * keyboard selection. Portals to `body` and re-stamps `data-theme`/`data-mode`
 * so it keeps the chrome theme. Powers the objects-sidebar Display picker and the
 * properties sidebar.
 */
const props = defineProps<{
  open: boolean
  anchor: HTMLElement | null
  optionGroups: ComboboxOptionItem[][]
  value: string
  resolveIcon?: (value: string) => string
}>()

const emit = defineEmits<{
  (event: "select", value: string): void
  (event: "close"): void
}>()

const { chromeTheme } = storeToRefs(useEditorConfigStore())
const resolvedMode = useResolvedInterfaceMode()

const panelRef = ref<HTMLElement | null>(null)
const position = ref<ListPosition>({ x: 0, y: 0, w: 0 })
const highlightedValue = ref<string | undefined>(undefined)

const flatOptions = computed<ComboboxOptionItem[]>(() =>
  props.optionGroups.flat().filter((option) => !option.hidden),
)

function place(): void {
  if (!props.anchor) return
  position.value = computeListPosition(
    props.anchor.getBoundingClientRect(),
    { width: window.innerWidth, height: window.innerHeight },
    {
      gap: PANEL_GAP,
      minSpaceBelow: MIN_SPACE_BELOW,
    },
  )
}

const panelStyle = computed(() => ({
  position: "fixed" as const,
  zIndex: 60,
  minWidth: `${position.value.w}px`,
  width: "max-content",
  maxWidth: `calc(100vw - ${position.value.x}px - 8px)`,
  outline: "none",
  left: `${position.value.x}px`,
  top: `${position.value.y}px`,
  transform: position.value.positionAbove ? "translateY(-100%)" : undefined,
}))

// The scroll cap lives on the options surface itself, which owns the border,
// radius, and shadow, so the bordered box hugs the visible panel instead of being
// clipped by an outer wrapper. Matches React, which applies these the same way.
const optionsStyle = {
  maxHeight: "24rem",
  overflowY: "auto" as const,
}

// The content reaches every slot by ref name. Every slot on a menu row is opt-in,
// so each keeps a positional enabler; without one the slot would not render.
function optionRefs(option: ComboboxOptionItem): Record<string, Record<string, unknown>> {
  return {
    optionIcon: { icon: props.resolveIcon?.(option.value) ?? "seldon-component" },
    optionLabel: { children: option.name },
    optionAnnotation: { children: option.annotation },
  }
}

/** The annotation slot stays off when the option has no annotation. */
function optionAnnotationSlot(option: ComboboxOptionItem): Record<string, unknown> | undefined {
  return option.annotation ? {} : undefined
}

function optionClass(option: ComboboxOptionItem): string | undefined {
  const classes: string[] = []
  if (option.value === props.value) classes.push("sdn-state-activated")
  if (option.value === highlightedValue.value) classes.push("sdn-state-hover")
  return classes.length > 0 ? classes.join(" ") : undefined
}

function moveHighlight(direction: 1 | -1): void {
  const options = flatOptions.value
  if (options.length === 0) return
  const current = options.findIndex((option) => option.value === highlightedValue.value)
  let next = current + direction
  if (next < 0) next = options.length - 1
  if (next >= options.length) next = 0
  highlightedValue.value = options[next]?.value
}

function select(value: string): void {
  emit("select", value)
  emit("close")
}

function onKeydown(event: KeyboardEvent): void {
  switch (event.key) {
    case "ArrowDown":
      event.preventDefault()
      moveHighlight(1)
      break
    case "ArrowUp":
      event.preventDefault()
      moveHighlight(-1)
      break
    case "Enter":
      event.preventDefault()
      if (highlightedValue.value) select(highlightedValue.value)
      break
    case "Escape":
    case "Tab":
      event.preventDefault()
      emit("close")
      break
  }
}

function onDocumentPointerDown(event: PointerEvent): void {
  if (!props.open) return
  const target = event.target as Node
  if (panelRef.value?.contains(target)) return
  if (props.anchor?.contains(target)) return
  emit("close")
}

watch(
  () => props.open,
  (open) => {
    if (!open) return
    place()
    highlightedValue.value = props.value
    void nextTick(() => panelRef.value?.focus())
  },
)

watch(
  () => props.anchor,
  () => {
    if (props.open) place()
  },
)

onMounted(() => {
  document.addEventListener("pointerdown", onDocumentPointerDown, true)
  window.addEventListener("resize", place)
  window.addEventListener("scroll", place, true)
  if (props.open) {
    place()
    highlightedValue.value = props.value
    void nextTick(() => panelRef.value?.focus())
  }
})

onBeforeUnmount(() => {
  document.removeEventListener("pointerdown", onDocumentPointerDown, true)
  window.removeEventListener("resize", place)
  window.removeEventListener("scroll", place, true)
})
</script>

<template>
  <Teleport to="body">
    <div
      v-if="open"
      ref="panelRef"
      :tabindex="-1"
      :style="panelStyle"
      :data-theme="chromeTheme"
      :data-mode="resolvedMode"
      @keydown="onKeydown"
    >
      <MenuOptions :style="optionsStyle">
        <template v-for="(group, groupIndex) in optionGroups" :key="`group-${groupIndex}`">
          <Hr v-if="groupIndex > 0" />
          <MenuItemOption
            v-for="option in group"
            :key="option.value"
            :class="optionClass(option)"
            :aria-selected="option.value === value || undefined"
            :seldon-refs="optionRefs(option)"
            :icon="{}"
            :text-label="{}"
            :text-label2="optionAnnotationSlot(option)"
            @click="select(option.value)"
            @pointerenter="highlightedValue = option.value"
          />
        </template>
      </MenuOptions>
    </div>
  </Teleport>
</template>

// packages/editor/apps/react/app/menus/ComboboxOptions.tsx
/**
 * View-model for the floating option list of a combobox. Renders the generated
 * `MenuOptions` (its Frame is the positioned surface) with one generated
 * `MenuItemOption` per option. Option rows bind through the `optionIcon`,
 * `optionLabel`, and `optionAnnotation` slot refs when the icon is a plain id,
 * and fall back to children when the icon is a dynamic node the string-based
 * `Icon` slot cannot host.
 *
 * Only functional placement (fixed position, scroll) is applied inline; all
 * appearance comes from the authored component CSS.
 */
import { useEditorConfig } from "@app/editor/hooks/use-editor-config"
import { useResolvedInterfaceMode } from "@app/editor/hooks/use-system-color-scheme"
import { MenuItemOption } from "@seldon/components/elements/MenuItemOption"
import { Frame } from "@seldon/components/frames/Frame"
import { MenuOptions } from "@seldon/components/parts/MenuOptions"
import { Hr } from "@seldon/components/primitives/Hr"
import { TextLabel } from "@seldon/components/primitives/TextLabel"
import { Fragment } from "react"
import { createPortal } from "react-dom"

import type { ComboboxOptionItem, OptionIconRender } from "./types"
import type { IconProps } from "@seldon/components/primitives/Icon"
import type { CSSProperties, MouseEvent, ReactNode } from "react"

interface Position {
  x: number
  y: number
  w: number
  positionAbove?: boolean
}

interface ComboboxOptionsProps {
  open: boolean
  position: Position
  handleClose: () => void
  onPointerLeave: () => void
  filteredOptions: ComboboxOptionItem[] | ComboboxOptionItem[][]
  hasSections: boolean
  value: string
  resolveIcon: (option?: { value: string; name: string }) => OptionIconRender
  onSelect: (value: string) => void
  onHighlight: (value: string | undefined) => void
  highlightedValue?: string
}

// Keyboard-highlighted option. The class hooks the workspace `Activated` state
// once authored; until then it styles nothing, which is acceptable.
const HIGHLIGHT_CLASS = "sdn-state-activated"

// The option label reuses the generated slot's delta class so the authored
// option state CSS (`:hover`, `[aria-selected]`, `[aria-disabled]`) scopes to it
// on the children path exactly as it does on the slot path.
const OPTION_LABEL_CLASS = "sdn-text-label sdn-text-label--xohb"
const OPTION_ANNOTATION_CLASS = "sdn-text-label sdn-text-label--lqmh"

// The option list portals to `document.body`, so it must sit above the floating
// window surface (`WindowSurface` z-40) to stay visible when the properties panel
// is a floating palette or the combobox opens over a dialog. It stays below the
// top menu/toast tier (z-50). The backdrop sits one step under the panel.
const OPTIONS_BACKDROP_Z_INDEX = 44
const OPTIONS_PANEL_Z_INDEX = 45

const backdropStyle: CSSProperties = {
  position: "fixed",
  inset: 0,
  zIndex: OPTIONS_BACKDROP_Z_INDEX,
}

// The portal root only scopes the chrome theme and mode swap; it lays out nothing.
const themeScopeStyle: CSSProperties = { display: "contents" }

export function ComboboxOptions({
  open,
  position,
  handleClose,
  onPointerLeave,
  filteredOptions,
  hasSections,
  value,
  highlightedValue,
  resolveIcon,
  onSelect,
  onHighlight,
}: ComboboxOptionsProps) {
  const { chromeTheme } = useEditorConfig()
  const resolvedMode = useResolvedInterfaceMode()

  if (!open) {
    return null
  }

  const panelStyle: CSSProperties = {
    position: "fixed",
    zIndex: OPTIONS_PANEL_Z_INDEX,
    top: position.y,
    left: position.x,
    minWidth: position.w,
    width: "max-content",
    maxWidth: `calc(100vw - ${position.x}px - 8px)`,
    maxHeight: "24rem",
    overflowY: "auto",
    ...(position.positionAbove ? { transform: "translateY(-100%)" } : {}),
  }

  function renderOption(option: ComboboxOptionItem): ReactNode {
    if (option.hidden) {
      return null
    }

    const isSelected = option.value.toLowerCase() === value.toLowerCase()
    const isHighlighted = option.value === highlightedValue
    const icon = resolveIcon(option)

    const handleMouseDown = (event: MouseEvent) => {
      if (option.disabled) return
      event.preventDefault()
      onSelect(option.value)
    }

    const handleMouseEnter = () => {
      if (!option.disabled) onHighlight(option.value)
    }

    const common = {
      role: "option",
      "aria-selected": isSelected || undefined,
      "aria-disabled": option.disabled || undefined,
      className: isHighlighted ? HIGHLIGHT_CLASS : undefined,
      onMouseDown: handleMouseDown,
      onMouseEnter: handleMouseEnter,
    }

    // Every slot on a menu row is opt-in, so each keeps a positional enabler;
    // without one the slot would not render. The annotation stays off when the
    // option has none.
    const annotationSlot = option.annotation ? {} : undefined

    if (icon.kind === "iconId") {
      // The content reaches every slot by ref name.
      const optionRefs = {
        optionIcon: { icon: icon.icon as IconProps["icon"] },
        optionLabel: { children: option.name },
        optionAnnotation: { children: option.annotation },
      }

      return (
        <MenuItemOption
          key={option.value}
          {...common}
          icon={{}}
          textLabel={{}}
          textLabel2={annotationSlot}
          seldonRefs={optionRefs}
        />
      )
    }

    const annotationNode = option.annotation ? (
      <TextLabel className={OPTION_ANNOTATION_CLASS}>{option.annotation}</TextLabel>
    ) : null

    return (
      <MenuItemOption key={option.value} {...common}>
        {icon.node}
        <TextLabel className={OPTION_LABEL_CLASS}>{option.name}</TextLabel>
        {annotationNode}
      </MenuItemOption>
    )
  }

  const content = hasSections
    ? (filteredOptions as ComboboxOptionItem[][]).map((group, index) => {
        const divider = index > 0 ? <Hr /> : null
        const options = group.map(renderOption)

        return (
          <Fragment key={index}>
            {divider}
            {options}
          </Fragment>
        )
      })
    : (filteredOptions as ComboboxOptionItem[]).map(renderOption)

  return createPortal(
    <Frame data-theme={chromeTheme} data-mode={resolvedMode} style={themeScopeStyle}>
      <Frame onClick={handleClose} style={backdropStyle} />
      <MenuOptions style={panelStyle} onMouseLeave={onPointerLeave}>
        {content}
      </MenuOptions>
    </Frame>,
    document.body,
  )
}
