// packages/editor/apps/react/app/palettes/components/ComponentPaletteController.tsx
"use client"

import { useComponentDragSession } from "@app/canvas/hooks/use-component-drag-session"
import { useEditorConfig } from "@app/editor/hooks/use-editor-config"
import { usePanel } from "@app/editor/hooks/use-panel"
import { useTool } from "@app/editor/hooks/use-tool"
import { FloatingPanel } from "@app/windows/FloatingPanel"
import { draggable } from "@atlaskit/pragmatic-drag-and-drop/element/adapter"
import { ItemCatalog } from "@seldon/components/elements/ItemCatalog"
import { Frame } from "@seldon/components/frames/Frame"
import { PanelPalette } from "@seldon/components/modules/PanelPalette"
import { BarFilter } from "@seldon/components/parts/BarFilter"
import { ListStandardCatalog } from "@seldon/components/parts/ListStandardCatalog"
import { TextSubtitle } from "@seldon/components/primitives/TextSubtitle"
import { TextTitle } from "@seldon/components/primitives/TextTitle"
import { useCallback, useEffect, useMemo, useRef } from "react"

import { useDialog } from "../../dialogs/hooks/use-dialog"

import type { CatalogComponentItem } from "../../dialogs/hooks/use-dialog"
import type { FloatingPanelApi } from "@app/windows/FloatingPanel"
import type { ComponentDragPayload } from "@seldon/editor/lib/workspace/component-drag"
import type { CSSProperties, ChangeEvent } from "react"

const EMPTY_SLOT = {}
const INITIAL_HEIGHT = 520
const INITIAL_WIDTH = 420

export function ComponentPaletteController() {
  const { componentPaletteOpen, closeComponentPalette } = usePanel()

  if (!componentPaletteOpen) return null

  return <ComponentPalette close={closeComponentPalette} />
}

function ComponentPalette({ close }: { close: () => void }) {
  const { componentPaletteRect, setComponentPaletteRect } = useEditorConfig()
  const showComponent = useCallback(() => true, [])
  const showAuthored = useCallback(() => true, [])
  const { categories, query, setQuery } = useDialog({
    shouldShowComponent: showComponent,
    shouldShowAuthored: showAuthored,
  })
  const visibleCategories = useMemo(
    () => categories.filter((category) => category.items.length > 0),
    [categories],
  )
  const onQueryChange = useCallback(
    (event: ChangeEvent<HTMLInputElement>) => setQuery(event.currentTarget.value),
    [setQuery],
  )
  const onClearQuery = useCallback(() => setQuery(""), [setQuery])
  const renderPalette = useCallback(
    (api: FloatingPanelApi) => {
      const content = visibleCategories.map((category) => (
        <ListStandardCatalog key={category.category}>
          <TextSubtitle>{category.category}</TextSubtitle>
          {category.items.map((item) => (
            <ComponentDragSource key={item.id} item={item} />
          ))}
        </ListStandardCatalog>
      ))
      const filter = (
        <BarFilter
          comboboxField={EMPTY_SLOT}
          input={filterInput}
          buttonIconic={EMPTY_SLOT}
          seldonRefs={{
            filterField: { onPointerDown: api.startDrag },
            filterFieldClear: { onClick: onClearQuery },
          }}
        />
      )
      const topBar = <TextTitle>Components</TextTitle>
      const topBarSlot = { children: topBar }
      const contentSlot = { children: content, style: contentStyle }
      const bottomBarSlot = { children: filter }
      const seldonRefs = {
        paletteTopBar: { onPointerDown: api.startDrag },
        paletteClose: { onClick: close, "data-testid": "component-palette-close" },
      }
      const palette = (
        <PanelPalette
          buttonIconic={null}
          buttonIconic2={EMPTY_SLOT}
          frame2={topBarSlot}
          frame3={contentSlot}
          frame5={bottomBarSlot}
          seldonRefs={seldonRefs}
          style={panelStyle}
          data-testid="component-palette"
        />
      )

      return palette
    },
    [close, onClearQuery, onQueryChange, query, visibleCategories],
  )
  const filterInput = { onChange: onQueryChange, value: query }
  const floatingPanel = (
    <FloatingPanel
      initialHeight={INITIAL_HEIGHT}
      initialWidth={INITIAL_WIDTH}
      onClose={close}
      onRectChange={setComponentPaletteRect}
      paletteId="component-palette"
      rect={componentPaletteRect}
      testId="component-palette"
    >
      {renderPalette}
    </FloatingPanel>
  )

  return floatingPanel
}

function ComponentDragSource({ item }: { item: CatalogComponentItem }) {
  const ref = useRef<HTMLElement | null>(null)
  const { setActiveTool } = useTool()
  const { begin, clear } = useComponentDragSession()
  const payload = useMemo<ComponentDragPayload>(
    () =>
      item.variantId
        ? { kind: "authored", variantId: item.variantId }
        : { componentId: item.componentId, kind: "catalog" },
    [item.componentId, item.variantId],
  )

  const refs = {
    catalogIcon: { icon: item.icon },
    catalogLabel: { children: item.name },
    catalogVariant: { children: item.description },
  }

  useEffect(() => {
    const element = ref.current

    if (!element) return

    return draggable({
      element,
      getInitialData: () => ({ action: "component-palette-insert", payload }),
      onDragStart: () => {
        begin(payload)
        setActiveTool("component")
      },
      onDrop: () => {
        clear()
        setActiveTool("select")
      },
    })
  }, [begin, clear, payload, setActiveTool])
  const testId = `component-palette-item-${item.id}`
  const itemContent = (
    <ItemCatalog
      icon={EMPTY_SLOT}
      seldonRefs={refs}
      textSubtitle={EMPTY_SLOT}
      textTitle={EMPTY_SLOT}
      data-testid={testId}
    />
  )
  const dragSource = <Frame ref={ref}>{itemContent}</Frame>

  return dragSource
}

const panelStyle: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  height: "100%",
  width: "100%",
}

const contentStyle: CSSProperties = {
  flex: 1,
  minHeight: 0,
  overflowY: "auto",
}

// packages/editor/apps/vue/app/palettes/components/ComponentPaletteController.vue
<script setup lang="ts">
import { useEditorConfigStore } from "@app/editor/editor-config-store"
import { usePanelStore } from "@app/editor/panel-store"
import FloatingPanel from "@app/windows/FloatingPanel.vue"
import ItemCatalog from "@seldon/components/elements/ItemCatalog.vue"
import PanelPalette from "@seldon/components/modules/PanelPalette.vue"
import BarFilter from "@seldon/components/parts/BarFilter.vue"
import ListStandardCatalog from "@seldon/components/parts/ListStandardCatalog.vue"
import TextSubtitle from "@seldon/components/primitives/TextSubtitle.vue"
import TextTitle from "@seldon/components/primitives/TextTitle.vue"
import { storeToRefs } from "pinia"

import { useCatalogDialog } from "../../dialogs/use-catalog-dialog"

import type { CSSProperties } from "vue"

const INITIAL_HEIGHT = 520
const INITIAL_WIDTH = 420
const styles: Record<string, CSSProperties> = {
  panel: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    width: "100%",
  },
  content: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
}

const config = useEditorConfigStore()
const panel = usePanelStore()
const { componentPaletteOpen } = storeToRefs(panel)
const { componentPaletteRect } = storeToRefs(config)
const { categories, query } = useCatalogDialog(
  () => true,
  () => true,
)

function close(): void {
  panel.closeComponentPalette()
}

function onQueryChange(event: Event): void {
  query.value = (event.target as HTMLInputElement).value
}

function clearQuery(): void {
  query.value = ""
}

function startComponentDrag(event: DragEvent, componentId: string, variantId?: string): void {
  const payload = variantId ? { kind: "authored", variantId } : { componentId, kind: "catalog" }

  event.dataTransfer?.setData("application/x-seldon-component", JSON.stringify(payload))
}
</script>

<template>
  <FloatingPanel
    v-if="componentPaletteOpen"
    :initial-width="INITIAL_WIDTH"
    :initial-height="INITIAL_HEIGHT"
    :on-close="close"
    palette-id="component-palette"
    test-id="component-palette"
    :rect="componentPaletteRect"
    :on-rect-change="config.setComponentPaletteRect"
    #default="{ startDrag }"
  >
    <PanelPalette
      :button-iconic="null"
      :button-iconic2="{}"
      :frame3="{ style: styles.content }"
      :style="styles.panel"
      :seldon-refs="{
        paletteTopBar: { onPointerdown: startDrag },
        paletteClose: { onClick: close },
      }"
    >
      <template #frame2>
        <TextTitle>Components</TextTitle>
      </template>
      <template #frame5>
        <BarFilter
          :combobox-field="{}"
          :button-iconic="{}"
          :input="{ value: query, onInput: onQueryChange }"
          :seldon-refs="{ filterFieldClear: { onClick: clearQuery } }"
        />
      </template>
      <template #frame3>
        <ListStandardCatalog v-for="category in categories" :key="category.category">
          <TextSubtitle>{{ category.category }}</TextSubtitle>
          <ItemCatalog
            v-for="item in category.items"
            :key="item.id"
            draggable="true"
            :icon="{}"
            :text-title="{}"
            :text-subtitle="{}"
            :seldon-refs="{
              catalogIcon: { icon: item.icon },
              catalogLabel: { children: item.name },
              catalogVariant: { children: item.description },
            }"
            @dragstart="startComponentDrag($event, item.componentId, item.variantId)"
          />
        </ListStandardCatalog>
      </template>
    </PanelPalette>
  </FloatingPanel>
</template>
