// packages/editor/apps/vue/app/menus/MenuController.vue
<script setup lang="ts">
import { useEditorConfigStore } from "@app/editor/editor-config-store"
import { useResolvedInterfaceMode } from "@app/editor/use-resolved-interface-mode"
import MenuItem from "@seldon/components/elements/MenuItem.vue"
import Menu from "@seldon/components/parts/Menu.vue"
import Hr from "@seldon/components/primitives/Hr.vue"
import { computeMenuPosition } from "@seldon/editor/lib/menus/anchor-position"
import { storeToRefs } from "pinia"
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue"

import type { MenuAlign, MenuEntry, MenuItem as MenuItemModel } from "./types"
import type { MenuPosition } from "@seldon/editor/lib/menus/anchor-position"

/**
 * Controlled floating menu built on the generated `Menu`/`MenuItem` chrome. The
 * caller owns `open` and the `anchor` element. Owns positioning, roving-focus
 * keyboard navigation, outside-pointer and Escape close, focus restore, and the
 * leading marker column. Portals to `body` and re-stamps `data-theme`/`data-mode`
 * so the menu keeps the chrome theme outside the layout tree. Mirrors the React
 * `MenuController` controlled mode.
 */
const props = withDefaults(
  defineProps<{
    open: boolean
    anchor: HTMLElement | null
    items: MenuEntry[]
    align?: MenuAlign
    minWidth?: string
  }>(),
  { align: "start", minWidth: "180px" },
)

const emit = defineEmits<{ (event: "close"): void }>()

const { chromeTheme } = storeToRefs(useEditorConfigStore())
const resolvedMode = useResolvedInterfaceMode()

const menuRef = ref<HTMLElement | null>(null)
const activeIndex = ref(-1)
const position = ref<MenuPosition>({})
let closedBySelect = false
let wasOpen = false

const enabledIndexes = computed(() =>
  props.items.reduce<number[]>((acc, item, index) => {
    if (item !== "separator" && !item.disabled) acc.push(index)
    return acc
  }, []),
)

function isMarked(item: MenuItemModel): boolean {
  return item.selected ?? Boolean(item.active)
}

const showMarkerColumn = computed(() =>
  props.items.some((item) => item !== "separator" && isMarked(item)),
)

/**
 * Leading marker slot props for an item. Marked items render a check (or radio
 * dot for `bullet` sets), tinted when also activated; unmarked items render the
 * same glyph hidden so labels stay aligned. Null drops the column entirely.
 */
function markerIcon(item: MenuItemModel): Record<string, unknown> | null {
  if (!showMarkerColumn.value) return null
  const glyph = item.activeMarker === "bullet" ? "material-radioButtonChecked" : "material-check"
  if (isMarked(item)) {
    return {
      icon: glyph,
      "aria-hidden": "true",
      className: item.active ? "sdn-state-activated" : undefined,
    }
  }
  return {
    icon: glyph,
    "aria-hidden": "true",
    style: { visibility: "hidden" },
  }
}

function labelSlot(item: MenuItemModel): Record<string, unknown> {
  return {
    children: item.label,
    "aria-disabled": item.disabled ? "true" : undefined,
    className: item.active ? "sdn-state-activated" : undefined,
    style: item.labelStyle,
  }
}

function shortcutSlot(item: MenuItemModel): Record<string, unknown> | null {
  return item.shortcut ? { children: item.shortcut } : null
}

const containerStyle = computed(() => {
  const px = (value: number | undefined) => (value === undefined ? undefined : `${value}px`)
  return {
    position: "fixed" as const,
    zIndex: 50,
    outline: "none",
    minWidth: props.minWidth,
    top: px(position.value.top),
    bottom: px(position.value.bottom),
    left: px(position.value.left),
    right: px(position.value.right),
  }
})

function place(): void {
  if (!props.anchor) return
  position.value = computeMenuPosition(
    props.anchor.getBoundingClientRect(),
    { width: window.innerWidth, height: window.innerHeight },
    { align: props.align },
  )
}

function focusActive(): void {
  const container = menuRef.value
  if (!container) return
  if (activeIndex.value >= 0) {
    container.querySelector<HTMLElement>(`[data-menu-index="${activeIndex.value}"]`)?.focus()
  } else {
    container.focus()
  }
}

function focusReturnTarget(element: HTMLElement | null): void {
  if (!element?.isConnected) return
  if (element.tabIndex < 0 && !element.hasAttribute("tabindex")) {
    element.tabIndex = -1
  }
  element.focus({ preventScroll: true })
}

function moveActive(direction: 1 | -1): void {
  const indexes = enabledIndexes.value
  if (indexes.length === 0) return
  const current = indexes.indexOf(activeIndex.value)
  let next = current + direction
  if (next < 0) next = indexes.length - 1
  if (next >= indexes.length) next = 0
  activeIndex.value = indexes[next]
}

function onKeydown(event: KeyboardEvent): void {
  switch (event.key) {
    case "ArrowDown":
      event.preventDefault()
      moveActive(1)
      break
    case "ArrowUp":
      event.preventDefault()
      moveActive(-1)
      break
    case "Home":
      event.preventDefault()
      activeIndex.value = enabledIndexes.value[0] ?? -1
      break
    case "End":
      event.preventDefault()
      activeIndex.value = enabledIndexes.value[enabledIndexes.value.length - 1] ?? -1
      break
    case "Escape":
      event.preventDefault()
      emit("close")
      break
    case "Tab":
      emit("close")
      break
  }
}

function handleSelect(item: MenuItemModel): void {
  if (item.disabled) return
  closedBySelect = true
  emit("close")
  item.onSelect?.()
  requestAnimationFrame(() => {
    focusReturnTarget(props.anchor)
    closedBySelect = false
  })
}

function onDocumentPointerDown(event: PointerEvent): void {
  if (!props.open) return
  const target = event.target as Node
  if (menuRef.value?.contains(target)) return
  if (props.anchor?.contains(target)) return
  emit("close")
}

watch(
  () => props.open,
  (open) => {
    if (open) {
      place()
      activeIndex.value = enabledIndexes.value[0] ?? -1
      void nextTick(focusActive)
    } else if (wasOpen && !closedBySelect) {
      focusReturnTarget(props.anchor)
    }
    wasOpen = open
  },
)

// Switching directly between open menus keeps `open` true while the anchor and
// items change, so re-place and re-highlight off the new trigger.
watch(
  () => props.anchor,
  () => {
    if (!props.open) return
    place()
    activeIndex.value = enabledIndexes.value[0] ?? -1
    void nextTick(focusActive)
  },
)

watch(activeIndex, () => {
  if (props.open) void nextTick(focusActive)
})

onMounted(() => {
  document.addEventListener("pointerdown", onDocumentPointerDown, true)
  window.addEventListener("resize", place)
  window.addEventListener("scroll", place, true)
  if (props.open) {
    place()
    activeIndex.value = enabledIndexes.value[0] ?? -1
    wasOpen = true
    void nextTick(focusActive)
  }
})

onBeforeUnmount(() => {
  document.removeEventListener("pointerdown", onDocumentPointerDown, true)
  window.removeEventListener("resize", place)
  window.removeEventListener("scroll", place, true)
})
</script>

<template>
  <Teleport to="body">
    <div
      v-if="open"
      ref="menuRef"
      :tabindex="-1"
      :style="containerStyle"
      :data-theme="chromeTheme"
      :data-mode="resolvedMode"
      @keydown="onKeydown"
    >
      <Menu aria-orientation="vertical" :style="{ minWidth }">
        <template
          v-for="(item, index) in items"
          :key="item === 'separator' ? `separator-${index}` : item.id"
        >
          <Hr v-if="item === 'separator'" />
          <MenuItem
            v-else
            type="button"
            :data-menu-index="index"
            :data-testid="item.testId"
            :disabled="item.disabled"
            :aria-disabled="item.disabled || undefined"
            :tabindex="index === activeIndex ? 0 : -1"
            :icon="markerIcon(item)"
            :text-label="labelSlot(item)"
            :text-label2="shortcutSlot(item)"
            @click="handleSelect(item)"
            @pointerenter="!item.disabled && (activeIndex = index)"
          />
        </template>
      </Menu>
    </div>
  </Teleport>
</template>

// packages/editor/lib/menus/MenuController.tsx
"use client"

import {
  CSSProperties,
  ReactNode,
  RefObject,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react"
import { createPortal } from "react-dom"
import { useEditorConfig } from "@lib/hooks/use-editor-config"
import { useResolvedInterfaceMode } from "@lib/hooks/use-system-color-scheme"
import { MenuItem } from "@seldon/components/elements/MenuItem"
import { Menu } from "@seldon/components/parts/Menu"
import { Hr } from "@seldon/components/primitives/Hr"
import { IconProps } from "@seldon/components/primitives/Icon"
import { MenuAlign, MenuEntry, MenuItem as MenuItemModel } from "./types"
import { useMenuPosition } from "./use-menu-position"

function focusReturnTarget(element: HTMLElement | null | undefined): void {
  if (!element?.isConnected) return
  if (element.tabIndex < 0 && !element.hasAttribute("tabindex")) {
    element.tabIndex = -1
  }
  element.focus({ preventScroll: true })
}

/**
 * Whether an item shows the leading marker. `selected` drives it when set, so an
 * item can be marked without the activated tint or tinted without a marker. When
 * `selected` is omitted the marker follows `active` for plain toggle menus.
 */
function isMarked(item: MenuItemModel): boolean {
  return item.selected ?? Boolean(item.active)
}

/**
 * Leading marker for the active column. Marked items render a check (or radio
 * dot for `bullet` sets), tinted only when the item is also activated; unmarked
 * items render the same glyph hidden so labels stay aligned. Returns null when
 * the menu has no markable items, dropping the column entirely.
 */
function markerIconProps(
  item: MenuItemModel,
  showColumn: boolean,
): IconProps | null {
  if (!showColumn) return null
  const glyph =
    item.activeMarker === "bullet"
      ? "material-radioButtonChecked"
      : "material-check"
  if (isMarked(item)) {
    return {
      icon: glyph,
      "aria-hidden": "true",
      className: item.active ? "sdn-state-activated" : undefined,
    }
  }
  return { icon: glyph, "aria-hidden": "true", style: { visibility: "hidden" } }
}

interface MenuControllerCommon {
  items: MenuEntry[]
  align?: MenuAlign
  minWidth?: string
  /** When set, menu actions restore focus here instead of the trigger. */
  focusTargetRef?: RefObject<HTMLElement | null>
}

/** Aria/handler props the caller spreads onto its trigger element. */
export interface DropdownTriggerProps {
  "aria-haspopup": "menu"
  "aria-expanded": boolean
  onClick: (event: React.MouseEvent) => void
  onKeyDown: (event: React.KeyboardEvent) => void
}

/** Arguments passed to `renderTrigger` in the self-managed trigger mode. */
export interface DropdownRenderTriggerArgs {
  ref: RefObject<HTMLButtonElement | null>
  open: boolean
  toggle: () => void
  triggerProps: DropdownTriggerProps
}

/** Controlled mode: the caller owns `open` and the anchor element. */
type MenuControllerControlledProps = MenuControllerCommon & {
  open: boolean
  anchorRef: RefObject<HTMLElement | null>
  onClose: () => void
  renderTrigger?: never
}

/** Trigger mode: MenuController owns open state and anchors to its own trigger. */
type MenuControllerTriggerProps = MenuControllerCommon & {
  renderTrigger: (args: DropdownRenderTriggerArgs) => ReactNode
  open?: never
  anchorRef?: never
  onClose?: never
}

export type MenuControllerProps = MenuControllerControlledProps | MenuControllerTriggerProps

/**
 * View-model for menus. In controlled mode the caller owns `open`/`anchorRef`
 * (used for headless slot triggers like sidebar row actions). In trigger mode
 * the caller supplies `renderTrigger` and MenuController owns the open state and trigger
 * wiring. Both render the same floating `Menu` View.
 */
export function MenuController(props: MenuControllerProps) {
  if (props.renderTrigger) {
    return <TriggerMenu {...props} />
  }
  return <FloatingMenu {...props} />
}

/**
 * Self-managed trigger wrapper. Owns the open state and an internal trigger ref,
 * hands aria/keyboard props to `renderTrigger`, and anchors the floating menu to
 * that trigger.
 */
function TriggerMenu({
  items,
  align,
  minWidth,
  focusTargetRef,
  renderTrigger,
}: MenuControllerTriggerProps) {
  const [open, setOpen] = useState(false)
  const triggerRef = useRef<HTMLButtonElement | null>(null)
  const toggle = () => setOpen((current) => !current)

  const triggerProps: DropdownTriggerProps = {
    "aria-haspopup": "menu",
    "aria-expanded": open,
    onClick: (event) => {
      event.stopPropagation()
      toggle()
    },
    onKeyDown: (event) => {
      if (event.key === "ArrowDown" || event.key === "ArrowUp") {
        event.preventDefault()
        setOpen(true)
      }
    },
  }

  return (
    <>
      {renderTrigger({ ref: triggerRef, open, toggle, triggerProps })}
      <FloatingMenu
        open={open}
        anchorRef={triggerRef}
        onClose={() => setOpen(false)}
        items={items}
        align={align}
        minWidth={minWidth}
        focusTargetRef={focusTargetRef}
      />
    </>
  )
}

interface FloatingMenuProps extends MenuControllerCommon {
  open: boolean
  anchorRef: RefObject<HTMLElement | null>
  onClose: () => void
}

/**
 * The floating menu surface. Owns positioning, roving-focus keyboard navigation,
 * outside-click and Escape to close, and focus restore, then renders the
 * generated `Menu` View. Item state and visuals come from the generated
 * component CSS: hover from `.sdn-menu-item:hover`, disabled from
 * `aria-disabled`, active from `.sdn-state-activated`, and the highlighted item
 * from `aria-selected` on its leaves.
 */
function FloatingMenu({
  open,
  anchorRef,
  onClose,
  items,
  align = "start",
  minWidth = "180px",
  focusTargetRef,
}: FloatingMenuProps) {
  const { chromeTheme } = useEditorConfig()
  const resolvedMode = useResolvedInterfaceMode()
  const position = useMenuPosition({ open, anchorRef, align })
  const menuRef = useRef<HTMLDivElement>(null)
  const [activeIndex, setActiveIndex] = useState(-1)
  const closedBySelectRef = useRef(false)

  const enabledIndexes = useMemo(
    () =>
      items.reduce<number[]>((acc, item, index) => {
        if (item !== "separator" && !item.disabled) acc.push(index)
        return acc
      }, []),
    [items],
  )

  // Highlight the first enabled item whenever the menu opens.
  useEffect(() => {
    if (open) setActiveIndex(enabledIndexes[0] ?? -1)
  }, [open, enabledIndexes])

  // Move DOM focus to the highlighted item for keyboard navigation.
  useEffect(() => {
    if (!open) return
    if (activeIndex >= 0) {
      menuRef.current
        ?.querySelector<HTMLElement>(`[data-menu-index="${activeIndex}"]`)
        ?.focus()
    } else {
      menuRef.current?.focus()
    }
  }, [open, activeIndex])

  // Restore focus to the trigger when the menu closes without a selection.
  const wasOpen = useRef(false)
  useEffect(() => {
    if (wasOpen.current && !open && !closedBySelectRef.current) {
      focusReturnTarget(anchorRef.current)
    }
    wasOpen.current = open
  }, [open, anchorRef])

  // Close on pointer interactions outside the menu and trigger.
  useEffect(() => {
    if (!open) return
    const handlePointerDown = (event: PointerEvent) => {
      const target = event.target as Node
      if (menuRef.current?.contains(target)) return
      if (anchorRef.current?.contains(target)) return
      onClose()
    }
    document.addEventListener("pointerdown", handlePointerDown, true)
    return () =>
      document.removeEventListener("pointerdown", handlePointerDown, true)
  }, [open, onClose, anchorRef])

  if (open && typeof document === "undefined") return null
  if (!open) return null

  const showMarkerColumn = items.some(
    (item) => item !== "separator" && isMarked(item),
  )

  const moveActive = (direction: 1 | -1) => {
    if (enabledIndexes.length === 0) return
    const currentPosition = enabledIndexes.indexOf(activeIndex)
    let nextPosition = currentPosition + direction
    if (nextPosition < 0) nextPosition = enabledIndexes.length - 1
    if (nextPosition >= enabledIndexes.length) nextPosition = 0
    setActiveIndex(enabledIndexes[nextPosition])
  }

  const handleKeyDown = (event: React.KeyboardEvent) => {
    switch (event.key) {
      case "ArrowDown":
        event.preventDefault()
        moveActive(1)
        break
      case "ArrowUp":
        event.preventDefault()
        moveActive(-1)
        break
      case "Home":
        event.preventDefault()
        setActiveIndex(enabledIndexes[0] ?? -1)
        break
      case "End":
        event.preventDefault()
        setActiveIndex(enabledIndexes[enabledIndexes.length - 1] ?? -1)
        break
      case "Escape":
        event.preventDefault()
        onClose()
        break
      case "Tab":
        onClose()
        break
    }
  }

  // Close before running the action, then move focus off the trigger when the
  // caller supplies a row target (for example after reset removes menu actions).
  const handleSelect = (item: MenuItemModel) => {
    if (item.disabled) return
    closedBySelectRef.current = true
    onClose()
    item.onSelect?.()
    requestAnimationFrame(() => {
      const focusTarget = focusTargetRef?.current
      if (focusTarget?.isConnected) {
        focusReturnTarget(focusTarget)
      } else if (anchorRef.current?.isConnected) {
        focusReturnTarget(anchorRef.current)
      }
      closedBySelectRef.current = false
    })
  }

  const containerStyle: CSSProperties = {
    position: "fixed",
    zIndex: 50,
    outline: "none",
    ...position,
  }

  return createPortal(
    <div
      ref={menuRef}
      tabIndex={-1}
      style={containerStyle}
      onKeyDown={handleKeyDown}
      data-theme={chromeTheme}
      data-mode={resolvedMode}
    >
      <Menu aria-orientation="vertical" style={{ minWidth }}>
        {items.map((item, index) => {
          if (item === "separator") {
            return <Hr key={`separator-${index}`} />
          }
          const highlighted = index === activeIndex
          return (
            <MenuItem
              key={item.id}
              type="button"
              data-menu-index={index}
              data-testid={item.testId}
              disabled={item.disabled}
              aria-disabled={item.disabled || undefined}
              tabIndex={highlighted ? 0 : -1}
              onClick={() => handleSelect(item)}
              onPointerEnter={() => {
                if (!item.disabled) setActiveIndex(index)
              }}
              icon={markerIconProps(item, showMarkerColumn)}
              textLabel={{
                children: item.label,
                "aria-disabled": item.disabled ? "true" : undefined,
                className: item.active ? "sdn-state-activated" : undefined,
                style: item.labelStyle,
              }}
              textLabel2={item.shortcut ? { children: item.shortcut } : null}
            />
          )
        })}
      </Menu>
    </div>,
    document.body,
  )
}
